opensearch-project/opensearch-dashboards-functional-test

- package-lock.json
- package.json
add repo description and also update the dependency version of test library.
https://github.com/opensearch-project/opensearch-dashboards-functional-test/issues/14
> add repo description

- package-lock.json
- package.json
bump test library version to 1.0.2
> bump test library version to 1.0.2

- .github/workflows/cypress-workflow-bundle-snapshot-based.yml
- .github/workflows/cypress-workflow-vanilla-snapshot-based.yml
- .github/workflows/cypress-workflow-vanilla-source-based.yml
- cypress.json
- package-lock.json
This will make it easy to copy all artifacts since they are in a single dir.
Resolves https://github.com/opensearch-project/opensearch-dashboards-functional-test/issues/49
local test to verify the new folder structure
> move test artifacts to a single dir

- CONTRIBUTING.md
Update md for instructions.
resolves https://github.com/opensearch-project/opensearch-dashboards-functional-test/issues/59
> Add onboard instructions for release tests

- .github/workflows/cypress-workflow-bundle-snapshot-based.yml
- .github/workflows/cypress-workflow-plugins-bundle-snapshot-based.yml
- .github/workflows/cypress-workflow-vanilla-snapshot-based.yml
- package.json
Update 1.2 branch https://github.com/opensearch-project/opensearch-dashboards-functional-test/issues/45
> update package version to 1.2.0

- cypress/integration/plugins/reports-dashboards/01-create.spec.js
- cypress/integration/plugins/reports-dashboards/02-edit.spec.js
- cypress/integration/plugins/reports-dashboards/03-details.spec.js
- cypress/integration/plugins/reports-dashboards/04-download.spec.js
- cypress/utils/base_constants.js
- cypress/utils/constants.js
- cypress/utils/plugins/reports-dashboards/constants.js
Signed-off-by: David Cui <davidcui@amazon.com>
Add Reporting cypress test suite 
#78 
> Add Reporting cypress tests

- cypress/fixtures/plugins/index-management-dashboards-plugin/sample_rollover_policy.json
Signed-off-by: bowenlan-amzn <bowenlan23@gmail.com>
Fix the test failure, [test run](https://github.com/opensearch-project/opensearch-dashboards-functional-test/runs/5425516829?check_suite_focus=true)
```
1) Managed indices
can have policies retried
successfully:
AssertionError: Timed out retrying: Expected to find content: 'Failed' but never did.
at Context.eval (http://localhost:5601/__cypress/tests?p=cypress/integration/plugins/index-management-dashboards-plugin/managed_indices_spec.js:253:10)
```
The failure reason is we [update the cypress in our plugin repo](https://github.com/opensearch-project/index-management-dashboards-plugin/commit/5ed6c25ae769bb40d447c5e3e55fb7f89007b926#diff-9de9f25f3db58b6b6d7ad1ebbb4d33690ab9021f99bdb8361cf2697608c3847eR10-R13), but didn't sync the change …
> Fix ISM test failure

- .github/workflows/codeql-analysis.yml
This workflow is failing https://github.com/opensearch-project/opensearch-dashboards-functional-test/actions/runs/1947349906
> fix syntax error in CodeQL workflow

- cypress/integration/plugins/alerting-dashboards-plugin/acknowledge_alerts_modal_spec.js
- cypress/integration/plugins/alerting-dashboards-plugin/alert_spec.js
- cypress/integration/plugins/alerting-dashboards-plugin/alerts_dashboard_flyout_spec.js
- cypress/integration/plugins/alerting-dashboards-plugin/bucket_level_monitor_spec.js
- cypress/integration/plugins/alerting-dashboards-plugin/query_level_monitor_spec.js
Signed-off-by: Annie Lee <leeyun@amazon.com>
Adding the rest of alerting dashboards plugin cypress tests over.
#75 
> Adding all alerting cypress test files

- .github/workflows/backport.yml
- .github/workflows/delete_backport_branch.yml
For backporting PRs to previous version branches if needed.
n/a
> [Github] add backport workflow

- package-lock.json
- package.json
Bump FTRepo to `1.3.1`
https://github.com/opensearch-project/opensearch-dashboards-functional-test/issues/161
> Version bump to 1.3.1

- package-lock.json
- package.json
1.x should at least be >= than 1.3.
https://github.com/opensearch-project/opensearch-dashboards-functional-test/issues/161
> Version bump to 1.3.1 (#165)

- cypress/integration/plugins/anomaly-detection-dashboards-plugin/dashboard_spec.js
- cypress/integration/plugins/anomaly-detection-dashboards-plugin/detector_list_spec.js
- cypress/integration/plugins/anomaly-detection-dashboards-plugin/real_time_results_spec.js
Utilize not.exist for AD tests.
n/a
> [AD] Test improvements to check if item exist

- .github/workflows/alerting-release-e2e-workflow.yml
- .github/workflows/anomaly-detection-release-e2e-workflow.yml
- .github/workflows/cypress-workflow-bundle-snapshot-based.yml
- .github/workflows/cypress-workflow-plugins-bundle-snapshot-based.yml.disabled
- .github/workflows/cypress-workflow-vanilla-snapshot-based.yml
- .github/workflows/cypress-workflow-vanilla-source-based.yml.disabled
- .github/workflows/gantt-chart-release-e2e-workflow.yml
- .github/workflows/index-management-release-e2e-workflow.yml
- .github/workflows/observability-release-e2e-workflow.yml
- .github/workflows/query-workbench-release-e2e-workflow.yml
- .github/workflows/release-e2e-workflow-template.yml
- .github/workflows/release-signoff-chrome.yml
- .github/workflows/release-signoff-chromium-ad-only.yml
- .github/workflows/release-signoff-chromium-ism-only.yml
- .github/workflows/release-signoff-chromium-tests-in-memory-0.yml
- .github/workflows/release-signoff-chromium-tests-in-memory-10.yml
- .github/workflows/release-signoff-chromium-tests-in-memory-20.yml
- .github/workflows/release-signoff-chromium-tests-in-memory-5.yml
- .github/workflows/release-signoff-chromium.yml
- .github/workflows/release-signoff-electron.yml
- .github/workflows/release-signoff-firefox.yml
- .github/workflows/reports-release-e2e-workflow.yml
- .github/workflows/security-release-e2e-workflow.yml
- .gitignore
- package.json
- scripts/getpkgversion.sh
- test_finder.sh
Utilize to pull the version in package.json and utilized in
github workflows.
https://github.com/opensearch-project/opensearch-dashboards-functional-test/issues/142
https://github.com/opensearch-project/opensearch-dashboards-functional-test/issues/189
> [CI] get package version yarn script

- cypress/integration/plugins/observability-dashboards/5_event_analytics.spec.js
- cypress/integration/plugins/observability-dashboards/7_app_analytics.spec.js
- cypress/utils/plugins/observability-dashboards/constants.js
Originally we changed to force the drop down to click but it seems not to be working as expected when we changed the code so not enforcing the focus and slow click like other tests.
n/a
> [Observability] app analytics issue with create

- .eslintrc.json
- CONTRIBUTING.md
- cypress/integration/plugins/alerting-dashboards-plugin/bucket_level_monitor_spec.js
- cypress/integration/plugins/alerting-dashboards-plugin/cluster_metrics_monitor_spec.js
- cypress/integration/plugins/alerting-dashboards-plugin/query_level_monitor_spec.js
- cypress/integration/plugins/index-management-dashboards-plugin/policies_spec.js
- cypress/integration/plugins/observability-dashboards/2_trace_analytics_services.spec.js
- cypress/integration/plugins/observability-dashboards/7_app_analytics.spec.js
- cypress/integration/plugins/reports-dashboards/01-create.spec.js
- cypress/integration/plugins/security/get_started_spec.js
- cypress/utils/plugins/observability-dashboards/constants.js
- package-lock.json
- package.json
* Add ESLint
* Integrate prettier with ESLint
* Apply ESLint rules to project
https://github.com/opensearch-project/opensearch-dashboards-functional-test/issues/186
> Integrate prettier with eslint and apply eslint rules

- .github/workflows/cypress-workflow-vanilla-snapshot-based.yml
- cypress/integration/plugins/anomaly-detection-dashboards-plugin/create_detector_spec.js
- cypress/integration/plugins/anomaly-detection-dashboards-plugin/dashboard_spec.js
- cypress/integration/plugins/anomaly-detection-dashboards-plugin/detector_configuration_spec.js
- cypress/integration/plugins/anomaly-detection-dashboards-plugin/detector_list_spec.js
- cypress/integration/plugins/anomaly-detection-dashboards-plugin/historical_analysis_spec.js
- cypress/integration/plugins/anomaly-detection-dashboards-plugin/overview_spec.js
- cypress/integration/plugins/anomaly-detection-dashboards-plugin/real_time_results_spec.js
- cypress/integration/plugins/anomaly-detection-dashboards-plugin/sample_detector_spec.js
- cypress/integration/plugins/observability-dashboards/6_notebooks.spec.js
- cypress/integration/plugins/observability-dashboards/7_app_analytics.spec.js
- cypress/integration/plugins/reports-dashboards/02-edit.spec.js
- cypress/integration/plugins/security/roles_spec.js
- cypress/utils/plugins/anomaly-detection-dashboards-plugin/commands.js
- cypress/utils/plugins/anomaly-detection-dashboards-plugin/constants.js
- cypress/utils/plugins/security/commands.js
- package-lock.json
- package.json
> Upgrade cypress to ^9.5.4

- package-lock.json
- package.json
Signed-off-by: Zelin Hao <zelinhao@amazon.com>
Incremented version to 1.3.2.
Part of https://github.com/opensearch-project/opensearch-build/issues/1882
> Incremented version to 1.3.2.

- package-lock.json
Main for test library was bumped. Ensuring integrity for changes.
n/a
> Bump test libary to 1.0.4

- package-lock.json
Version was bumped but the SHA needed to be updated
n/a
> [Build] update test library sha

- .github/workflows/cypress-workflow-bundle-snapshot-based.yml
- .github/workflows/cypress-workflow-plugins-bundle-snapshot-based.yml
- .github/workflows/cypress-workflow-vanilla-snapshot-based.yml
- CONTRIBUTING.md
- package.json
Create a 1.0 branch, and update the version to be 1.0
> update the version to be 1.0

- .github/workflows/cypress-workflow-bundle-snapshot-based.yml
- .github/workflows/cypress-workflow-plugins-bundle-snapshot-based.yml
- .github/workflows/cypress-workflow-vanilla-snapshot-based.yml
- CONTRIBUTING.md
- package.json
Create a 1.1 branch, and update version to be 1.1
> update version to be 1.1

- integtest.sh
- test_finder.sh
Signed-off-by: Peter Zhu <zhujiaxi@amazon.com>
Add test component selector to run specific tests
Part of #110 
https://github.com/opensearch-project/opensearch-build/issues/2144
> Add test component selector to run specific tests

- package-lock.json
- package.json
https://github.com/opensearch-project/opensearch-build/issues/2101
https://github.com/opensearch-project/opensearch-build/issues/2101
> Version Increment to 1.3.3 OpenSearch Dashboard release

- site/index.html
- site/js/dashboard.js
Pass query params with URL for sharing links.
n/a
> [Site] add ability to pass query params

- site/index.html
- site/js/dashboard.js
- site/styles.css
1.x specs can be different so updated to help with finding that.
Still hardcoded though.
Also a quick note about the path to access the image.
n/a
> [Site] handle 1.x version links and helper for accessing images

- package.json
Bump version of the functional test repo to the next release
n/a
> Bump version to 2.1

- CONTRIBUTING.md
https://github.com/opensearch-project/opensearch-dashboards-functional-test/issues/265
Resolves https://github.com/opensearch-project/opensearch-dashboards-functional-test/issues/265
> Update the release strategy

- package-lock.json
- package.json
Signed-off-by: Zelin Hao <zelinhao@amazon.com>
Version increment for 1.3.4
Part of https://github.com/opensearch-project/opensearch-build/issues/2205
> Version increment for 1.3.4

- package.json
Update the version to be 2.2.0
- [ X ] Commits are signed per the DCO using --signoff
> update the version to be 2.2.0

- package-lock.json
- package.json
Signed-off-by: prudhvigodithi <pgodithi@amazon.com>
Incremented version to 1.3.5.
Part of: https://github.com/opensearch-project/opensearch-build/issues/2348
> [Release 1.3.5] Version increment

- package.json
Signed-off-by: prudhvigodithi <pgodithi@amazon.com>
Version increment 2.2.1
Part of: https://github.com/opensearch-project/opensearch-build/issues/2481
> Version increment 2.2.1

- package.json
Signed-off-by: Louis Chu <lingzhichu.clz@gmail.com>
update version to be 2.4.0
#286 
> update version to be 2.4.0

- package-lock.json
- package.json
Signed-off-by: Zelin Hao <zelinhao@amazon.com>
Version bump to 1.3.6
Part of https://github.com/opensearch-project/opensearch-build/issues/2650
> Version increment to 1.3.6

- CONTRIBUTING.md
- cypress/integration/plugins/anomaly-detection-dashboards-plugin/historical_analysis_spec.js
- cypress/integration/plugins/anomaly-detection-dashboards-plugin/overview_spec.js
- cypress/integration/plugins/custom-import-map-dashboards/import_vector_map_tab.spec.js
Add instructions for tests for experimental features. The lint failed due to previous commits and I tried to fix along with the PR. (Thanks @ashwin-pc for creating an issue for lint https://github.com/opensearch-project/opensearch-dashboards-functional-test/issues/307)
> [doc] Add instructions for tests for experimental features

- CONTRIBUTING.md
- cypress/integration/plugins/anomaly-detection-dashboards-plugin/historical_analysis_spec.js
- cypress/integration/plugins/anomaly-detection-dashboards-plugin/overview_spec.js
- cypress/integration/plugins/custom-import-map-dashboards/import_vector_map_tab.spec.js
* Add instructions for tests for experimental features
* add more
* add todo
* enhance readability
* update
* update format
* capitalize
* add example
* add cypress configuration example
(cherry picked from commit 4617754afe51640acf6eb2b29c3613592e1181a3)
[List any issues …
> [doc] Add instructions for tests for experimental features (#317)

- .eslintrc.json
- cypress/integration/common/dashboard_sample_data_spec.js
- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/dashboard_sanity_test_spec.js
- cypress/integration/core-opensearch-dashboards/vanilla-opensearch-dashboards/dashboard_filtering_spec.js
- cypress/integration/plugins/notifications-dashboards/1_email_senders_and_groups.spec.js
- cypress/integration/plugins/notifications-dashboards/2_channels.spec.js
- cypress/integration/plugins/query-workbench-dashboards/ui.spec.js
- cypress/plugins/index.js
- cypress/support/index.js
- cypress/utils/plugins/notifications-dashboards/constants.js
- cypress/utils/plugins/query-workbench-dashboards/constants.js
- index.js
- package-lock.json
- package.json
- site/js/dashboard.js
(cherry picked from commit 317f15665b900737565eff8c8b0b8534f47ddac1)
> Adds linter rules for license and import. Fixes linting (#319)

- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/datasource-management-plugin/3_update_datasource.spec.js
Signed-off-by: mpabba3003 <amazonmanideep@gmail.com>
[MD] update functional tests on edit/update datasource as per UX changes
[#2621](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/2621)
[#2622](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/2622)
https://user-images.githubusercontent.com/109986843/197042408-f0f58e3e-1c94-4aae-ad92-8329426b715f.mp4
> [MD] update functional tests on edit/update datasource as per UX changes

- .github/workflows/search-relevance-release-e2e-workflow.yml
- cypress/integration/plugins/search-relevance-dashboards/1_query_compare.spec.js
- cypress/utils/plugins/search-relevance-dashboards/constants.js
- test_finder.sh
Signed-off-by: Mingkun Ma <mingkunm@amazon.com>
Add integration test for Search Relevance Dashboards 
> Add integration test for Search Relevance Dashboards

- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/vis_builder/vis_types/area.spec.js
- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/vis_builder/vis_types/bar.spec.js
- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/vis_builder/vis_types/line.spec.js
Allows for rounding errors in VisBuilder
> [VisBuilder] Allow rounding errors

- .github/workflows/security-analytics-release-e2e-workflow.yml
- cypress/integration/plugins/security-analytics-dashboards-plugin/rules_spec.js
- cypress/support/index.js
- cypress/utils/constants.js
- cypress/utils/plugins/security-analytics-dashboards-plugin/commands.js
- cypress/utils/plugins/security-analytics-dashboards-plugin/constants.js
- site/js/dashboard.js
- test_finder.sh
Onboarding security analytics dashboards plugin. Security analytics 3.0 isn't available yet, so submitting this PR directly to the function test repo 2.x branch.
> Onboarding security analytics dashboards plugin.

- package.json
> Bump to 2.5.0

- package-lock.json
- package.json
Signed-off-by: Rishabh Singh <sngri@amazon.com>
Version increment to 1.3.7
> Version increment to 1.3.7

- DEVELOPER_GUIDE.md
- cypress/fixtures/dashboard/opensearch_dashboards/visBuilder/prepare_data.md
- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/vis_builder/vis_types/area.spec.js
- docs/writing_tests.md
- package-lock.json
- package.json
- scripts/generate_data/basic_generator.js
- scripts/generate_data/index.js
- Adds test data generation script
- Adds docs for writing tests
- Updates developer guide
#290
> Generate test data script

- cypress/integration/plugins/custom-import-map-dashboards/documentsLayer.spec.js
- cypress/integration/plugins/custom-import-map-dashboards/opensearchMapLayer.spec.js
Signed-off-by: Junqiu Lei <junqiu@amazon.com>
Because Multi-layer maps App will be added to custom-import-map plugin, adding new tests for it.
Tests results can be found at: https://github.com/opensearch-project/dashboards-maps/pull/174
> Add new tests to custom-import-map

- cypress/integration/plugins/index-management-dashboards-plugin/aliases.js
- cypress/integration/plugins/index-management-dashboards-plugin/create_index.js
- cypress/integration/plugins/index-management-dashboards-plugin/indices_spec.js
- cypress/integration/plugins/index-management-dashboards-plugin/reindex_spec.js
- cypress/integration/plugins/index-management-dashboards-plugin/snapshots_spec.js
- cypress/integration/plugins/index-management-dashboards-plugin/split_index.js
- cypress/integration/plugins/index-management-dashboards-plugin/templates.js
- cypress/utils/plugins/index-management-dashboards-plugin/commands.js
Signed-off-by: suzhou <suzhou@amazon.com>
> feat: add function test for IM plugin on v2.5

- package-lock.json
- package.json
Signed-off-by: Rishabh Singh <sngri@amazon.com>
Bump version to 1.3.8
> Bump version to 1.3.8

- cypress/integration/plugins/security-analytics-dashboards-plugin/rules_spec.js
- cypress/support/index.js
- cypress/utils/constants.js
- cypress/utils/plugins/index-management-dashboards-plugin/commands.js
- cypress/utils/plugins/security-analytics-dashboards-plugin/commands.js
- site/js/dashboard.js
Clean up linter issues with:
`yarn lint --fix`
n/a
> Clean up linter issues

- cypress/integration/plugins/custom-import-map-dashboards/documentsLayer.spec.js
Signed-off-by: Junqiu Lei <junqiu@amazon.com>
Fix flaky test in maps
> Fix flaky test in maps

- cypress/integration/plugins/reports-dashboards/01-create.spec.js
- cypress/integration/plugins/reports-dashboards/02-edit.spec.js
- cypress/integration/plugins/reports-dashboards/04-download.spec.js
- cypress/utils/plugins/reports-dashboards/constants.js
Signed-off-by: Rupal Mahajan <maharup@amazon.com>
- Added fix for flaky test.
- Increased timeout
https://github.com/opensearch-project/dashboards-reporting/issues/23
> Update reports test

- cypress/integration/plugins/observability-dashboards/3_trace_analytics_traces.spec.js
- cypress/integration/plugins/observability-dashboards/5_event_analytics.spec.js
- cypress/integration/plugins/observability-dashboards/6_notebooks.spec.js
- cypress/integration/plugins/observability-dashboards/7_app_analytics.spec.js
Update dashboards observability tests
> Update dashboards observability tests

- cypress/integration/plugins/observability-dashboards/6_notebooks.spec.js
- cypress/integration/plugins/observability-dashboards/7_app_analytics.spec.js
Fix failing notebook and app analytics tests.
> Update notebook and app analytics tests

- package.json
Signed-off-by: Hu <qingyah@bcd074412c0b.ant.amazon.com>
Increment version to 2.5.1 on 2.5 branch
> Increment version to 2.5.1 on 2.5 branch

- cypress/integration/plugins/observability-dashboards/3_trace_analytics_traces.spec.js
- cypress/utils/plugins/observability-dashboards/constants.js
* fix time zone
* make more general for any time zone
---------
(cherry picked from commit 4c70c1a484247bd4b14eed68ee3edd98d40ea88c)
> [BACKPORT 2.3] fix time zone for trace analytics test (#529)

- cypress/integration/plugins/observability-dashboards/3_trace_analytics_traces.spec.js
- cypress/utils/plugins/observability-dashboards/constants.js
* fix time zone
* make more general for any time zone
---------
(cherry picked from commit 4c70c1a484247bd4b14eed68ee3edd98d40ea88c)
> [BACKPORT 2.0] fix time zone for trace analytics test (#529)

- cypress/integration/plugins/observability-dashboards/3_trace_analytics_traces.spec.js
- cypress/utils/plugins/observability-dashboards/constants.js
* fix time zone
* make more general for any time zone
---------
(cherry picked from commit 4c70c1a484247bd4b14eed68ee3edd98d40ea88c)
> [BACKPORT 2.1] fix time zone for trace analytics test (#529)

- cypress/integration/plugins/observability-dashboards/3_trace_analytics_traces.spec.js
- cypress/utils/plugins/observability-dashboards/constants.js
* fix time zone
* make more general for any time zone
---------
(cherry picked from commit 4c70c1a484247bd4b14eed68ee3edd98d40ea88c)
> [BACKPORT 2.2] fix time zone for trace analytics test (#529)

- cypress/integration/plugins/query-workbench-dashboards/ui.spec.js
> Fix Sql timeout

- cypress/integration/plugins/anomaly-detection-dashboards-plugin/create_detector_spec.js
- cypress/integration/plugins/anomaly-detection-dashboards-plugin/detector_configuration_spec.js
- cypress/integration/plugins/anomaly-detection-dashboards-plugin/historical_analysis_spec.js
- cypress/integration/plugins/anomaly-detection-dashboards-plugin/sample_detector_spec.js
- cypress/utils/commands.js
Cleans up resource deletion (index & detector) for tests to prevent flaky failures,
Passed locally based on `main` tips of AD repos:
```
(Run Finished)
Spec                                              Tests  Passing  Failing  Pending  Skipped
│ ✔  plugins/anomaly-detection-dashboard      00:32        1        1        -        -        - │
│    s-plugin/create_detector_spec.js                                                            │
├────────────────────────────────────────────────────────────────────────────────────────────────┤
│ ✔  plugins/anomaly-detection-dashboard      00:29        8        8        -        -        - │
│    s-plugin/dashboard_spec.js …
```
> Clean up flaky resource deletion for AD tests

- cypress/integration/plugins/observability-dashboards/3_trace_analytics_traces.spec.js
> fix missed test case for dates

- .github/workflows/ml-commons-release-e2e-workflow.yml
- cypress/integration/plugins/ml-commons-dashboards/overview_spec.js
- cypress/support/index.js
- cypress/utils/constants.js
- cypress/utils/plugins/ml-commons-dashboards/commands.js
- cypress/utils/plugins/ml-commons-dashboards/constants.js
- test_finder.sh
Add functional test for ml-commons-dashboards overview page
> Add functional test for ml-commons-dashboards overview page

- cypress/integration/plugins/index-management-dashboards-plugin/aliases.js
- cypress/integration/plugins/index-management-dashboards-plugin/managed_indices_spec.js
- cypress/integration/plugins/index-management-dashboards-plugin/policies_spec.js
> Fix: failed test spec on 2.6

- cypress/integration/plugins/custom-import-map-dashboards/documentsLayer.spec.js
- cypress/integration/plugins/custom-import-map-dashboards/opensearchMapLayer.spec.js
Remove all indices after test case run finished
https://github.com/opensearch-project/opensearch-dashboards-functional-test/issues/577
> Maps: remove indices after run

- package-lock.json
- package.json
Signed-off-by: Divya Madala <divyaasm@amazon.com>
Version bump from 1.3.8 to 1.3.9
> Increment version to 1.3.9

- package.json
> Chore: bump version to 2.7.0

- package-lock.json
Points the FTR repo to the latest commit for the test library changes.
> updates package lock for new library changes

- cypress/utils/dashboards/commands.js
- package-lock.json
We no longer need to make the change so reverting the changes to the functional test repo
> Revert changes for OUI 1.1

- cypress/integration/plugins/index-management-dashboards-plugin/create_index.js
- cypress/integration/plugins/index-management-dashboards-plugin/data_streams.js
- cypress/integration/plugins/index-management-dashboards-plugin/force_merge.js
- cypress/integration/plugins/index-management-dashboards-plugin/rollover.js
- cypress/integration/plugins/index-management-dashboards-plugin/template_components.js
- cypress/integration/plugins/index-management-dashboards-plugin/templates.js
- cypress/utils/commands.js
- cypress/utils/plugins/index-management-dashboards-plugin/commands.js
- cypress/utils/plugins/index-management-dashboards-plugin/constants.js
> Add ISM cypress test for 2.7

- cypress/utils/plugins/observability-dashboards/constants.js
Update Observability tests
- Event analytics
- App analytics
> Update url for observability event and app analytics

- cypress/integration/plugins/observability-dashboards/6_notebooks.spec.js
Update notebooks tests for 2.7
> Update notebooks test for 2.7

- cypress/integration/plugins/observability-dashboards/1_trace_analytics_dashboard.spec.js
- cypress/integration/plugins/observability-dashboards/2_trace_analytics_services.spec.js
- cypress/integration/plugins/observability-dashboards/3_trace_analytics_traces.spec.js
-  Update traces tests for 2.7
> Update traces tests for 2.7

- site/index.html
- site/js/dashboard.js
> [Site] add ML Commons to test explorer

- cypress/integration/plugins/observability-dashboards/1_trace_analytics_dashboard.spec.js
- cypress/integration/plugins/observability-dashboards/2_trace_analytics_services.spec.js
- cypress/integration/plugins/observability-dashboards/3_trace_analytics_traces.spec.js
- cypress/integration/plugins/observability-dashboards/4_panels.spec.js
- cypress/utils/plugins/observability-dashboards/constants.js
- Update panel tests
- Update trace tests
This needs to be backported to 2.7 and 2.x.
> Update Observability panel and trace tests

- cypress/integration/plugins/custom-import-map-dashboards/add_saved_object.spec.js
Fix Failing Test in custom-import-map-dashboards
> Fix Failing Test in custom-import-map-dashboards

- package.json
Bump version to 2.8 per release process.
N/a
> Bump version to 2.8

- package.json
Bump version to patch version per post release activities.
https://github.com/opensearch-project/opensearch-dashboards-functional-test/issues/602
> Bump version to 2.7.1

- test_finder.sh
Remove duplicate securityAnalyticsDashboards
https://github.com/opensearch-project/opensearch-build/issues/3434
> [2.x] Remove duplicate securityAnalyticsDashboards

- .github/workflows/cypress-workflow-vanilla-snapshot-based.yml
- .github/workflows/release-signoff-chrome.yml
- .github/workflows/release-signoff-chromium-tests-in-memory-0.yml
- .github/workflows/release-signoff-chromium-tests-in-memory-10.yml
- .github/workflows/release-signoff-chromium-tests-in-memory-20.yml
- .github/workflows/release-signoff-chromium-tests-in-memory-5.yml
- .github/workflows/release-signoff-chromium.yml
- .github/workflows/release-signoff-electron.yml
- .github/workflows/release-signoff-firefox.yml
Backport changes to 1.3 in #676
#676
> Backport changes to 1.3 in #676

- .github/workflows/release-e2e-workflow-template.yml
- .github/workflows/release-signoff-chrome.yml
- .github/workflows/release-signoff-chromium-ad-only.yml
- .github/workflows/release-signoff-chromium-ism-only.yml
- .github/workflows/release-signoff-chromium-tests-in-memory-0.yml
- .github/workflows/release-signoff-chromium-tests-in-memory-10.yml
- .github/workflows/release-signoff-chromium-tests-in-memory-20.yml
- .github/workflows/release-signoff-chromium-tests-in-memory-5.yml
- .github/workflows/release-signoff-chromium.yml
- .github/workflows/release-signoff-electron.yml
- .github/workflows/release-signoff-firefox.yml
Tweak dir path for osd after untar
#676 follow up
> Tweak dir path for osd after untar

- cypress/integration/plugins/index-management-dashboards-plugin/aliases.js
- cypress/integration/plugins/index-management-dashboards-plugin/data_streams.js
- cypress/integration/plugins/index-management-dashboards-plugin/force_merge.js
- cypress/integration/plugins/index-management-dashboards-plugin/indices_spec.js
- cypress/integration/plugins/index-management-dashboards-plugin/notification_settings.js
- cypress/integration/plugins/index-management-dashboards-plugin/refresh_index.js
- cypress/integration/plugins/index-management-dashboards-plugin/template_components.js
> Add cypress test of index management dashboards plugin on 2.8

- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/vis_type_table/data.spec.js
- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/vis_type_table/split.spec.js
- cypress/utils/dashboards/vis_type_table/constants.js
- cypress/utils/dashboards/vis_type_table/table.js
Update create table URL and add workaround for style rendering issue here: https://github.com/opensearch-project/OpenSearch-Dashboards/issues/4157
n/a
> Update create table url and address style render

- .github/CODEOWNERS
- MAINTAINERS.md
The maintainers have voted and agreed to this nomination.
Thank you @ananzh!
> [Admin] add ananzh as maintainer

- .github/CODEOWNERS
- MAINTAINERS.md
Add Prudhvi as new functional test repo maintainer
> Add Prudhvi as new functional test repo maintainer

- .github/CODEOWNERS
- MAINTAINERS.md
[This repo has not been very well maintained. I have a team that will take over. Adding these folks as maintainers and plan to catch up on PRs, unaddressed issues, etc]
[N/A]
> Add more maintainers

- package.json
Bump version to 2.8.1 per release process.
https://github.com/opensearch-project/opensearch-dashboards-functional-test/issues/666
> Bump version to 2.8.1

- package.json
Bump version to 2.9 per release process.
https://github.com/opensearch-project/opensearch-dashboards-functional-test/issues/666
> Bump version to 2.9

- site/index.html
- site/js/dashboard.js
- site/styles.css
Manual backport of https://github.com/opensearch-project/opensearch-dashboards-functional-test/pull/711
> [Manual][Backport 2.x][Site] add OSD results (#711)

- package-lock.json
- package.json
> fix: Bump tough-cookie and word-wrap versions

- package.json
> Increment version to 1.3.12

- cypress/integration/common/dashboard_sample_data_spec.js
Fix a cypress test for legacy discover.
> Fix cypress test for legacy discover

- cypress/integration/common/dashboard_sample_data_spec.js
> Fix cypress for data explorer

- cypress/integration/plugins/gantt-chart-dashboards/gantt_ui.spec.js
- cypress/integration/plugins/query-workbench-dashboards/ui.spec.js
> [Backport 1.2] Removing form field in gantt-chart, observability and workbench (#424)

- cypress/integration/plugins/gantt-chart-dashboards/gantt_ui.spec.js
- cypress/integration/plugins/query-workbench-dashboards/ui.spec.js
> [Backport 1.1] Removing form field in gantt-chart, observability and workbench (#424)

- cypress/integration/plugins/gantt-chart-dashboards/gantt_ui.spec.js
- cypress/integration/plugins/query-workbench-dashboards/ui.spec.js
> [Backport 1.0] Removing form field in gantt-chart, observability and workbench (#424)

- cypress/integration/plugins/gantt-chart-dashboards/gantt_ui.spec.js
> updated format for time

- package.json
Bump version on 2.x branch
Related to: https://github.com/opensearch-project/opensearch-dashboards-functional-test/issues/766
> Increment version from 2.10 to 2.11

- cypress/fixtures/plugins/alerting-dashboards-plugin/sample_cluster_metrics_health_monitor.json
- cypress/fixtures/plugins/alerting-dashboards-plugin/sample_cluster_metrics_stats_monitor.json
- cypress/fixtures/plugins/alerting-dashboards-plugin/sample_composite_level_monitor.json
- cypress/integration/plugins/alerting-dashboards-plugin/cluster_metrics_monitor_spec.js
- cypress/integration/plugins/alerting-dashboards-plugin/composite_level_monitor_spec.js
- cypress/integration/plugins/alerting-dashboards-plugin/monitors_dashboard_spec.js
- cypress/integration/plugins/alerting-dashboards-plugin/query_level_monitor_spec.js
- cypress/utils/plugins/alerting-dashboards-plugin/commands.js
- cypress/utils/plugins/alerting-dashboards-plugin/constants.js
Add new tests for alerting dashboards for composite workflows and monitor dashboards
N/A
> Add new tests for alerting dashboards

- cypress/integration/plugins/security-analytics-dashboards-plugin/1_detectors.spec.js
- cypress/utils/plugins/security-analytics-dashboards-plugin/commands.js
- cypress/utils/plugins/security-analytics-dashboards-plugin/constants.js
- cypress/utils/plugins/security-analytics-dashboards-plugin/index.d.ts
Updated cypress commands to remove conflicts
#834 
> Updated cypress commands to avoid duplication

- package.json
Bump version to 1.3.13
Part of https://github.com/opensearch-project/opensearch-build/issues/3878
> Bump version to 1.3.13

- cypress/integration/plugins/observability-dashboards/1_trace_analytics_dashboard.spec.js
- cypress/integration/plugins/observability-dashboards/4_panels.spec.js
- cypress/utils/plugins/observability-dashboards/constants.js
Fix flaky tests for Trace Analytics and Panels for 2.10 release candidate Integ test failures
> Fix flaky tests for Trace Analytics and Panels

- cypress/integration/plugins/security-analytics-dashboards-plugin/3_alerts.spec.js
Excluding flaky test for security analytics Alerts test suite.
> [Security Analytics 2.10] Excluded flaky test from alerts test suite

- cypress/integration/plugins/observability-dashboards/7_app_analytics.spec.js
- cypress/integration/plugins/reports-dashboards/04-download.spec.js
Remove flaky tests for 1.3 release
> Remove flaky tests for 1.3 release

- package.json
Bump version from 2.10.0 to 2.10.1
https://github.com/opensearch-project/opensearch-dashboards-functional-test/issues/766
> [2.10] Bump patch version

- cypress/integration/plugins/alerting-dashboards-plugin/composite_level_monitor_spec.js
> [Alerting] Update alerting tests in main

- cypress/integration/plugins/alerting-dashboards-plugin/composite_level_monitor_spec.js
Fix flaky composite level tests
N/A
> Resolve flaky composite level tests

- cypress/integration/plugins/security-analytics-dashboards-plugin/1_detectors.spec.js
- cypress/integration/plugins/security-analytics-dashboards-plugin/2_rules.spec.js
- cypress/integration/plugins/security-analytics-dashboards-plugin/3_alerts.spec.js
- cypress/integration/plugins/security-analytics-dashboards-plugin/4_findings.spec.js
- cypress/utils/plugins/security-analytics-dashboards-plugin/commands.js
- cypress/utils/plugins/security-analytics-dashboards-plugin/constants.js
- cypress/utils/plugins/security-analytics-dashboards-plugin/index.d.ts
> [Backport 2.11] Security analytics latest tests (#825)

- cypress/integration/plugins/reports-dashboards/04-download.spec.js
> Skip flaky reporting test

- cypress/integration/plugins/custom-import-map-dashboards/documentsLayer.spec.js
Signed-off-by: Heemin Kim <heemin@amazon.com>
(cherry picked from commit d97e8916090174df8719af81f3d77d546ee4b5b5)
> [Backport 2.11]Add wait time after selecting a color (#936)

- cypress/integration/plugins/custom-import-map-dashboards/documentsLayer.spec.js
Signed-off-by: Heemin Kim <heemin@amazon.com>
(cherry picked from commit d97e8916090174df8719af81f3d77d546ee4b5b5)
> [Backport 2.x]Add wait time after selecting a color (#936)

- package.json
Bump version to 1.3.14
Part of https://github.com/opensearch-project/opensearch-build/issues/4069
> Bump version to 1.3.14

- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/vis_type_table/embed.spec.js
- cypress/utils/plugins/observability-dashboards/constants.js
Add suppress observer for table vis test cigroup2. Also fix the typo in the function name.
> Add suppress observer for table vis test

- package.json
> bump version from 2.11 to 2.12

- cypress/integration/plugins/dashboards-assistant/feedback_spec.js
add test cases for assistant feedback
> add test cases for assistant feedback

- cypress/integration/plugins/observability-dashboards/7_integrations.spec.js
Making a duplicate of #1015 backporting #990 since the DCO action doesn't seem to like my signoff in the autocreated version.
N/A
> [Manual Backport] 990 to 2.x

- cypress/integration/plugins/security-analytics-dashboards-plugin/1_detectors.spec.js
- cypress/integration/plugins/security-analytics-dashboards-plugin/2_rules.spec.js
- cypress/integration/plugins/security-analytics-dashboards-plugin/3_alerts.spec.js
- cypress/integration/plugins/security-analytics-dashboards-plugin/4_findings.spec.js
- cypress/utils/plugins/security-analytics-dashboards-plugin/constants.js
- cypress/utils/plugins/security-analytics-dashboards-plugin/helpers.js
Updated tests for security analytics dashboards plugin
https://github.com/opensearch-project/security-analytics-dashboards-plugin/issues/857
> [2.12] Update security analytics tests

- cypress/integration/plugins/reports-dashboards/04-download.spec.js
Fix Download csv from saved search in-context menu test
N/A
- [ x] Commits are signed per the DCO using --signoff
> Fix reports dashboards test

- cypress/integration/plugins/query-workbench-dashboards/ui.spec.js
Sets sql download option form to true
> Fix query workbench tests

- .github/workflows/assistant-release-e2e-workflow.yml
- cypress/integration/plugins/dashboards-assistant/chatbot_interaction_trace_spec.js
- cypress/support/assistant-dummy-llm.js
ml-commons changes the prompt when using tool in agent framework 
> Fix assistant failed cases because of change of ml-commons

- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/data_explorer/shared_links.spec.js
Reverts opensearch-project/opensearch-dashboards-functional-test#1079
https://github.com/opensearch-project/opensearch-dashboards-functional-test/pull/1079#issuecomment-1967885419
> Revert "fixed failed discover app shared links tests"

- package.json
Bump version to 1.3.15
[[RELEASE] Release version 1.3.15](https://github.com/opensearch-project/opensearch-build/issues/4294)
> Bump version to 1.3.15

- package.json
Upgrade version
https://github.com/opensearch-project/opensearch-dashboards-functional-test/issues/914
> bump version from 2.12 to 2.13

- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/data_explorer/date_nanos.spec.js
- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/data_explorer/date_nanos_mixed.spec.js
- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/data_explorer/discover.spec.js
- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/data_explorer/field_data.spec.js
- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/data_explorer/index_pattern_with_encoded_id.spec.js
- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/data_explorer/index_pattern_without_field.spec.js
- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/data_explorer/saved_queries.spec.js
- cypress/utils/dashboards/data_explorer/commands.js
This reverts commit 861f8b2253c5d986a7a2d2351722e03ab1d83758.
> Revert "[Discover] toggle for legacy mode (#1148)"

- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/data_explorer/date_nanos.spec.js
- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/data_explorer/date_nanos_mixed.spec.js
- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/data_explorer/discover.spec.js
- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/data_explorer/field_data.spec.js
- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/data_explorer/index_pattern_with_encoded_id.spec.js
- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/data_explorer/index_pattern_without_field.spec.js
- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/data_explorer/saved_queries.spec.js
- cypress/utils/dashboards/data_explorer/commands.js
Update tests related to switching from legacy view within the Discover page.
Requires:
https://github.com/opensearch-project/OpenSearch-Dashboards/pull/6170
n/a
> [Discover] update tests related to legacy view

- cypress/integration/plugins/ml-commons-dashboards/overview_spec.js
- cypress/utils/plugins/ml-commons-dashboards/commands.js
- cypress/utils/plugins/ml-commons-dashboards/constants.js
Change to use pre trained models for testing
> Change to use pre trained model

- cypress/integration/plugins/custom-import-map-dashboards/4_documentsLayer.spec.js
> [backport 2.x] Update data source name and rebase code in maps (#1147)

- cypress/fixtures/plugins/security-analytics-dashboards-plugin/sample_aws_s3_rule_to_import.yml
- cypress/integration/plugins/security-analytics-dashboards-plugin/1_detectors.spec.js
- cypress/integration/plugins/security-analytics-dashboards-plugin/2_rules.spec.js
- cypress/integration/plugins/security-analytics-dashboards-plugin/4_findings.spec.js
Updated tests for 2.13 release
> [Security analytics][2.x] Updated tests 2.13 release

- cypress/integration/plugins/security-analytics-dashboards-plugin/2_rules.spec.js
Update-security-analytics-tests
https://github.com/opensearch-project/security-analytics-dashboards-plugin/issues/963
> [Security Analytics][2.13] Updates rules tests

- cypress/integration/plugins/security-analytics-dashboards-plugin/1_detectors.spec.js
- cypress/integration/plugins/security-analytics-dashboards-plugin/3_alerts.spec.js
- cypress/integration/plugins/security-analytics-dashboards-plugin/4_findings.spec.js
- cypress/integration/plugins/security-analytics-dashboards-plugin/5_integrations.spec.js
- cypress/utils/plugins/security-analytics-dashboards-plugin/commands.js
- cypress/utils/plugins/security-analytics-dashboards-plugin/helpers.js
Fixed security analytics tests.
> [2.5] Fixed security analytics tests

- cypress/integration/plugins/security-analytics-dashboards-plugin/1_detectors.spec.js
- cypress/integration/plugins/security-analytics-dashboards-plugin/2_rules.spec.js
- cypress/integration/plugins/security-analytics-dashboards-plugin/3_alerts.spec.js
- cypress/integration/plugins/security-analytics-dashboards-plugin/4_findings.spec.js
- cypress/utils/plugins/security-analytics-dashboards-plugin/constants.js
- cypress/utils/plugins/security-analytics-dashboards-plugin/helpers.js
- cypress/utils/plugins/security-analytics-dashboards-plugin/rules.js
Updates integ tests for security analytics 2.7
> [Security analytics] Update 2.7 tests

- cypress/integration/plugins/security/tenants_spec.js
Follow up need since the copy on these pages was modified in https://github.com/opensearch-project/security-dashboards-plugin/pull/1881
- Resolves https://github.com/opensearch-project/security-dashboards-plugin/issues/1893
> [Security Plugin] Update tenant header identifiers

- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/workspace-plugin/workspace_dropdown_menu.spec.js
- cypress/utils/dashboards/workspace-plugin/commands.js
Tests for workspace dropdown menu
> [Workspace] add tests for workspace dropdown menu

- site/js/dashboard.js
The test files has been renamed in #1229 , this PR is for correcting the wrong test name in results site.
> Update test name in results site

- site/js/dashboard.js
This PR is for manual backport #1247 to 2.x
> Manual backport #1247 to 2.x

- cypress/fixtures/plugins/security-analytics-dashboards-plugin/integration_tests/rule/create_windows_usb_rule.json
- cypress/fixtures/plugins/security-analytics-dashboards-plugin/sample_document.json
- cypress/fixtures/plugins/security-analytics-dashboards-plugin/sample_windows_index_settings.json
- cypress/integration/plugins/security-analytics-dashboards-plugin/2_rules.spec.js
- cypress/integration/plugins/security-analytics-dashboards-plugin/3_alerts.spec.js
Updated security analytics cypress tests.
https://github.com/opensearch-project/security-analytics-dashboards-plugin/issues/1004
Tests pass locally when using the `opensearchstaging/opensearch:2.14.0` docker image with security enabled.
> Updated security analytics cypress tests.

- cypress/utils/commands.js
Only jump to home when security enabled.
#1290 
> feat: only flesh tenant when security enabled

- cypress/integration/plugins/security-analytics-dashboards-plugin/3_alerts.spec.js
Fixed security analytics cypress test.
https://github.com/opensearch-project/security-analytics-dashboards-plugin/issues/1004
> Fixed security analytics cypress test.

- cypress/integration/plugins/alerting-dashboards-plugin/cluster_metrics_monitor_spec.js
- cypress/integration/plugins/alerting-dashboards-plugin/composite_level_monitor_spec.js
Fixed v2.13 alerting tests.
Tested against a v2.13 domain with security enabled.
> Fixed v2.13 alerting tests.

- cypress/integration/plugins/alerting-dashboards-plugin/cluster_metrics_monitor_spec.js
Fixed v2.7 alerting tests.
Tested against a 2.7 domain with security enabled.
> Fixed v2.7 alerting tests.

- cypress/integration/plugins/security-analytics-dashboards-plugin/3_alerts.spec.js
This PR updates the tests required for the changes made in PR https://github.com/opensearch-project/security-analytics-dashboards-plugin/pull/1010
> [Security Analytics] Updated alerts spec for the security analytics PR 1010

- .github/workflows/ml-commons-release-e2e-workflow.yml
- cypress/integration/plugins/ml-commons-dashboards/1_overview_spec.js
- cypress/integration/plugins/ml-commons-dashboards/2_overview_remote_model_spec.js
- cypress/integration/plugins/ml-commons-dashboards/mds_1_overview_spec.js
- cypress/integration/plugins/ml-commons-dashboards/mds_2_overview_remote_model_spec.js
- cypress/utils/plugins/ml-commons-dashboards/shared/overview.js
Separate ml-commons-dashboards MDS cases to files with mds_ prefix, this PR includes below changes:
1. Move shared test cases to `utils/shared` folder
2. Execute shared test cases in non MDS test files
3. Select data source before each MDS test case
> Separate ml-commons-dashboards MDS cases

- .github/workflows/cypress-workflow-bundle-snapshot-based.yml
- cypress.json
- cypress/fixtures/dashboard/opensearch_dashboards/telemetry/uiReport.json
- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/telemetry/server.spec.js
- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/telemetry/ui_metric.spec.js
- package.json
Signed-off-by: Suchit Sahoo <suchsah@amazon.com>
(cherry picked from commit b2e2498789e016cceea4be39fcca539399a20a22)
> [Manual Backport 2.x]Add functional test for UI Metric (#1267)

- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/workspace-plugin/workspace_create.spec.js
- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/workspace-plugin/workspace_dropdown_menu.spec.js
- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/workspace-plugin/workspace_overview.spec.js
- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/workspace-plugin/workspace_update.spec.js
The same as #1369 , but backport to main.
1. Remove workspace description invalid test cases
2. Remove workspace features test cases
3. Add workspace use case test cases
> Update workspace description usecase tests

- cypress/integration/plugins/security-analytics-dashboards-plugin/3_alerts.spec.js
Update tests for [PR 1014](https://github.com/opensearch-project/security-analytics-dashboards-plugin/pull/1014/) in Security Analytics Dashboards
https://github.com/opensearch-project/security-analytics-dashboards-plugin/issues/1043
> [Security Analytics][2.15] Update tests for PR 1014 in Security Analytics Dashboards

- cypress/integration/plugins/dashboards-assistant/mds_chatbot_default_data_source_change.js
- cypress/utils/dashboards/datasource-management-dashboards-plugin/commands.js
1. Add title parameter to `cy.createDataSourceNoAuth`
2. Add chatbot test cases for default data source change
> Add chatbot test cases for default data source change

- .github/CODEOWNERS
- MAINTAINERS.md
> Add Emma as maintainer

- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/datasource-management-plugin/5_version_decouple.spec.js
Add functional test for version decouple
- [ Y] Commits are signed per the DCO using --signoff
> Add functional test for version decouple

- .github/workflows/cypress-workflow-bundle-snapshot-based-ci-groups.yml
- .github/workflows/cypress-workflow-bundle-snapshot-based-windows.yml
- .github/workflows/cypress-workflow-bundle-snapshot-based.yml
- .github/workflows/release-e2e-workflow-template.yml
- cypress.json
- cypress/support/index.js
Reverts opensearch-project/opensearch-dashboards-functional-test#1408
Closes https://github.com/opensearch-project/OpenSearch/issues/14442
> Revert "feat: freeze browser version to 112"

- cypress/integration/plugins/index-management-dashboards-plugin/aliases.js
- cypress/integration/plugins/index-management-dashboards-plugin/transforms_spec.js
There are flaky tests due to version conflict exception.
> Additional wait will allow the page to render

- cypress/integration/plugins/security-dashboards-plugin/sanity_tests.spec.js
- cypress/integration/plugins/security/permissions_spec.js
- cypress/utils/plugins/security/commands.js
- cypress/utils/plugins/security/constants.js
- package-lock.json
> Update api path in main after service account removal

- cypress/integration/plugins/security-analytics-dashboards-plugin/1_detectors.spec.js
> [2.15][Security analytics] Updated detector tests

- cypress/integration/plugins/security-analytics-dashboards-plugin/1_detectors.spec.js
- cypress/integration/plugins/security-analytics-dashboards-plugin/3_alerts.spec.js
Fix tests for security analytics 2.16
https://github.com/opensearch-project/security-analytics-dashboards-plugin/issues/1085
> [2.16] Fix tests for security analytics 2.16

- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/data_explorer/discover_advanced_settings.spec.js
Fix Test failures in Discover Advanced Settings.
> Fix Discover Advanced Setting Bug

- cypress/integration/plugins/gantt-chart-dashboards/gantt_ui.spec.js
https://github.com/opensearch-project/dashboards-visualizations/issues/379#issuecomment-2266175221
https://github.com/opensearch-project/dashboards-visualizations/issues/379
> remove command time out for gantt chart

- cypress/integration/plugins/notifications-dashboards/1_email_senders_and_groups.spec.js
* Add missing semicolon to fix lint issues
> add missing ; to tests to fix lint issues

- cypress/fixtures/plugins/notifications-dashboards/test_chime_channel.json
- cypress/fixtures/plugins/notifications-dashboards/test_slack_channel.json
- cypress/integration/plugins/notifications-dashboards/1_email_senders_and_groups.spec.js
- cypress/integration/plugins/notifications-dashboards/2_channels.spec.js
This PR fixes the notification channel tests
Fixes the CI failure here -> https://github.com/opensearch-project/opensearch-dashboards-functional-test/actions/runs/10252949383/job/28365198539
> Fix channel tests

- cypress/integration/plugins/anomaly-detection-dashboards-plugin/vis_augmenter/associate_detector_spec.js
Updates cypress integration test for Anomaly Detection plugin due to [UI changes from Look&Feel PR](https://github.com/opensearch-project/anomaly-detection-dashboards-plugin/pull/836).
> Update Anomaly Detection Plugin test

- cypress/integration/plugins/reports-dashboards/02-edit.spec.js
passing the tod for the failed repoting integ tests
> Fix for reporting integ test failures

- cypress/integration/plugins/anomaly-detection-dashboards-plugin/vis_augmenter/associate_detector_spec.js
Manual backport for 2.x for #1518 
> [Backport 2.x] Update Anomaly Detection Plugin test (#1518)

- cypress/integration/plugins/security/audit_log_spec.js
Updates security dashboards plugin cypress tests due to look&feel UI changes
> Update Security Dashboards testing due to look&feel changes

- cypress/integration/plugins/security/audit_log_spec.js
> [Backport 2.x] Update Security Dashboards testing due to look&feel changes

- cypress/integration/plugins/observability-dashboards/4_panels.spec.js
> Fix observability panel test base paths on 2.13

- cypress/integration/plugins/observability-dashboards/4_panels.spec.js
> Fix observability panel test base paths on 2.15

- .github/actions/start-opensearch/action.yml
- .github/workflows/cypress-workflow-bundle-snapshot-based-ci-groups.yml
- .github/workflows/release-e2e-workflow-template-windows.yml
- .github/workflows/release-e2e-workflow-template.yml
Backport e445a5207cd74a215d4a326766b1fc0f65455537 from #1384
> [Backport 2.x]Bump JDK to 21 (#1384)

- cypress/integration/plugins/security-analytics-dashboards-plugin/1_detectors.spec.js
> [2.17][Security Analytics] Updated detectors cypress tests

- cypress/integration/plugins/dashboards-flow-framework/create_workflow_spec.js
- Updated flow framework dashboards test spec to match changes in https://github.com/opensearch-project/dashboards-flow-framework/pull/432
> Update flow framework dashboards test spec

- cypress/integration/plugins/alerting-dashboards-plugin/bucket_level_monitor_spec.js
- cypress/integration/plugins/alerting-dashboards-plugin/cluster_metrics_monitor_spec.js
- cypress/integration/plugins/alerting-dashboards-plugin/composite_level_monitor_spec.js
- cypress/integration/plugins/alerting-dashboards-plugin/document_level_monitor_spec.js
- cypress/integration/plugins/alerting-dashboards-plugin/query_level_monitor_spec.js
Updated alerting dashboard cypress tests due to fit and finish changes.
> [Alerting dashboards] Update alerting dashboard tests due to fit and finish changes

- cypress/integration/plugins/observability-dashboards/2_trace_analytics_services.spec.js
- cypress/utils/plugins/observability-dashboards/constants.js
See lint error in 2.x and 2.18 and submit this fix. Main has no such issue.
na
> fix lint issue in 2.x

- cypress/utils/plugins/dashboards-flow-framework/constants.js
Update flow framework visible plugin name. Related to https://github.com/opensearch-project/dashboards-flow-framework/pull/472
> Update flow framework visible plugin name

- cypress/fixtures/dashboard/opensearch_dashboards/workspace/workspaceTestRole.json
- cypress/fixtures/dashboard/opensearch_dashboards/workspace/workspaceTestRoleMapping.json
- cypress/fixtures/dashboard/opensearch_dashboards/workspace/workspaceTestUser.json
- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/workspace-plugin/mds_workspace_initial.spec.js
- cypress/utils/plugins/security-dashboards-plugin/commands.js
Add workspace initial page functional tests
> Add workspace initial page functional tests

- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/data_explorer/discover_advanced_settings.spec.js
Merge after https://github.com/opensearch-project/OpenSearch-Dashboards/pull/8782
na
> modify the refresh data button test to use test-data-subj

- .github/CODEOWNERS
- MAINTAINERS.md
- Yubo’s PR: https://github.com/opensearch-project/opensearch-dashboards-functional-test/pulls?q=is%3Apr+author%3Ayubonluo+is%3Aclosed 
- Issues and PRs Hailong has commented:  https://github.com/opensearch-project/opensearch-dashboards-functional-test/issues?q=commenter%3Ayubonluo
> Add yubonluo as maintainer

- .github/workflows/cypress-workflow-bundle-snapshot-based.yml
- cypress/utils/dashboards/workspace-plugin/test-cases/mds_workspace_import_sample_data_to.cases.js
1. Improve workspace import sample data tests, no need to install / uninstall sample data many times to reduce the possibility of test flaky. 
2. Fix upload artifact failed due to duplicate artifact name 
> Improve workspace import sample data tests

- cypress/integration/plugins/observability-dashboards/2_trace_analytics_services.spec.js
- cypress/integration/plugins/observability-dashboards/3_trace_analytics_traces.spec.js
- cypress/integration/plugins/observability-dashboards/6_notebooks.spec.js
- cypress/utils/plugins/observability-dashboards/constants.js
> [Backport 2.x] Update observability dashboards tests (#1669)

- cypress/fixtures/plugins/dashboards-flow-framework/semantic_search/import_workflow.json
- cypress/integration/plugins/dashboards-flow-framework/create_workflow_spec.js
A large amount of wording changes from the tech writer & doc teams have come in. Updating tests accordingly.
> Update Flow Framework Tests cont.

- package-lock.json
- package.json
> [CVE-2024-21538] Bump cross-spawn to 7.0.5

- cypress/fixtures/plugins/dashboards-flow-framework/semantic_search/import_workflow.json
- cypress/fixtures/plugins/dashboards-flow-framework/semantic_search/simulate_pipeline_response.json
- cypress/integration/plugins/dashboards-flow-framework/create_workflow_spec.js
- cypress/utils/plugins/dashboards-flow-framework/commands.js
Update FF test to integrate with new API calls
> Update FF test to integrate with new API calls

- cypress/integration/plugins/index-management-dashboards-plugin/rollups_spec.js
- cypress/integration/plugins/index-management-dashboards-plugin/transforms_spec.js
Fixing couple of flaky tests in rollups and transforms
Resolves https://github.com/opensearch-project/index-management-dashboards-plugin/issues/1177
> Fixing couple of flaky tests in rollups and transforms

- .github/workflows/release-e2e-workflow-template.yml
- cypress/integration/plugins/reports-dashboards/04-download.spec.js
Updated flakey test in reporting Homepage
> [Bug]Updated flakey test from reporting homepage

- cypress/integration/plugins/observability-dashboards/4_panels.spec.js
Fixes flaky adding visualization and deleting panels tests in panels 2.9
```
Running:  plugins/observability-dashboards/4_panels.spec.js                               (5 of 9)
Creating visualizations
✓ Create first visualization in event analytics (22594ms)
Testing panels table
✓ Creates a panel and redirects to the panel (8889ms)
✓ Duplicates a panel
✓ Deletes panels (9102ms)
Testing a panel
✓ Move to test panel
✓ Change date filter of the panel
Clean up all test data
✓ Deletes test panel
7 passing (55s)
(Results)
│ Tests:        7                                                                                │
│ Passing:      7 …
```
> Update flaky observability panels tests

- cypress/integration/plugins/reports-dashboards/02-edit.spec.js
Updated edit spec test in 2.11(match gitfarm)
> [Bug]Fix flakey Reports test in 2.11

- cypress/integration/plugins/reports-dashboards/02-edit.spec.js
- cypress/integration/plugins/reports-dashboards/04-download.spec.js
Updated edit spec and download test in 2.5(match gitfarm)
> [Bug]Fix flakey reports test in 2.3

- cypress/integration/plugins/query-workbench-dashboards/ui.spec.js
- cypress/utils/plugins/query-workbench-dashboards/constants.js
Fix flakey workbench test in 1.3
> [Bug]Fix flakey Query-workbench test in 1.3

- .github/workflows/cypress-workflow-bundle-snapshot-based.yml
- .github/workflows/cypress-workflow-plugins-bundle-snapshot-based.yml
- .github/workflows/cypress-workflow-vanilla-snapshot-based.yml
- cypress/integration/plugins/observability-dashboards/3_trace_analytics_traces.spec.js
- cypress/integration/plugins/observability-dashboards/4_panels.spec.js
- cypress/integration/plugins/observability-dashboards/5_event_analytics.spec.js
- cypress/utils/plugins/observability-dashboards/constants.js
Fix for different time zones in trace analytics
Fix panels buttons names
Fix event analytics data-test-subj names
> Fix flaky observability tests in 1.3

- .github/workflows/cypress-workflow-bundle-snapshot-based.yml
- .github/workflows/cypress-workflow-plugins-bundle-snapshot-based.yml
- .github/workflows/cypress-workflow-vanilla-snapshot-based.yml
- cypress/integration/plugins/gantt-chart-dashboards/gantt_ui.spec.js
Add fix for different timezones in time format test
> Add gantt chart fix for different timezones in 1.1

- cypress/integration/plugins/query-workbench-dashboards/ui.spec.js
- cypress/utils/plugins/query-workbench-dashboards/constants.js
Fix flakey workbench test in 1.2
Dump test data ✓ Indexes test data for SQL and PPL
Test PPL UI ✓ Confirm results are empty (8630ms) ✓ Test Run button (8270ms) ✓ Test Clear button (7220ms) ✓ Test full screen view (6070ms)
Test SQL UI ✓ Confirm results are empty ✓ Test Run button and field search (5963ms) ✓ Test Translate button (9252ms) ✓ Test Clear button ✓ Test full screen view
Test and verify SQL downloads ✓ Download and verify JSON ✓ Download and verify JDBC ✓ Download and verify CSV ✓ Download and verify Text
Test table display ✓ Test GROUP BY (8497ms) ✓ Test GROUP BY with aliases and scalar function (6477ms) ✓ Test GROUP BY and HAVING (7192ms) ✓ Test ORDER BY (8722ms) ✓ Test JOIN (10001ms) ✓ Test nested fields display (9448ms)
20 passing (2m)
(Results) …
> [Bug]Fix flakey Query-workbench test in 1.2

- .github/workflows/release-e2e-workflow-template.yml
- .github/workflows/reports-release-e2e-workflow.yml
- cypress/integration/plugins/observability-dashboards/3_trace_analytics_traces.spec.js
- cypress/integration/plugins/observability-dashboards/6_notebooks.spec.js
- cypress/integration/plugins/reports-dashboards/02-edit.spec.js
Fix flakey cypress test for observability and reports
> [Bug ]2.19 insights fix for observability and reports

- .github/workflows/release-e2e-workflow-template.yml
- .github/workflows/release-signoff-chrome.yml
- .github/workflows/release-signoff-chromium-ad-only.yml
- .github/workflows/release-signoff-chromium-ism-only.yml
- .github/workflows/release-signoff-chromium-tests-in-memory-0.yml
- .github/workflows/release-signoff-chromium-tests-in-memory-10.yml
- .github/workflows/release-signoff-chromium-tests-in-memory-20.yml
- .github/workflows/release-signoff-chromium-tests-in-memory-5.yml
- .github/workflows/release-signoff-chromium.yml
- .github/workflows/release-signoff-electron.yml
- .github/workflows/release-signoff-firefox.yml
- cypress/utils/plugins/query-workbench-dashboards/constants.js
test: remove JSON download test
* Remove test following feature deprecation in upstream repository
* Maintains compatibility with current upstream functionality
also, updates `action/cache` from v1 to v4
https://github.com/opensearch-project/sql/issues/3248
https://github.com/opensearch-project/dashboards-query-workbench/pull/460
> QueryWorkbench remove download json test

- package-lock.json
- package.json
- remote_cypress_manifest.json
> feat: bump version to beta1

- cypress/integration/plugins/security-analytics-dashboards-plugin/1_detectors.spec.js
- cypress/integration/plugins/security-analytics-dashboards-plugin/2_rules.spec.js
- cypress/integration/plugins/security-analytics-dashboards-plugin/3_alerts.spec.js
Fix cypress tests, remove unnecessary button click. Added commits to fix flakiness in tests.
> [Security Analytics] Fix cypress tests

- .github/workflows/assistant-release-e2e-workflow.yml
- cypress/fixtures/plugins/alerting-dashboards-plugin/sample_query_level_monitor_for_alert_summary.json
- cypress/fixtures/plugins/dashboards-assistant/data2summary-response.json
- cypress/fixtures/plugins/dashboards-assistant/flow-templates/data2summary.json
- cypress/fixtures/plugins/dashboards-assistant/flow-templates/suggest-ad.json
- cypress/fixtures/plugins/dashboards-assistant/flow-templates/summary.json
- cypress/fixtures/plugins/dashboards-assistant/flow-templates/summary_with_log_pattern.json
- cypress/fixtures/plugins/dashboards-assistant/suggest-ad-response.json
- cypress/fixtures/plugins/dashboards-assistant/summary-response.json
- cypress/fixtures/plugins/dashboards-assistant/summary-with-log-pattern-response.json
- cypress/integration/plugins/dashboards-assistant/mds_query_enhancements_alert_summary_spec.js
- cypress/integration/plugins/dashboards-assistant/mds_query_enhancements_data2summary_spec.js
- cypress/integration/plugins/dashboards-assistant/mds_query_enhancements_suggest_anomaly_detector_spec.js
- cypress/support/assistant-dummy-llm.js
- cypress/utils/plugins/alerting-dashboards-plugin/commands.js
- cypress/utils/plugins/dashboards-assistant/commands.js
- cypress/utils/plugins/dashboards-assistant/constants.js
This PR add integration tests for Assistant, mainly includes changes below:
- Add integration tests for alert summary in alert page.
- Add integration tests for discovery summary in discovery page.
- Add integration tests for anonymous detect in discovery page.
> Feat: add tests for alert summary, discovery summary and anonymous detect

- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/vis_type_table/data.spec.js
- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/vis_type_table/embed.spec.js
Disable flaky tests in Ci group 2 for Discover. 
> Disable tests

- cypress/integration/plugins/dashboards-assistant/conversation_chatbot_save_to_notebook_spec.js
- cypress/integration/plugins/dashboards-assistant/mds_chatbot_agent_framework_spec.js
- cypress/integration/plugins/dashboards-assistant/mds_chatbot_conversation_history_spec.js
- cypress/integration/plugins/dashboards-assistant/mds_chatbot_default_data_source_change.js
- cypress/integration/plugins/dashboards-assistant/mds_chatbot_feedback_spec.js
- cypress/integration/plugins/dashboards-assistant/mds_chatbot_interaction_trace_spec.js
- cypress/integration/plugins/dashboards-assistant/mds_chatbot_sidecar_spec.js
- cypress/integration/plugins/dashboards-assistant/mds_query_enhancements_chatbot_spec.js
- cypress/utils/plugins/dashboards-assistant/commands.js
1. Add chatbot test cases for query_enhancements task
2. Refactor chatbot open command
3. Start new conversation before chatbot test start
> Add chatbot test cases for query_enhancements task

- cypress/integration/plugins/query-insights-dashboards/3_configurations.cy.js
fix query insights cypress tests for 3.2
> fix query insights cypress tests for 3.2

- cypress/integration/plugins/anomaly-detection-dashboards-plugin/forecaster_list_spec.js
forecaster_list_spec test  was getting stuck on the "Select your tenant" dialog in the frontend, preventing execution from proceeding. This change ensures the dialog is dismissed so the test can continue without manual intervention.
Testing done:
* ran forecaster_list_spec test in 3.2 cluster with all plugins.
https://github.com/opensearch-project/anomaly-detection-dashboards-plugin/issues/1072
> Fix test hang on tenant selection dialog

- cypress/utils/plugins/query-insights-dashboards/commands.js
Updated the window size from 1m -> 1h
> updated the window size -QueryInsights Dashboards

- package-lock.json
- package.json
Bump form-data version to 2.5.5
> Bump form-data version to 2.5.5
