- integtest.sh
During infra team's Jenkins test, we noticed some issues to fix. Thus this PR is to add npm install and executable for integ test shell
1. add package install. (Plugins use osd bootstrap)
2. `chmod 775 integtest.sh`
https://github.com/opensearch-project/opensearch-dashboards-functional-test/issues/3
- [Check with Infra Jenkins ] Commits are signed per the DCO using --signoff 
> add npm install and executable for integ test shell

- .gitignore
- CONTRIBUTING.md
- cypress.json
- cypress/integration/security-disabled/dashboard_filtering_spec.js
- cypress/integration/security-enabled/login-page-spec.js
- package-lock.json
- package.json
Signed-off-by: Tengda He <tengh@amazon.com>
- adding a separate cypress environment variable for OpenSearch endpoint url, the baseUrl will be reserved for OpenSearchDashboard endpoint. This way allows easy config for API call to OpenSearch endpoint.
- move the username and password parameter to  cypress environment variable
- cypress environment variable supports CLI overrides as well.
- all existing test suites passed for remote endpoint in staging environment
- fgac tests passed
- non fgac tests passed
#8 
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/m …
> add config to support remote endpoint test

- integtest.sh
Add the support for `version` argument.
During https://github.com/opensearch-project/opensearch-build/issues/604 I noticed the integ test command failed with `Invalid option: -v`
```
Executing "/tmp/tmpz2xuwc_d/functionalTestDashboards/integtest.sh -b localhost -p 5601 -s false -v 1.2.0" in /tmp/tmpz2xuwc_d/functionalTestDashboards
2021-11-30 02:14:32 INFO     status,  is 1
2021-11-30 02:14:32 INFO     stdout is Invalid option: -v
```
After checking this repo, I realized that this option is not available. 
Resolves https://github.com/opensearch-project/opensearch-dashboards-functional-test/issues/39
The previous `-v` error is gone.
```
./integtest.sh -b localhost -p 5601 -s false -v 1.2.0
./integtest.sh: line 80: npm: command not found
``` …
> add version argument to integ test shell

- integtest.sh
Changes cypress run command in `integtest.sh` to run core and plugin tests in a single run to persist all test artifacts (videos, screenshots, etc.).
See [cypress documentation](https://docs.cypress.io/guides/guides/command-line#cypress-run-spec-lt-spec-gt) for details on running multiple files and/or globs.
Closes #68 
> Run core and plugin tests in single run command in integtest.sh

- CONTRIBUTING.md
- cypress/integration/core-opensearch-dashboards/vanilla-opensearch-dashboards/dashboard_filtering_spec.js
Signed-off-by: Tao Liu <liutaoaz@amazon.com>
This PR is skipping one flaky test, and update the CONTRIBUTING.md.
resolves https://github.com/opensearch-project/opensearch-dashboards-functional-test/issues/90
According to the Cypress: https://github.com/cypress-io/cypress/issues/3092
Cypress considers a pending test to be any of the following:
```
it.skip(), context.skip, etc
it('some test') (no callback)
```
```
dashboard filtering
✓ Buffer test for …
```
> skip flaky test and update document

- .github/workflows/cypress-workflow-bundle-snapshot-based.yml
- .github/workflows/cypress-workflow-plugins-bundle-snapshot-based.yml
- .github/workflows/cypress-workflow-vanilla-snapshot-based.yml
- package.json
Upgrade the main branch to 1.3.0 and use the `latest` url since it is ready. https://github.com/opensearch-project/opensearch-build/issues/1492
> upgrade to 1.3.0 and use latest url

- cypress/integration/plugins/anomaly-detection-dashboards-plugin/detector_list_spec.js
Signed-off-by: Amit Galitzky <amgalitz@amazon.com>
Changed `data-test-subj` tag for 'Redirect to create detector' test to correct ID tag that is used in AD dashboards-plugin
> Fixed ID tag name in AD test

- integtest.sh
Make the shell script calling integ test by using the same way as Github workflow to avoid discrepancy.
https://github.com/opensearch-project/opensearch-build/issues/1709
> unify the sh and Github workflow

- cypress/integration/plugins/reports-dashboards/01-create.spec.js
- cypress/integration/plugins/reports-dashboards/02-edit.spec.js
- cypress/integration/plugins/reports-dashboards/03-details.spec.js
- cypress/integration/plugins/reports-dashboards/04-download.spec.js
- package.json
See error to run the tests from infra.
```
$ env TZ=America/Los_Angeles cypress run --browser chrome --headless --env SECURITY_ENABLED=false --spec 'cypress/integration/core-opensearch-dashboards/opensearch-dashboards/*.js,cypress/integration/plugins/*/*'
Can't run because you've entered an invalid browser name.
Browser: 'chrome' was not found on your system or is not supported by Cypress.
```
Thus remove browser parameter.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certifi …
> use default browser

- package.json
The output is in garbled status. https://ci.opensearch.org/ci/dbc/integ-test-opensearch-dashboards/1.3.0/1484/linux/x64/test-results/b94f426463b24046a2ed33c5be290508/integ-test/functionalTestDashboards/without-security/test-results/stdout.txt
> disable color in output

- .github/workflows/release-signoff.yml
- package.json
This can serve as a sign off. Use browser chrome. Run every 3 hours. The host has x64 per https://github.com/actions/virtual-environments/blob/releases/ubuntu20/20220306/images/linux/Ubuntu2004-Readme.md There is no official support for ARM64 yet.
Resolves https://github.com/opensearch-project/opensearch-dashboards-functional-test/issues/118
> Add workflow to run release tests every 3 hours

- cypress/integration/plugins/reports-dashboards/01-create.spec.js
- cypress/integration/plugins/reports-dashboards/02-edit.spec.js
- cypress/integration/plugins/reports-dashboards/03-details.spec.js
- cypress/integration/plugins/reports-dashboards/04-download.spec.js
This reverts commit 376ac6483748402df4c987c75d981989bc87f41e.
Will explore more options to handle the crashed default browser.
> Revert "use default browser (#112)"

- integtest.sh
The build repo has switched to use the latest Docker image with Chromium support. https://github.com/opensearch-project/opensearch-build/pull/1748 We expect to see more stable test results since the existing Electron browser installed along with Cypress 5.6.0 is quite old.
> use browser chromium in integtest.sh

- .github/workflows/release-signoff-chromium-tests-in-memory-0.yml
- .github/workflows/release-signoff-chromium-tests-in-memory-10.yml
- .github/workflows/release-signoff-chromium-tests-in-memory-20.yml
- .github/workflows/release-signoff-chromium-tests-in-memory-5.yml
- cypress.json
- package.json
Tune parameter `numTestsKeptInMemory` https://docs.cypress.io/guides/references/configuration#Global By default is is 50
> add a workflow for tuning numTestsKeptInMemory 

- integtest.sh
- package.json
At the beginning of each release, the Dashboards plugins are added gradually. Thus allow the FTRepo to support such so that tests won't run all the plugins. Once one plugin is supported in the bundle, we can uncomment the corresponding test files.
https://github.com/opensearch-project/opensearch-dashboards-functional-test/issues/84
> allow phased addition of dashboards plugins

- .github/workflows/cypress-workflow-bundle-snapshot-based.yml
- .github/workflows/cypress-workflow-plugins-bundle-snapshot-based.yml
- .github/workflows/cypress-workflow-vanilla-snapshot-based.yml
Update the PR workflows to use chromium since we have already done such for infra integration. https://github.com/opensearch-project/opensearch-dashboards-functional-test/blob/main/integtest.sh#L96
> switch to use chromium browser

- cypress/integration/plugins/anomaly-detection-dashboards-plugin/create_detector_spec.js
Signed-off-by: Tyler Ohlsen <ohltyler@amazon.com>
The logic to delete the detector in the create detector workflow test would occasionally fail, due to trying to delete it too soon after creation. Because of this failure to delete, it had cascading effects on other tests, where they were expecting empty pages / no detectors, but instead was displaying this test detector which failed to delete.
This fixes the logic in the deletion by utilizing the UI instead of making a direct API call, which provides the benefits of (1) more closely replicating how a user would interact with the plugin and (2) provides more time for the detector to be created, as the modal to delete won't be functional until the detector has been created and is available to delete.
Testing:
- Debugged failures by …
> Clean up flaky failures in AD plugin

- cypress/integration/plugins/anomaly-detection-dashboards-plugin/detector_list_spec.js
Signed-off-by: Tyler Ohlsen <ohltyler@amazon.com>
Fixes one AD test that is still occasionally failing on both Cypress 5.x and 9.x. Checks that the detector list page is in a certain state before trying to click a button.
Testing done:
- Replicated failure: [link](https://github.com/ohltyler/anomaly-detection-dashboards-plugin-1/runs/5669200562?check_suite_focus=true)
- Made the change and updated AD CI to temporarily point to the change. The change is reflected starting on attempt 3 onwards (running multiple times to confirm no failures): [link](https://github.com/ohltyler/anomaly-detection-dashboards-plugin-1/actions/runs/2036306657)
Closes #147 
For more information on …
> Fix one AD test

- cypress/integration/plugins/reports-dashboards/04-download.spec.js
Signed-off-by: Joshua Li <joshuali925@gmail.com>
By default this test clicks on the first report, which is CSV and its model disappears instantly. Changing it to PDF to give more time for cypress to capture the downloading model. 
> Fix reports downloading flaky test

- integtest.sh
- test_finder.sh
Within the CI, we know the location of the build manifest of
the OpenSearch Dashboards that got scaled up in prep for the
execution of these tests within this repo.
We can use that knowledge to determine the set of tests that
are valid against the distribution that this repo is being
executed on.
https://github.com/opensearch-project/opensearch-dashboards-functional-test/issues/153
> [CI] build TEST_FILES for CI based on build manifest

- integtest.sh
- test_finder.sh
* [CI] build TEST_FILES for CI based on build manifest
Within the CI, we know the location of the build manifest of
the OpenSearch Dashboards that got scaled up in prep for the
execution of these tests within this repo.
We can use that knowledge to determine the set of tests that
are valid against the distribution that this repo is being
executed on.
(cherry picked from commit 23bb48ba59f6d03fc8623a45c14c6c887a13d2d9)
> [1.3][CI] build TEST_FILES for CI based on build manifest

- cypress/integration/plugins/security/audit_log_spec.js
- cypress/integration/plugins/security/get_started_spec.js
- cypress/integration/plugins/security/permissions_spec.js
For some reason, message returned in the security plugins tests
differ from architectures. On x64 it will return as valid JSON
but on ARM64 it will be an object. The closest attempt to keeping
the message check was by stringifying them but on ARM64 it would
add the double quote.
So it fails to parse we can just ensure the resp code is correct.
Also switch to visible to not exist seems like we define this across
the repo as well.
n/a
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#devel …
> [Security] fix tests that failed on ARM64

- CONTRIBUTING.md
Update CONTRIBUTING to include information for maintainers
on how to backport.
Issue resolved:
https://github.com/opensearch-project/opensearch-dashboards-functional-test/issues/160
https://github.com/opensearch-project/opensearch-dashboards-functional-test/issues/160
> [Docs] backport port process

- cypress/integration/plugins/index-management-dashboards-plugin/indices_spec.js
When all the suites run together. There might an issue
with cleanup and the expected amount of rows on this page.
Which would cause this test to be "flakey"
Here we ensure the largest amount of rows are shown because
within the test run the expected data stream index might be
on the next row if there are 20 plus indices.
n/a
> [ISM] show all rows for test

- cypress/integration/plugins/anomaly-detection-dashboards-plugin/historical_analysis_spec.js
Signed-off-by: Amit Galitzky <amgalitz@amazon.com>
Changed AD historical test to get HTML element by `title` instead of `aria-label`. The aria-label doesn't show up in the markdown since 2.0 bump. I will continue investigating adding aria-label back but for now tests shouldn't need to fail cause of this. Also added a refresh click before this test is executed to decrease flakiness.
> Fix AD historical analysis integ test

- cypress/integration/plugins/alerting-dashboards-plugin/bucket_level_monitor_spec.js
- cypress/integration/plugins/alerting-dashboards-plugin/query_level_monitor_spec.js
Copy-paste with changes that were committed from the alerting
dashboards plugin.
Source PR:
https://github.com/opensearch-project/alerting-dashboards-plugin/pull/214
n/a
> [2.0][Alerting] temp disable cypress flakey test

- integtest.sh
- test_finder.sh
* [CI] build TEST_FILES for CI based on build manifest
Within the CI, we know the location of the build manifest of
the OpenSearch Dashboards that got scaled up in prep for the
execution of these tests within this repo.
We can use that knowledge to determine the set of tests that
are valid against the distribution that this repo is being
executed on.
(cherry picked from commit 23bb48ba59f6d03fc8623a45c14c6c887a13d2d9)
> [1.x][CI] build TEST_FILES for CI based on build manifest

- cypress/integration/plugins/security/permissions_spec.js
Resolves a flaky test that was failing due to multiple clicks in a very short time.
https://amzn-aws.slack.com/archives/C02006YQC9X/p1650390694582289?thread_ts=1650389923.574799&cid=C02006YQC9X
> Updates flaky test to not fail in security dashboards

- cypress/integration/plugins/anomaly-detection-dashboards-plugin/historical_analysis_spec.js
For our cypress, the date picker might not have closed when refreshing
so then I just checked if the button exists if not then it's because
the date picker is closed. If it's open it will then the previous time
window will exist.
Issue:
n/a
n/a
> [AD] fix historical analysis

- CONTRIBUTING.md
* Update the test folder when security is enabled in [CONTRIBUTING](https://github.com/opensearch-project/opensearch-dashboards-functional-test/blob/main/CONTRIBUTING.md)
https://github.com/opensearch-project/opensearch-dashboards-functional-test/issues/100
1. Run 
```yarn cypress run --spec "cypress/integration/core-opensearch-dashboards/opensearch-dashboards/*.js" --config "baseUrl=https://search-conjwang-1-2-2y5dpzuupluvzhttbx6xwjpcsi.us-east-1.es.amazonaws.com/_dashboards" --env "openSearchUrl=https://search-conjwang-1-2-2y5dpzuupluvzhttbx6xwjpcsi.us-east-1.es.amazonaws.com,SECURITY_ENABLED=true,username=admin,password=Test2022*,ENDPOINT_WITH_PROXY=true"```
2. See all tests passed
```
Spec                                              Tests …
```
> update security test folder in CONTRIBUTING

- .github/workflows/notifications-release-e2e-workflow.yml
- cypress/integration/plugins/notifications-dashboards/channels.spec.js
- cypress/integration/plugins/notifications-dashboards/dashboard.spec.js
- cypress/integration/plugins/notifications-dashboards/email_groups.spec.js
- cypress/utils/constants.js
- cypress/utils/plugins/notifications-dashboards/constants.js
- test_finder.sh
New plugin. Just copy and pasted the existing tests from this repo:
https://github.com/opensearch-project/notifications/tree/main/dashboards-notifications
I am not positive about the flakiness this introduces but will handle it in subsequent tests.
https://github.com/opensearch-project/opensearch-dashboards-functional-test/issues/184
> [Notifications] onboard sanity tests for notifications plugin

- .github/workflows/notifications-release-e2e-workflow.yml
Address the failed Notification workflow https://github.com/opensearch-project/opensearch-dashboards-functional-test/pull/206#issuecomment-1113895074
> remove unnecessary version in Notification workflow

- package-lock.json
- package.json
Signed-off-by: Peter Zhu <zhujiaxi@amazon.com>
Lock Cypress version to 9.5.4 so it will not use other versions:
```
2022-04-30 05:03:10 INFO     [FAILED] Cypress failed to start.
[FAILED] 
[FAILED] This may be due to a missing library or dependency. https://on.cypress.io/required-dependencies
[FAILED] 
[FAILED] Please refer to the error below for more details.
[FAILED] 
[FAILED] ----------
[FAILED] 
[FAILED] /usr/share/opensearch/.cache/Cypress/9.6.0/Cypress/Cypress: /usr/share/opensearch/.cache/Cypress/9.6.0/Cypress/Cypress: cannot execute binary file
[FAILED] 
[FAILED] ----------
[FAILED] 
[FAILED] Platform: linux-x64 (RHEL - )
[FAILED] Cypress Version: 9.6.0
error Command failed with exit code 1.
```
Our docker image only have 9.5.4 version compiled and installed.
On 2022/04/25 Cypress …
> Lock Cypress version to 9.5.4 so it will not use other versions

- package.json
* Add `postinstall` script in package.json, so that people don't need to manually install hooks
https://github.com/opensearch-project/opensearch-dashboards-functional-test/pull/201#discussion_r860252631
1. Delete `node_modules`
2. Run `npm install`, should see that`husky install`runs and text `husky - Git hooks installed`
```
> husky install
husky - Git hooks installed
```
3. Commit code change, should see precommit hook runs
```
ubuntu@ip-172-31-55-176:~/github/opensearch-dashboards-functional-test$ git commit -s -m "add postinstall script in package.json"
yarn run v1.22.10
$ eslint . --ext .js
Done in 2.49s.
```
For more …
> add postinstall script in package.json

- cypress/integration/plugins/anomaly-detection-dashboards-plugin/create_detector_spec.js
- cypress/utils/plugins/anomaly-detection-dashboards-plugin/helpers.js
Signed-off-by: Amit Galitzky <amgalitz@amazon.com>
Added wait time to solve AD test looking for something in the next page after button click.
> AD test failure fix 

- .github/workflows/cypress-workflow-bundle-snapshot-based.yml
- .github/workflows/release-e2e-workflow-template.yml
- cypress/utils/commands.js
- cypress/utils/plugins/anomaly-detection-dashboards-plugin/helpers.js
- cypress/utils/plugins/observability-dashboards/constants.js
- package-lock.json
- package.json
Bumping to version 2.0.0, fix linter problem.
Also, preventing the test runner from navigating to a new
page when security plugin is enabled. The reason why is
because depending on how long the test takes to run, there
is an API call to refresh the permissions that take a little
bit longer than what tests are expecting. So if the test runner
makes the call to switch tenants but navigates to a new page
before that call is finished another call might run into a
permissions error. This ensures that if that call is made
then the test runner waits before navigating to the destination.
https://github.com/opensearch-project/opensearch-dashboards-functional-test/issues/231
By submitting this pull request, I confirm that my contribution is made …
> Wait for tenancy call if security enabled and bump version

- site/index.html
- site/js/dashboard.js
- site/styles.css
Basic HTML and JS to explore known tests.
There can be improvements made but just initial stuff and hardcoded.
values to help plugin developers find their results.
If this is merged, and `Sites` are enabled for this repo then it should be accessible
via `https://opensearch-project.github.io/opensearch-dashboards-functional-test/site/`
https://github.com/opensearch-project/opensearch-dashboards-functional-test/issues/217
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certific …
> [Site] add test explore page

- cypress/integration/plugins/reports-dashboards/01-create.spec.js
- cypress/integration/plugins/reports-dashboards/02-edit.spec.js
- cypress/utils/commands.js
- cypress/utils/plugins/reports-dashboards/constants.js
- test_finder.sh
Incorrectly merged the verification where I check if option to wait
for switching of tenant worked. Switched it back to the expected
scenario if the test passed the command it will wait.
Also, the test finder for manifest was missing the manifest path so
added that while also ensuring the minify OSD tests weren't ran
when verifying the distribution because those will fail as expected.
n/a
> [Improvement] fix issue with tenancy and test finder

- MAINTAINERS.md
Update maintainer list to reflect the actual situation. Will follow the standard [process](https://github.com/opensearch-project/.github/blob/main/MAINTAINERS.md#becoming-a-maintainer) for future new maintainers.
Resolves https://github.com/opensearch-project/opensearch-dashboards-functional-test/issues/212
> update maintainer list

- cypress/integration/plugins/observability-dashboards/7_app_analytics.spec.js
Origin: https://github.com/opensearch-project/observability/commit/9d16389d9f719cf07b24bd93f359731ec621305f
https://github.com/opensearch-project/opensearch-build/issues/1818
> [Observability] update test for common delete modal

- .github/workflows/custom-import-map-dashboards-release-e2e-workflow.yml
- cypress/integration/plugins/custom-import-map-dashboards/import_vector_map_tab.spec.js
- test_finder.sh
Signed-off-by: Shivam Dhar <dhshivam@amazon.com>
Video without security ->
https://user-images.githubusercontent.com/9303427/182781721-cdf45498-eae4-48cf-9771-8f3b2e7291d8.mp4
Test results -
`yarn cypress:run-without-security --spec "cypress/integration/plugins/customImportMap/*.js"`
```
yarn run v1.22.18
$ env TZ=America/Los_Angeles NO_COLOR=1 cypress run --headless --env SECURITY_ENABLED=false --spec 'cypress/integration/plugins/customImportMap/*.js'
The experimentalNetworkStubbing configuration option was removed in Cypress version 6.0.0.
It is no longer necessary for using cy.intercept(). You can safely remove this option from your config.
Couldn't determine Mocha version
====================================================================================================
(Run …
```
> Adds basic integration test for customImportMap plugin

- cypress/integration/plugins/anomaly-detection-dashboards-plugin/create_detector_spec.js
- cypress/integration/plugins/anomaly-detection-dashboards-plugin/detector_configuration_spec.js
- cypress/integration/plugins/anomaly-detection-dashboards-plugin/historical_analysis_spec.js
- cypress/integration/plugins/anomaly-detection-dashboards-plugin/overview_spec.js
- cypress/integration/plugins/anomaly-detection-dashboards-plugin/real_time_results_spec.js
Signed-off-by: Jackie Han <jkhanjob@gmail.com>
AD Dashboard Feature Attribution feature introduced a change of swapping Feature Breakdown tab and Anomaly occurrences tab, therefore, adjusting tests correspondingly.
AD Dashboard failed tests
> Adjust ad-dashboard historical page test and fix flaky tests

- cypress/integration/plugins/anomaly-detection-dashboards-plugin/create_detector_spec.js
Signed-off-by: Tyler Ohlsen <ohltyler@amazon.com>
Cleans up 2 things in the AD create detector test:
1. Renames the sample index to `sample-ad-index` so it gets deleted in the `cy.deleteAllIndices()` cmd. Before, this was left as a dangling index because the pattern in [deleteAllIndices](https://github.com/opensearch-project/opensearch-dashboards-functional-test/blob/main/cypress/utils/commands.js#L92) didn't catch the old name of `ad-cypress-test-index`.
2. Adds 5s wait time after creation before attempting to delete. This was flaky and would occasionally fail when trying to delete too fast, before the creation and detector start requests had finished executing.
For more …
> Clean up create detector AD test

- site/index.html
- site/js/dashboard.js
Enables access to easily see the import custom maps. Also added more query strings to easily set and build a link to the test results page to be easily copied and shared.
n/a
> [Site] add import maps button and more query string

- cypress/integration/plugins/anomaly-detection-dashboards-plugin/create_detector_spec.js
Signed-off-by: Tyler Ohlsen <ohltyler@amazon.com>
Changes the AD request to `form:false` in the request parameters, when loading in some sample data. From the [cypress documentation](https://docs.cypress.io/api/commands/request#Arguments), setting to `form:true` means the body should be url-encoded, and overwrites the `Content-Type` header to `application/x-www-form-urlencoded`. What we actually want is `application/json` which we have already specified in the request itself. By setting to `false` it removes any confusion and cleans up the code to make it run as expected.
Note that the previous code still worked, but was changing the request header to `Content-Type: application/x-www-form-urlencoded` under the hood which was causing confusion and could lead to certain bugs, especially if …
> Change form:false for AD request

- cypress.json
```experimentalNetworkStubbing``` option was removed and made the default behaviour from version 6.0.0.
Ref: https://docs.cypress.io/guides/references/changelog#6-0-0
Resolves #309 
> Remove experimentalNetworkStubbing Option from Cypress.json

- .eslintrc.json
- cypress/integration/common/dashboard_sample_data_spec.js
- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/dashboard_sanity_test_spec.js
- cypress/integration/core-opensearch-dashboards/vanilla-opensearch-dashboards/dashboard_filtering_spec.js
- cypress/integration/plugins/notifications-dashboards/1_email_senders_and_groups.spec.js
- cypress/integration/plugins/notifications-dashboards/2_channels.spec.js
- cypress/integration/plugins/query-workbench-dashboards/ui.spec.js
- cypress/plugins/index.js
- cypress/support/index.js
- cypress/utils/plugins/notifications-dashboards/constants.js
- cypress/utils/plugins/query-workbench-dashboards/constants.js
- index.js
- package-lock.json
- package.json
- site/js/dashboard.js
Adds two eslint rules and fixes issues caught by the linter
- eslint-plugin-header: To enforce license header
- eslint-plugin-import: To error for import issues
Fixes linting issues
> Adds linter rules for license and import. Fixes lint issues

- .github/release.yml
Signed-off-by: Zilong Xia <zilongx@amazon.com>
* Add `release.yml` file to `Functional Test` project to enable the auto generation of release note.
* Testing Release created in fork repo as 
Resolves https://github.com/opensearch-project/opensearch-dashboards-functional-test/issues/346
> Add release.yml file to enable release note automation

- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/datasource-management-plugin/2_datasource_table.spec.js
Signed-off-by: Yibo Wang <yibow@amazon.com>
Based on the feedback from Multi-datasource UX sign-off meeting, there are small changes in UX. This PR is to update functional test of Datasource listing page to make sure all test cases pass. Most of the UX changes do not effect the function test cases except the datasource table column header change. 
(Note: Functional test of datasource create page does not need to be updated.)
https://user-images.githubusercontent.com/109543558/197059732-7ceccdd6-8348-46f1-af2e-1ab9fd03ac14.mp4
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/2615
For more information on following Developer Certificate of Origin and signing …
> [MD] Update DS list page FT based on UX change

- package-lock.json
Signed-off-by: Zilong Xia <zilongx@amazon.com>
* Resolves the `minimatch ReDoS vulnerability` by bumping `minimatch` up to `3.1.2` 
* Retrieve vulnerability details by running `npm audit`
```
88665a51c9b6:opensearch-dashboards-functional-test zilongx$ npm i --package-lock-only
added 327 packages and audited 327 packages in 0.896s
found 4 high severity vulnerabilities
run `npm audit fix` to fix them, or `npm audit` for details
88665a51c9b6:opensearch-dashboards-functional-test zilongx$ npm audit
=== npm audit security report ===                        
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ minimatch ReDoS vulnerability                                │
├───────────────┼──────────────────────────────────────────────────────────────┤ …
```
> [Security] Bump minimatch to 3.1.2 to fix the ReDoS vulnerability

- cypress/integration/plugins/security-dashboards-plugin/aggregation_view.js
Signed-off-by: Ryan Liang <jiallian@amazon.com>
Add test case for filter of aggregation view feature
* Resolve https://github.com/opensearch-project/security-dashboards-plugin/pull/1169 
* Resolve https://github.com/opensearch-project/OpenSearch-Dashboards/pull/2656
https://user-images.githubusercontent.com/109499885/199626218-b1365ca5-b9d7-4a9f-bebd-f8c6e237b4a7.mp4
> Add test cases for filter of aggregation view feature

- cypress.json
Enables visbuilder tests by default
> Enables visbuilder tests by default

- .github/workflows/cypress-workflow-bundle-snapshot-based-windows.yml
- .github/workflows/release-e2e-workflow-template-windows.yml
- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/dashboard_sanity_test_spec.js
- test_finder.sh
Add Windows workflow on cypress bundle build.
https://github.com/opensearch-project/opensearch-dashboards-functional-test/issues/359
https://github.com/opensearch-project/opensearch-build/issues/2649
> Add Windows workflow on cypress bundle build

- .github/workflows/cypress-workflow-bundle-snapshot-based-windows.yml
- .github/workflows/cypress-workflow-bundle-snapshot-based.yml
- .github/workflows/release-e2e-workflow-template-windows.yml
- .github/workflows/release-e2e-workflow-template.yml
- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/dashboard_sanity_test_spec.js
Signed-off-by: Peter Zhu <zhujiaxi@amazon.com>
Add support for linux e2e template to run no-sec tests
https://github.com/opensearch-project/opensearch-build/issues/2649
> Add support for linux e2e template to run no-sec tests

- .github/workflows/cypress-workflow-bundle-snapshot-based-windows.yml
- .github/workflows/cypress-workflow-bundle-snapshot-based.yml
- .github/workflows/release-e2e-workflow-template-windows.yml
- .github/workflows/release-e2e-workflow-template.yml
- test_finder.sh
Signed-off-by: Peter Zhu <zhujiaxi@amazon.com>
Signed-off-by: Peter Zhu <zhujiaxi@amazon.com>
[Backport 2.x] Add support for linux e2e template to run no-sec tests
#367
#383
> [Backport 2.x] Add support for linux e2e template to run no-sec tests (#367 #383)

- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/vis_builder/vis_types/table.spec.js
This PR adds basic functional tests for table vis rendered in vis builder. These functional tests are only focusing on how
vis builder renders table vis given diff metric and bucket. The functions related specific to table vis will be tested in table visualization to avoid any duplications.
https://github.com/opensearch-project/opensearch-dashboards-functional-test/issues/388
https://user-images.githubusercontent.com/79961084/200977570-94733e88-8f97-43f4-ad41-dd9ac6f2d632.mov
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-cer …
> [Vis Builder] [Test] Add functional tests for table vis

- MAINTAINERS.md
The maintainers have voted https://github.com/mpabba3003 as maintainer. Also @mpabba3003 agreed to join as maintainer.
> add mpabba3003 to maintainers

- MAINTAINERS.md
The maintainers have voted https://github.com/ashwin-pc as maintainer. Also @ashwin-pc  agreed to join as maintainer.
> add ashwin-pc to maintainers

- MAINTAINERS.md
The maintainers have voted https://github.com/peterzhuamazon as maintainer. Also @peterzhuamazon  agreed to join as maintainer.
> add peterzhuamazon as maintainers

- .github/workflows/alerting-release-e2e-workflow.yml
- .github/workflows/anomaly-detection-release-e2e-workflow.yml
- .github/workflows/custom-import-map-dashboards-release-e2e-workflow.yml
- .github/workflows/cypress-workflow-bundle-snapshot-based-windows.yml
- .github/workflows/cypress-workflow-bundle-snapshot-based.yml
- .github/workflows/gantt-chart-release-e2e-workflow.yml
- .github/workflows/index-management-release-e2e-workflow.yml
- .github/workflows/lint_checker.yml
- .github/workflows/notifications-release-e2e-workflow.yml
- .github/workflows/observability-release-e2e-workflow.yml
- .github/workflows/query-workbench-release-e2e-workflow.yml
- .github/workflows/reports-release-e2e-workflow.yml
- .github/workflows/search-relevance-release-e2e-workflow.yml
- .github/workflows/security-release-e2e-workflow.yml
@ohltyler noticed that workflows are not running for branches e.g 2.x. Thus we are changing to match all branches.
> update Github action trigger to be all branches

- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/datasource-management-plugin/1_create_datasource.spec.js
Currently there are two submit type buttons in data source which cause cypress fails to find and click. In this PR, I switch to use `data-test-subj` to uniquely identify the btn.
https://github.com/opensearch-project/opensearch-dashboards-functional-test/issues/439
* After fix
https://user-images.githubusercontent.com/79961084/211672342-ab8624c5-dfae-453e-96d6-d488dceb5343.mov
> [BUG] Fix multiple submit bug

- cypress/integration/plugins/observability-dashboards/0_before.spec.js
- cypress/integration/plugins/observability-dashboards/2_trace_analytics_services.spec.js
- cypress/integration/plugins/observability-dashboards/4_panels.spec.js
- cypress/integration/plugins/observability-dashboards/5_event_analytics.spec.js
- cypress/integration/plugins/observability-dashboards/7_app_analytics.spec.js
- cypress/utils/plugins/observability-dashboards/constants.js
Removed/updated observability tests.
#289 
> Update observability tests

- site/index.html
- site/js/dashboard.js
- site/styles.css
Update pages site with new test links for the latest release of 2.5.0.
Added windows option to platforms.
Moved test number from advanced settings to regular settings because test number is no longer static for each test run.
Update default values.
n/a
> [Site][2.5] update test result explorer site with new test links

- cypress/integration/plugins/gantt-chart-dashboards/gantt_ui.spec.js
- cypress/integration/plugins/observability-dashboards/0_before.spec.js
- cypress/integration/plugins/query-workbench-dashboards/ui.spec.js
Signed-off-by: Shenoy Pratik <sgguruda@amazon.com>
The functional tests for gantt-chart, observability and workbench were over-riding the default cypress form field in api requests to OpenSearch. This was leading to error as form field override is only necessary when this header is set to `x-www-form-urlencoded` 
Solution: Removed the form field as it is not required in the tests.
#313 
#310  
#311  
#312  
> Removing form field in gantt-chart, observability and workbench

- cypress/utils/plugins/observability-dashboards/constants.js
Signed-off-by: Kavitha Conjeevaram Mohan <mohakavi@amazon.com>
The `mapping_url` provided for observability seems to be pointing towards the old repository. So changing it to point towards correct URL.
> Fix Observability mapping url

- cypress/integration/plugins/gantt-chart-dashboards/gantt_ui.spec.js
Signed-off-by: Shenoy Pratik <sgguruda@amazon.com>
For branches 1.3 and prior, FTR uses cypress 5 which doesn't have default shipped moment.js rather it has moment.js. 
This PR replaces the day.js library usage for older versions. 
```
Error: Webpack Compilation Error
./cypress/integration/plugins/gantt-chart-dashboards/gantt_ui.spec.js
Module not found: Error: Can't resolve 'dayjs' in '/docker/cypress/integration/plugins/gantt-chart-dashboards'
resolve 'dayjs' in '/docker/cypress/integration/plugins/gantt-chart-dashboards'
```
Related to https://github.com/cypress-io/cypress/issues/8714
For more information on following Developer Certificate of Origin and signing off your …
> Replacing day.js with moment.js -> 1.3 and older 

- cypress/integration/plugins/query-workbench-dashboards/ui.spec.js
Signed-off-by: Joshua Li <joshuali925@gmail.com>
cypress issue 14566
full window button sometimes cannot be found
> Fix workbench find full window button

- .github/workflows/release-e2e-workflow-template.yml
- cypress/integration/plugins/index-management-dashboards-plugin/aliases.js
* feat: add function test for IM plugin on v2.5
Signed-off-by: suzhou <suzhou@amazon.com>
* feat: remove snapshot_spec
Signed-off-by: suzhou <suzhou@amazon.com>
* feat: remove duplicate commands
Signed-off-by: suzhou <suzhou@amazon.com>
* feat: remove duplicate commands
Signed-off-by: suzhou <suzhou@amazon.com>
* feat: remove some useless test case
Signed-off-by: suzhou <suzhou@amazon.com>
* feat: remove snapshot_spec and duplicate commands (#450)
* feat: remove snapshot spec and update commands
Signed-off-by: suzhou <suzhou@amazon.com>
* feat: make actions to run again
Signed-off-by: suzhou <suzhou@amazon.com>
* feat: change to addIndexAlias & removeIndexAlias
Signed-off-by: suzhou <suzhou@amazon.com>
Signed-off-by: suzhou <suzhou@amazon.com>
* feat: lint
Signed-off-by: suzhou …
> [Backport 2.5] feat: add function test for IM plugin (#443) 

- .github/workflows/release-e2e-workflow-template.yml
- cypress/integration/plugins/index-management-dashboards-plugin/aliases.js
* feat: add function test for IM plugin on v2.5
Signed-off-by: suzhou <suzhou@amazon.com>
* feat: remove snapshot_spec
Signed-off-by: suzhou <suzhou@amazon.com>
* feat: remove duplicate commands
Signed-off-by: suzhou <suzhou@amazon.com>
* feat: remove duplicate commands
Signed-off-by: suzhou <suzhou@amazon.com>
* feat: remove some useless test case
Signed-off-by: suzhou <suzhou@amazon.com>
* feat: remove snapshot_spec and duplicate commands (#450)
* feat: remove snapshot spec and update commands
Signed-off-by: suzhou <suzhou@amazon.com>
* feat: make actions to run again
Signed-off-by: suzhou <suzhou@amazon.com>
* feat: change to addIndexAlias & removeIndexAlias
Signed-off-by: suzhou <suzhou@amazon.com>
Signed-off-by: suzhou <suzhou@amazon.com>
* feat: lint
Signed-off-by: suzhou …
> [Backport 2.x] feat: add function test for IM plugin (#443)

- cypress/integration/plugins/ml-commons-dashboards/overview_spec.js
- cypress/utils/plugins/ml-commons-dashboards/commands.js
The ml-commons-dashboards functional test will failed if there is no ml nodes in opensearch cluster. The error will like this:
Disable only_run_on_ml_node to avoid this error in model upload phase.
I removed all the ml node in my local and re-run this functional test. It works fine.
> Disable only_run_on_ml_node to avoid model upload error

- .github/workflows/ml-commons-release-e2e-workflow.yml
- cypress/integration/plugins/ml-commons-dashboards/overview_spec.js
- cypress/support/index.js
- cypress/utils/constants.js
- cypress/utils/plugins/ml-commons-dashboards/commands.js
- cypress/utils/plugins/ml-commons-dashboards/constants.js
- test_finder.sh
Signed-off-by: Lin Wang <wonglam@amazon.com>
(cherry picked from commit 94d1f8047821b522b07aed5b0844f2068a835983)
Manual backport #538 to 2.x
> [BACKPORT 2.x] Add functional test for ml-commons-dashboards overview page (#538)

- cypress/integration/plugins/security/permissions_spec.js
Fix the flaky test case for security permission
*Resolve https://github.com/opensearch-project/opensearch-dashboards-functional-test/issues/284
> Fix the flaky test case for security permission

- .github/workflows/release-e2e-workflow-template-windows.yml
- .github/workflows/release-e2e-workflow-template.yml
Issue is caused by security plugins not available in plugins folder. Need to add a check before set plugins.security.disabled to the config file.
https://github.com/opensearch-project/opensearch-dashboards-functional-test/issues/473
> [BUG]fix unknown setting [plugins.security.disabled] issue

- cypress/integration/plugins/ml-commons-dashboards/overview_spec.js
- cypress/utils/plugins/ml-commons-dashboards/commands.js
Disable native memory circuit breaker to avoid model upload error like [this](https://github.com/opensearch-project/opensearch-dashboards-functional-test/actions/runs/4258333832/jobs/7413535943#step:15:108).
The same code run successfully when cherry-pick to 2.6 branch,  the result link is: https://github.com/wanglam/opensearch-dashboards-functional-test/actions/runs/4261055837/jobs/7414926387#step:15:108
> Disable native memory circuit breaker before model upload

- cypress/integration/plugins/search-relevance-dashboards/1_query_compare.spec.js
Improving Cypress tests for `Dashboards Search Relevance` to defend against uncleared sample data. If sample data from other tests are not cleared after they finished, the `search-relevance` tests fail, as during `2.6.0` release.
Test run with sample data that is not cleared:
Test run after adding `cy.deleteAllIndices()`:
[#159](https://github.com/opensearch-project/dashboards-search-relevance/issues/159)
> [ENHANCEMENT] Improving Dashboards Search Relevance Tests

- cypress/integration/plugins/observability-dashboards/6_notebooks.spec.js
We don't support notebooks context menu reports below 2.5 or 2.6 after chromium removal, users will need to create a report in the reporting plugin explicitly for notebooks. This PR removes the old tests in 1.3 branch. They should be removed by #530 but it contained other changes and couldn't be backported
https://github.com/opensearch-project/opensearch-dashboards-functional-test/issues/585
> Remove context menu download reporting tests in notebooks

- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/vis_builder/dashboard.spec.js
- cypress/utils/dashboards/vis_builder/commands.js
- cypress/utils/dashboards/vis_builder/constants.js
https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3715 changes how the visualization types change. We no longer show the confirm modal. This updates the tests to reflect that. This will fail in CI until the other change is merged
> [VisBuilder] Fixes tests for vis type persistence change

- cypress/integration/plugins/ml-commons-dashboards/overview_spec.js
- cypress/utils/plugins/ml-commons-dashboards/constants.js
There is an UI bug in ml-commons-dashboards 2.6.0, here is [the issue](https://github.com/opensearch-project/ml-commons-dashboards/issues/145). This bug will be fixed in ml-commons-dashboards 2.7.0. This PR add a new case to cover  this bug to ensure the same issue won't be raised anymore.
I've run the new functional test in my local, here is the results:
N/A
> add test case for model deployment details loading indicator

- cypress/utils/dashboards/commands.js
OUI 1.1makes a change that removes the need to click the start date button after clicking show dates. doing so will actually close the popup and fail the test. The change fixes that.
> Chore: updates datepicker command for change in oui 1.1

- cypress/integration/plugins/custom-import-map-dashboards/add_saved_object.spec.js
Add Cypress test to validate adding default saved map for the sample flights dataset in the dashboards-maps plugin.
> Add Cypress test for Default Saved Map

- integtest.sh
- test_finder.sh
SignedOff by : divyaasm@amazon.com
A new optional argument OPTION [-o ] is added to integtest.sh
Fix to the issue [#3316](https://github.com/opensearch-project/opensearch-build/pull/3316)
Call to ./integtest.sh from integ-workflow can now use additional `-o default` parameter when -t is passed which executes the tests individually instead of altogether. This is optional and does not change the behaviour if -o is not passed.
> Add an optional parameter -o to integtest.sh 

- cypress/integration/plugins/security-dashboards-plugin/inaccessible_tenancy_features.js
We are adding a new cypress test to check if Dashboards tenancy features are disabled when `opensearch_security.multitenancy.enabled` is disabled in the `opensearchdashboard.yaml` file.
Cypress tests for PR: https://github.com/opensearch-project/security-dashboards-plugin/pull/1419
- [✅ ] Commits are signed per the DCO using --signoff
Testing video: 
https://user-images.githubusercontent.com/99718513/236475661-31cd89cf-6121-422a-b71f-cc0a7236b1be.mp4
Testing by running cypress test from Security-Dashboards plugin;
https://github.com/opensearch-project/security-dashboards-plugin/actions/runs/4894295743/jobs/8738346716
For more information on following Developer Certificate of …
> Adding test for opensearch_security.multitenancy.enabled disabled

- integtest.sh
- test_finder.sh
Backport the changes from main branch to 1.3 branch to support the parallel run of OSD integtests. Currently the changes are applied only to 2.x branch. Need to adapt the changes for [1.3.10](https://github.com/opensearch-project/opensearch-build/issues/3331) release 
Changes to the files integtest.sh and test_finder.sh include from :
https://github.com/opensearch-project/opensearch-dashboards-functional-test/pull/234
https://github.com/opensearch-project/opensearch-dashboards-functional-test/pull/236
https://github.com/opensearch-project/opensearch-dashboards-functional-test/pull/367
https://github.com/opensearch-project/opensearch-dashboards-functional-test/pull/644
By submitting this pull request, I confirm that my contribution is made under the …
> Backport changes from main to 1.3 branch related to OSD Integtests

- cypress/fixtures/plugins/security-dashboards-plugin/users/testUser.json
- cypress/integration/plugins/security-dashboards-plugin/aggregation_view.js
Change the testuser password into a strong password in aggregation_view test
* Relate https://github.com/opensearch-project/security-dashboards-plugin/issues/1429
* Relate https://github.com/opensearch-project/security/pull/2557
> Change the testuser password into a strong password in aggregation_view test

- integtest.sh
Allow ftrepo to accept custom browser path running integTest
opensearch-project/opensearch-build#3434
opensearch-project/opensearch-ci#293
> Allow ftrepo to accept custom browser path running integTest

- cypress/integration/plugins/ml-commons-dashboards/overview_spec.js
- cypress/utils/plugins/ml-commons-dashboards/commands.js
- cypress/utils/plugins/ml-commons-dashboards/constants.js
The ml-commons 2.8 will bring model group level access control feature. The new feature will break old model upload process.  This PR enable model register upload by URL and create model group before model upload. Then model can be uploaded and deployed. 
This PR **should be backport to `2.x`** branch and already passed in the local environment.
Test video: https://github.com/opensearch-project/opensearch-dashboards-functional-test/assets/4034161/6044acbe-9be6-48fb-94df-2d3551cd506c
Test screenshot: ![image](https://github.com/opensearch-project/opensearch-dashboards-functional-test/assets/4034161/397d2309-8159-4ed0-a7a6-4d248617a34f)
For more information on following …
> fix: model upload failed with model group level access control

- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/datasource-management-plugin/1_create_datasource.spec.js
- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/datasource-management-plugin/2_datasource_table.spec.js
- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/datasource-management-plugin/3_update_datasource.spec.js
- cypress/utils/dashboards/datasource-management-dashboards-plugin/constants.js
CI should pass once we merge PR: https://github.com/opensearch-project/OpenSearch-Dashboards/pull/4126
locally passed
#665 
> [MD]Update cypress tests for sigV4 & serverless support

- .github/workflows/cypress-workflow-plugins-bundle-snapshot-based.yml
- .github/workflows/release-signoff-chrome.yml
- .github/workflows/release-signoff-chromium-tests-in-memory-0.yml
- .github/workflows/release-signoff-chromium-tests-in-memory-10.yml
- .github/workflows/release-signoff-chromium-tests-in-memory-20.yml
- .github/workflows/release-signoff-chromium-tests-in-memory-5.yml
- .github/workflows/release-signoff-chromium.yml
- .github/workflows/release-signoff-electron.yml
- .github/workflows/release-signoff-firefox.yml
[Backport 1.3] Tweak dir path for osd after untar (#688)
#688
> [Backport 1.3] Tweak dir path for osd after untar (#688)

- cypress/integration/plugins/ml-commons-dashboards/overview_spec.js
- cypress/utils/plugins/ml-commons-dashboards/commands.js
Compatible with register model group failed, try to register model without model_group_id.
Local env test screenshot:
Local env test video:
https://github.com/opensearch-project/opensearch-dashboards-functional-test/assets/4034161/54284502-9a9c-4f3a-9ac8-2e3054e7ae71
This PR should be backport to 2.x and 2.8 branch.
> Enhancement ml-commons model upload compatible with register model group failed

- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/vis_type_table/data.spec.js
- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/vis_type_table/embed.spec.js
- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/vis_type_table/options.spec.js
- package-lock.json
Blocked by:
https://github.com/opensearch-project/opensearch-dashboards-test-library/pull/34
This uses first and last instead of relying of `eq` which seems to be inconsistent per Cypress env headless
n/a
> Use range for filter

- site/index.html
- site/js/dashboard.js
- site/styles.css
For site, previous test results will exist within the FTRepo but since the usage of concurrency for plugin tests, the path to the results is different.
Updating site to be able to handle both situations.
Added a gif how to use this feature.
n/a
> [Site] update results path based on recent updates for concurrency

- site/index.html
- site/js/dashboard.js
- site/styles.css
Add OpenSearch Dashboards test artifact links
N/A
> [Site] add OSD results

- cypress/utils/commands.js
This commit addresses an issue where the deletion of Anomaly Detection (AD) system indices was failing in Cypress tests due to lack of super admin privileges. Instead of attempting to delete the indices as super admin, which isn't feasible in the Cypress environment, we now employ an API-based approach to delete the content of these AD indices.
Testing Performed:
1. Executed all tests in a security-enabled cluster confirming the successful deletion of AD system indices content.
https://github.com/opensearch-project/opensearch-dashboards-functional-test/issues/714 …
> Fix Anomaly Detection System Indices Deletion in Cypress Tests

- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/vis_builder/dashboard.spec.js
Add one line `cy.waitForLoader();` in the vis-builder/dashboard test. 
Previously, after we create a new vis builder from a dashboard, we immediately test if the vis builder exists in that dashboard without letting the dashboard page finish loading.
> [Dashboard De-Angular] Let dashboard finish loading after adding a new vis

- site/index.html
- site/js/dashboard.js
- site/styles.css
(cherry picked from commit aadc599ea6ec4e3e9ff42efa7ea97258023928e0)
> [Manual][Backport 2.x][Site] update results path based on recent updates for concurrency

- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/vis_builder/vis_types/table.spec.js
This PR updates tests, so that it no longer needs to test direction, because the direction logic was moved to the OUI components, instead of custom `visTable__groupInColumns` class that is used currently. Without this, the tests will fail when [the PR that removes `visTable__groupInColumns`](https://github.com/opensearch-project/OpenSearch-Dashboards/pull/4272) will be merged, as this class will no longer exist.
https://github.com/opensearch-project/opensearch-dashboards-functional-test/blob/6823c8202eb8aca8ec1ef1dee41c9e25f65622ab/cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/vis_builder/vis_types/table.spec.js#L60 
Solves https://github.com/opensearch-project/opensearch-dashboards-functional-test/issues/730
By submitting this pull request, I confirm that my …
> [Table Visualizations] Update test

- package.json
Increment the version on the parent branch (2.x) to the next development iteration (2.10) after 2.9 branch cut.
Issues Resolved
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/4486
> Increment version to 2.10 as part of release process

- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/dashboard_sample_data_with_datasource_spec.js
Test sample data list, installation and uninstall with multiple data source enabled on local cluster. 
Verified tests pass locally:
```
Running:  core-opensearch-dashboards/opensearch-dashboards/dashboard_sample_da            (1 of 2)
ta_with_datasource_spec.js 
dashboard local cluster sample data validation
checking home page
✓ checking tutorial_directory display (6575ms)
adding sample data
✓ checking ecommerce dashboards displayed (23503ms)
✓ checking flights dashboards displayed (6671ms)
✓ checking web logs dashboards displayed (6949ms)
checking index patterns
✓ checking ecommerce index patterns are added
✓ checking flights index patterns are added
✓ checking web logs index patterns are added
checking saved objects
✓ checking ecommerce object is saved
✓ checking flights object is saved …
```
> Test sample data with multiple data source enabled on local cluster

- DEVELOPER_GUIDE.md
- package-lock.json
- package.json
1. add tough-cookie & word-wrap fix in overrides.
2. use npm v8 to generate `package-lock.json`(Now our workflows are using NPM v8).
> feat: use "overrides" to install desired version of tough-cookie and word-wrap.

- cypress/utils/commands.js
- cypress/utils/dashboards/commands.js
- cypress/utils/index.d.ts
Different versions of OUI handle the interactions with the SuperDatePicker differently. This change attempts to work around those differences by conditionally performing tasks.
> Improve date selection across versions of OUI

- cypress/fixtures/plugins/notifications-dashboards/test_chime_channel.json
- cypress/fixtures/plugins/notifications-dashboards/test_email_recipient_group.json
- cypress/fixtures/plugins/notifications-dashboards/test_ses_sender.json
- cypress/fixtures/plugins/notifications-dashboards/test_slack_channel.json
- cypress/fixtures/plugins/notifications-dashboards/test_smtp_email_channel.json
- cypress/fixtures/plugins/notifications-dashboards/test_sns_channel.json
- cypress/fixtures/plugins/notifications-dashboards/test_ssl_smtp_sender.json
- cypress/fixtures/plugins/notifications-dashboards/test_tls_smtp_sender.json
- cypress/fixtures/plugins/notifications-dashboards/test_webhook_channel.json
- cypress/integration/plugins/notifications-dashboards/1_email_senders_and_groups.spec.js
- cypress/integration/plugins/notifications-dashboards/2_channels.spec.js
- cypress/support/index.js
- cypress/utils/plugins/notifications-dashboards/commands.js
- cypress/utils/plugins/notifications-dashboards/constants.js
> feat: sync cypress test from notifications-dashboards

- cypress/fixtures/plugins/notifications-dashboards/test_chime_channel.json
- cypress/fixtures/plugins/notifications-dashboards/test_email_recipient_group.json
- cypress/fixtures/plugins/notifications-dashboards/test_ses_sender.json
- cypress/fixtures/plugins/notifications-dashboards/test_slack_channel.json
- cypress/fixtures/plugins/notifications-dashboards/test_smtp_email_channel.json
- cypress/fixtures/plugins/notifications-dashboards/test_sns_channel.json
- cypress/fixtures/plugins/notifications-dashboards/test_ssl_smtp_sender.json
- cypress/fixtures/plugins/notifications-dashboards/test_tls_smtp_sender.json
- cypress/fixtures/plugins/notifications-dashboards/test_webhook_channel.json
- cypress/integration/plugins/notifications-dashboards/1_email_senders_and_groups.spec.js
- cypress/integration/plugins/notifications-dashboards/2_channels.spec.js
- cypress/support/index.js
- cypress/utils/plugins/notifications-dashboards/commands.js
- cypress/utils/plugins/notifications-dashboards/constants.js
* feat: sync cypress test from notifications-dashboards
Signed-off-by: SuZhou-Joe <suzhou@amazon.com>
* feat: rename commands
Signed-off-by: SuZhou-Joe <suzhou@amazon.com>
* feat: update
Signed-off-by: SuZhou-Joe <suzhou@amazon.com>
* feat: add larger wait time
Signed-off-by: SuZhou-Joe <suzhou@amazon.com>
* feat: update
Signed-off-by: SuZhou-Joe <suzhou@amazon.com>
* feat: update
Signed-off-by: SuZhou-Joe <suzhou@amazon.com>
* feat: update
Signed-off-by: SuZhou-Joe <suzhou@amazon.com>
* feat: add refresh before delete all notifications configs
Signed-off-by: SuZhou-Joe <suzhou@amazon.com>
---------
Signed-off-by: SuZhou-Joe <suzhou@amazon.com>
(cherry picked from commit 81f70c37fde7b468915b173b0e81f4a609ecea84) …
> [Backport main] feat: sync cypress test from notifications-dashboards (#776)

- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/vis_builder/vis_types/table.spec.js
- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/vis_type_table/split.spec.js
In https://github.com/opensearch-project/opensearch-dashboards-functional-test/pull/731 the usage of `visTable__groupInColumns` was removed, but one usage was left off https://github.com/opensearch-project/opensearch-dashboards-functional-test/blob/7f8a7d799abe560549759fa440b0184a3238b61b/cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/vis_type_table/split.spec.js#L314. Also, it covers another follow-up cleanup issue https://github.com/opensearch-project/opensearch-dashboards-functional-test/issues/740.
Solves https://github.com/opensearch-project/opensearch-dashboards-functional-test/issues/740
For more information on following Developer Certificate …
> [Table Visualizations] Tests cleanup

- package-lock.json
- package.json
Bump dependency on `opensearch-dashboards-test-library` to use the `main` branch on the repo to get the latest changes all the time.
> Bump dependency on opensearch-dashboards-test-library

- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/vis_builder/vis_types/table.spec.js
In this dashboards [PR](https://github.com/opensearch-project/OpenSearch-Dashboards/pull/4272) we replaced div container with `OuiFlexItem`. So this line:
https://github.com/opensearch-project/opensearch-dashboards-functional-test/blob/7f8a7d799abe560549759fa440b0184a3238b61b/cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/vis_builder/vis_types/table.spec.js#L91
Was causing error, because it matches element with exactly single `visTable__group` class, while after the PR we had additional `euiFlexItem` class. As a result we got undefined. Here is the screenshot of error.
Now after this fix this test suite do pass, here is the screenshot from my local cypress run.
As we can see it does match all 4 elements like it should.
It solves cypress error when trying to …
> [Table Visualizations] Test Update

- cypress/integration/plugins/ml-commons-dashboards/overview_spec.js
- cypress/utils/plugins/ml-commons-dashboards/commands.js
- cypress/utils/plugins/ml-commons-dashboards/constants.js
Add test cases for ml commons remote models.
This PR has been tested in local env, here is the video:
https://github.com/opensearch-project/opensearch-dashboards-functional-test/assets/4034161/3b1faa2c-ae75-46ee-b090-d116d9735a7e
> feat: add test cases for remote models

- cypress/integration/plugins/query-workbench-dashboards/ui.spec.js
based on the API call, response schema changed back to have data in `response.body.data.resp`. `resp` used to be `"resp": "Unable to parse/serialize body",` is fixed for 2.9, please also port this to main
> fix workbench download text and csv schema

- cypress/integration/plugins/gantt-chart-dashboards/gantt_ui.spec.js
Fix gantt-charts test for different timezones
> [Backport 1.2] added fix for gantt-charts test for different timezones

- cypress/integration/plugins/gantt-chart-dashboards/gantt_ui.spec.js
Fix gantt-charts test for different timezones
> [Backport 1.0] added fix for gantt-charts test for different timezones

- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/vis_builder/dashboard.spec.js
Seeing it pass in video replays but occassionally doesn't pass. However, it doesn't pass with security enabled so I'd imagine it could be related to the refreshing of the session.
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/4947
> [Dashboard] Retry visbuilder dashboard test

- cypress/integration/plugins/custom-import-map-dashboards/import_vector_map_tab.spec.js
Update source element in import_vector_map_tab.spec.js to use opensearch_dashboards_sample_data_flights.
> Update source element in import_vector_map_tab.spec.js

- cypress/fixtures/plugins/security-analytics-dashboards-plugin/integration_tests/detector/create_usb_detector_mappings_data.json
- cypress/fixtures/plugins/security-analytics-dashboards-plugin/integration_tests/index/add_windows_index_data.json
- cypress/fixtures/plugins/security-analytics-dashboards-plugin/integration_tests/index/create_windows_settings.json
- cypress/fixtures/plugins/security-analytics-dashboards-plugin/integration_tests/rule/create_windows_usb_rule.json
- cypress/fixtures/plugins/security-analytics-dashboards-plugin/sample_alias_mappings.json
- cypress/fixtures/plugins/security-analytics-dashboards-plugin/sample_document.json
- cypress/fixtures/plugins/security-analytics-dashboards-plugin/sample_field_mappings.json
- cypress/fixtures/plugins/security-analytics-dashboards-plugin/sample_windows_index_settings.json
- cypress/integration/plugins/security-analytics-dashboards-plugin/3_alerts.spec.js
- cypress/utils/plugins/security-analytics-dashboards-plugin/constants.js
Updated index alias mapping for security analytics dashboards plugin tests to comply with the latest backend mappings for correct rule query generation in a detector.
Resolves https://github.com/opensearch-project/security-analytics-dashboards-plugin/issues/690
> [Security analytics 2.10] Update index mappings

- cypress/integration/plugins/security-analytics-dashboards-plugin/3_alerts.spec.js
When checking for acknowledged alerts, since the filter menu is already open, clicking the button closes it. This PR fixes the test to avoid opening the menu twice.
https://github.com/opensearch-project/security-analytics-dashboards-plugin/issues/690
> [Security Analytics 2.10] Avoid clicking filter menu btn twice

- cypress/utils/plugins/security-analytics-dashboards-plugin/commands.js
The check for loaded URL doesn't account for security enabled, removed it since we have other check for the page content to verify the page loaded correctly
https://github.com/opensearch-project/security-analytics-dashboards-plugin/issues/690
> removed check for url since it differs with and without security

- cypress/utils/plugins/security-analytics-dashboards-plugin/commands.js
The check for loaded URL doesn't account for security enabled, removed it since we have other check for the page content to verify the page loaded correctly
https://github.com/opensearch-project/security-analytics-dashboards-plugin/issues/690
> [Security Analytics 2.x] Removed check for url since it differs with and without security

- cypress/integration/plugins/alerting-dashboards-plugin/composite_level_monitor_spec.js
We are seeing flaky behavior when creating composite monitor. The name input element is sometimes not in view which prevents cypress from typing the name. Since this behavior won't happen when a user is creating the monitor it is safe to force the typing in the name element and the monitor selector elements.
> [Alerting 2.10] Override element covered check for name input in Composite monitor creation

- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/vis_builder/dashboard.spec.js
Finds the correct element when loading instead of a regular visualization loader.
Error easier to catch since wait for loader is less flakey.
opensearch-project/OpenSearch-Dashboards#5043
> [Vis builder]  get correct element

- cypress/integration/plugins/alerting-dashboards-plugin/composite_level_monitor_spec.js
When selecting delegate monitors for composite monitor creation, we are typing in the combo box div element which is throwing invalid typing element error. This PR fixes that by selecting the child input element instead.
This change is already part of #866 for 2.x
https://github.com/opensearch-project/alerting-dashboards-plugin/issues/728
> [Alerting 2.10] Use input element for typing when selecting delegate monitor

- cypress/integration/plugins/index-management-dashboards-plugin/indices_spec.js
During one of the tests for indices, we create an index with name `reindex_opensearch_dashboards_sample_data_ecommerce` that is superstring for the sample index `opensearch_dashboards_sample_data_ecommerce`. This new index is supposed to get deleted but sometimes it might not get deleted due to failure in backend and after that if some other test looks for the sample index and tries to select that index from a combo box, it faces collision and might end up not selecting any index. This PR renames the new index to avoid this situation.
Fixes flaky test in Index Management Dashboards - https://github.com/opensearch-project/index-management-dashboards-plugin/issues/880
For more …
> [Index-mgmt 2.10] Renamed index to avoid collision for other tests

- cypress/integration/plugins/alerting-dashboards-plugin/composite_level_monitor_spec.js
After updating composite monitor added some wait time before checking if update was successful
https://github.com/opensearch-project/alerting-dashboards-plugin/issues/732
> [Alerting 2.10] Wait before checking update status for composite monitor

- cypress/integration/plugins/custom-import-map-dashboards/add_saved_object.spec.js
- cypress/integration/plugins/custom-import-map-dashboards/documentsLayer.spec.js
Ignore the flaky test on customImportMaps when security enabled
> Ignore flaky test on customImportMaps when security enabled

- cypress/integration/plugins/custom-import-map-dashboards/opensearchMapLayer.spec.js
Ignore the flaky test of opensearchMapLayer when security enabled
https://github.com/opensearch-project/opensearch-dashboards-functional-test/issues/883
> Ignore the flaky test of opensearchMapLayer when security enabled

- cypress/integration/plugins/alerting-dashboards-plugin/composite_level_monitor_spec.js
Excluding flaky tests for composite monitors
https://github.com/opensearch-project/alerting-dashboards-plugin/issues/737
> [Alerting 2.10] Excluding flaky tests

- cypress/integration/plugins/reports-dashboards/04-download.spec.js
Skip the failing reporting test for 2.10 release
> Skip failing test for reporting

- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/vis_type_table/embed.spec.js
Skipping test that fails occassional
https://build.ci.opensearch.org/blue/organizations/jenkins/integ-test-opensearch-dashboards/detail/integ-test-opensearch-dashboards/4162/pipeline
Will follow-up in a fast-follow to re-add:
https://github.com/opensearch-project/opensearch-dashboards-functional-test/issues/768
> [2.10] core skip with filter for embed spec on security

- cypress/integration/plugins/observability-dashboards/4_panels.spec.js
- cypress/integration/plugins/observability-dashboards/6_notebooks.spec.js
Latest RC for 2.10 release has seen 2 flaky tests in Observability plugin
Skips below flaky tests:
* 6_notebooks.spec.js/Testing paragraphs -- Duplicates paragraphs
* 4_panels.spec.js/Testing panels table -- Deletes panels
> Skipping flaky tests for panels and notebooks in Observability

- cypress/integration/plugins/alerting-dashboards-plugin/composite_level_monitor_spec.js
We are seeing flaky behavior when creating composite monitor. The name input element is sometimes not in view which prevents cypress from typing the name. Since this behavior won't happen when a user is creating the monitor it is safe to force the typing in the name element and the monitor selector elements.
> [Alerting 2.x] Override element covered check for name input in Composite monitor creation

- cypress/integration/common/dashboard_sample_data_spec.js
In 2.11, we will get rid of angular dependency and legacy discover. The change cypress test to use data explorer.
> Change from legacy discover to data explorer

- cypress/integration/plugins/index-management-dashboards-plugin/indices_spec.js
During one of the tests for indices, we create an index with name `reindex_opensearch_dashboards_sample_data_ecommerce` that is superstring for the sample index `opensearch_dashboards_sample_data_ecommerce`. This new index is supposed to get deleted but sometimes it might not get deleted due to failure in backend and after that if some other test looks for the sample index and tries to select that index from a combo box, it faces collision and might end up not selecting any index. This PR renames the new index to avoid this situation.
Manual backport for 2.10 in #873 
Fixes flaky test in Index Management Dashboards - https://github.com/opensearch-project/index-management-dashboards-plugin/issues/880
By submitting this pull request, I confirm that my contribution is made under the terms of …
> [Index-mgmt 2.x] Renamed index to avoid collision for other tests

- cypress/integration/plugins/query-workbench-dashboards/ui.spec.js
dashboards query workbench removed Euititle
Need to backport to 2.11
> Workbench updates to remove title checks

- DEVELOPER_GUIDE.md
These commands were not working:
` yarn cypress run-without-security --spec "cypress/integration/core-opensearch-dashboards/vanilla-opensearch-dashboards/*.js"`
`yarn cypress run-with-security --spec "cypress/integration/core-opensearch-dashboards/opensearch-dashboards/*.js"`
now changed to:
` yarn cypress:run-without-security --spec "cypress/integration/core-opensearch-dashboards/vanilla-opensearch-dashboards/*.js"`
`yarn cypress:run-with-security --spec "cypress/integration/core-opensearch-dashboards/opensearch-dashboards/*.js"`
Issue #907
- [ ☑️] Commits are signed per the DCO using --signoff
For more information on following Developer Certificate of Origin and signing off …
> [bug] update installation commands in DEVELOPER_GUIDE.md

- cypress/integration/plugins/observability-dashboards/5_event_analytics.spec.js
Fixes flaky test for saved visualization in event analytics
> Update Observability event analytics visualization test

- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/data_explorer/shared_links.spec.js
Fix share link of save search for 2.x branch.
Because of https://github.com/opensearch-project/OpenSearch-Dashboards/pull/5095, the URL parsing is handled differently on main branch and 2.x branch. Therefore, this cypress test on 2.x branch needs to be modified.
> Fix share link for 2.x branch

- cypress/integration/plugins/custom-import-map-dashboards/documentsLayer.spec.js
After selecting a color from color palette, it takes time for the palette to disappear and it could cause two palette to be visible at the same time which could cause an error like `Your subject contained 2 elements.`
```
Opening Cypress...
[376:1025/064054.202674:ERROR:gpu_init.cc(453)] Passthrough is not supported, GL is swiftshader, ANGLE is 
================================================================================
(Run Starting)
│ Cypress:        9.5.4                                                                          │
│ Browser:        Chromium 112 (headless)                                                        │
│ Node Version:   v16.14.2 …
```
> Add wait time after selecting a color

- cypress/integration/plugins/observability-dashboards/5_event_analytics.spec.js
- cypress/integration/plugins/observability-dashboards/6_notebooks.spec.js
https://github.com/opensearch-project/opensearch-dashboards-functional-test/pull/948
Fix observability event analytics and notebook failing tests.
```
Adding sample visualization
✓ Add sample observability data (10158ms)
Testing notebooks table
✓ Creates a notebook and redirects to the notebook (6125ms)
✓ Duplicates and renames a notebook (17050ms)
✓ Deletes notebooks (14073ms)
Testing paragraphs
✓ Goes into a notebook and creates paragraphs (15351ms)
✓ Renders markdown
✓ Shows output message (7307ms)
✓ Duplicates paragraphs (6804ms)
✓ Adds a dashboards visualization paragraph (15066ms)
✓ Adds a SQL query paragraph (17729ms)
✓ Adds a PPL query paragraph (18266ms)
✓ Runs all paragraphs (11655ms)
✓ Deletes paragraphs (13078ms)
✓ Cleans up test notebooks (10435ms)
clean up all test data
✓ …
```
> Fix observability event analytics and notebook failing tests

- cypress/integration/plugins/alerting-dashboards-plugin/monitors_dashboard_spec.js
Refactored alerting test, and added wait logic to reduce flakiness.
The edited test passes locally.
> Refactored alerting test, and added wait logic to reduce flakiness.

- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/data_explorer/aaa_before.spec.js
- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/data_explorer/date_nanos.spec.js
- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/data_explorer/date_nanos_mixed.spec.js
- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/data_explorer/discover.spec.js
- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/data_explorer/discover_histogram.spec.js
- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/data_explorer/doc_navigation.spec.js
- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/data_explorer/doc_table.spec.js
- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/data_explorer/errors.spec.js
- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/data_explorer/field_data.spec.js
- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/data_explorer/field_visualize.spec.js
- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/data_explorer/filter_editor.spec.js
- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/data_explorer/index_pattern_with_encoded_id.spec.js
- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/data_explorer/index_pattern_without_field.spec.js
- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/data_explorer/inspector.spec.js
- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/data_explorer/large_string.spec.js
- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/data_explorer/saved_queries.spec.js
- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/data_explorer/shared_links.spec.js
- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/data_explorer/sidebar.spec.js
- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/data_explorer/source_filter.spec.js
- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/data_explorer/zzz_after.spec.js
- cypress/utils/commands.js
> [Tests] Set default tenancy to global for data explorer tests

- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/data_explorer/discover.spec.js
- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/data_explorer/doc_navigation.spec.js
Because of https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5495, we decide to skip the failed tests.
> Skip flaky data explorer tests 

- .github/workflows/remote-cypress-workflow.yml
- poll_remote_workflow.sh
- remoteCypress.sh
Issue details - https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5392
POC - https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5526
Adds a script which acts as a test orchestrator to trigger Github workflow runners in a plugin/component repository. With this feature, during release testing build team will be able to use this script to trigger the cypress tests hosted within plugins repositories and make sure if those workflows succeeded or not. Every plugin component can write tests in the same repository where their feature resides and do not have to paste the tests in functional test repo which is outside of the feature changes.
https://github.com/opensearch-project/opensearch-dashboards-functional-test/issues/972
By submitting this pull request, I …
> Add test orchestrator script to trigger remote workflow runner outside functional test repo for cypress tests

- cypress/integration/plugins/alerting-dashboards-plugin/cluster_metrics_monitor_spec.js
Sometimes we see cluster metrics monitor creation test fail due to a slower response from api types monitor execution. Adding wait time before selecting the cluster health API.
> [Alerting] Added wait before selecting Cluster Health API

- cypress/integration/plugins/security-dashboards-plugin/readonly.js
- cypress/integration/plugins/security-dashboards-plugin/switch_tenant.js
- cypress/utils/commands.js
> [Backport 2.x] Read-only tenant mode tests

- cypress/integration/plugins/security/internalusers_spec.js
- cypress/utils/plugins/security/commands.js
- cypress/utils/plugins/security/constants.js
This PR changed the API called in main, but was not backported to 2.x: https://github.com/opensearch-project/security-dashboards-plugin/pull/1502. It also changes some text. This updates internal users tests to accommodate those changes. It should **NOT** be backported to 2.x line.
Fix: https://github.com/opensearch-project/security-dashboards-plugin/issues/1645
> Adapt recent changes in the security plugin to pass integ test

- .github/workflows/release-signoff-chrome.yml
- .github/workflows/release-signoff-chromium-ad-only.yml
- .github/workflows/release-signoff-chromium-ism-only.yml
- .github/workflows/release-signoff-chromium-tests-in-memory-0.yml
- .github/workflows/release-signoff-chromium-tests-in-memory-10.yml
- .github/workflows/release-signoff-chromium-tests-in-memory-20.yml
- .github/workflows/release-signoff-chromium-tests-in-memory-5.yml
- .github/workflows/release-signoff-chromium.yml
- .github/workflows/release-signoff-electron.yml
- .github/workflows/release-signoff-firefox.yml
The `Run OpenSearch-Dashboards server` task was failed in the regular [release sign-off workflow](https://github.com/opensearch-project/opensearch-dashboards-functional-test/actions/runs/7485045221/job/20372861098), the OSD API status checker missing required credentials and respond 401 error.
Since the OpenSearch was run with security enabled,  we need to pass the admin credentials to the `curl` command.
This PR add `-u admin:${{ env.OPENSEARCH_INITIAL_ADMIN_PASSWORD }}` to the `curl` call for all release sign-off workflows.
#985  …
> add admin credentials for regular release sign-off workflow

- cypress/integration/plugins/observability-dashboards/7_datasources_dashboard.spec.js
- cypress/utils/plugins/observability-dashboards/constants.js
Add functional test for datasources at observability dashboards plugin
> Add functional test for datasources at observability dashboards plugin

- test_finder.sh
For new onboarding plugin, need to add test map so that intetest.sh can find the directory based on the input of `component`.
For assistant component name, refer to https://github.com/opensearch-project/opensearch-build/pull/4363
> feat: add test map for dashboards-assistant

- cypress/integration/common/dashboard_sample_data_spec.js
- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/home/section.spec.js
- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/dashboard_sample_data_with_datasource_spec.js
> Add tests for the new homepage

- cypress/integration/plugins/observability-dashboards/6_notebooks.spec.js
- cypress/utils/plugins/observability-dashboards/constants.js
Update notebooks tests, this PR depends on notebooks updates to be merged by this PR: https://github.com/opensearch-project/dashboards-observability/pull/1367
https://github.com/opensearch-project/opensearch-dashboards-functional-test/issues/897
> Update notebooks tests

- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/data_explorer/data_source_selector.spec.js
- package.json
Add e2e tests for data source selector.
```
Data source selector
✓ displays all data sources by default (5755ms)
✓ filters options based on user input
✓ updates the visual length of the dropdown based on filtered results
✓ selects the correct option when clicked
4 passing (9s)
```
Following up on [#5211](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5211)
> Add tests for data source selector

- cypress/fixtures/plugins/dashboards-assistant/agent-framework-thought-response.json
- cypress/integration/plugins/dashboards-assistant/chatbot_agent_framework_spec.js
- cypress/integration/plugins/dashboards-assistant/chatbot_interaction_trace_spec.js
- cypress/support/assistant-dummy-llm.js
1. Add functional test for chat assistant trace page
2. Add tool invocation into mock LLM server
https://github.com/opensearch-project/opensearch-dashboards-functional-test/assets/113890546/3e4ab295-4711-4121-b714-086b62c7f639
> Add functional test for dashboard assistant trace page  

- cypress/fixtures/plugins/dashboards-assistant/agent-framework-thought-response.json
- cypress/integration/plugins/dashboards-assistant/chatbot_interaction_trace_spec.js
- cypress/support/assistant-dummy-llm.js
Backport 32cba8323cc07910b2e9c7babc8dc3b424adc684 from #1012
> [Backport 2.x] Add functional test for dashboard assistant trace page   (#1012)

- .github/workflows/release-signoff-chrome.yml
- .github/workflows/release-signoff-chromium-ad-only.yml
- .github/workflows/release-signoff-chromium-ism-only.yml
- .github/workflows/release-signoff-chromium-tests-in-memory-0.yml
- .github/workflows/release-signoff-chromium-tests-in-memory-10.yml
- .github/workflows/release-signoff-chromium-tests-in-memory-20.yml
- .github/workflows/release-signoff-chromium-tests-in-memory-5.yml
- .github/workflows/release-signoff-chromium.yml
- .github/workflows/release-signoff-electron.yml
- .github/workflows/release-signoff-firefox.yml
The release sign off test workflow always hang during test execution. 
Add `CYPRESS_NO_COMMAND_LOG=1` to env variables to unhang. 
> feat: add CYPRESS_NO_COMMAND_LOG to release signoff workflows

- cypress/integration/plugins/observability-dashboards/7_datasources_dashboard.spec.js
- cypress/utils/plugins/observability-dashboards/constants.js
Add functional test for datasources at observability dashboards plugin
* Backport https://github.com/opensearch-project/opensearch-dashboards-functional-test/pull/987
> [Backport 2.x] Add functional test for datasources at observability dashboards plugin

- cypress/integration/plugins/index-management-dashboards-plugin/indices_spec.js
- cypress/integration/plugins/index-management-dashboards-plugin/managed_indices_spec.js
- cypress/integration/plugins/index-management-dashboards-plugin/notification_settings.js
- cypress/integration/plugins/index-management-dashboards-plugin/rollups_spec.js
Change ...
1. 'Close indices' to 'Close'
2. 'Open indices' to 'Open'
3. 'indices' to 'indexes'
4. Sample slack webhook to meet current validation
... to match current tech writing guidelines.
Same fixes can be applied to 2.x for fixing #1008
> ism-plugin: fix tests

- cypress/integration/plugins/index-management-dashboards-plugin/indices_spec.js
- cypress/integration/plugins/index-management-dashboards-plugin/managed_indices_spec.js
- cypress/integration/plugins/index-management-dashboards-plugin/notification_settings.js
- cypress/integration/plugins/index-management-dashboards-plugin/rollups_spec.js
Backport [`10443bd`](https://github.com/opensearch-project/opensearch-dashboards-functional-test/commit/10443bddc26164d8cf24878746fe47897f060c79) from #1030
> [Backport 2.x] ism-plugin: fix tests

- cypress/integration/plugins/observability-dashboards/1_trace_analytics_dashboard.spec.js
Resolved https://github.com/opensearch-project/opensearch-dashboards-functional-test/issues/1022
Updated the tests so that time range is set and refresh button is clicked before the `Service and operations` accordion is opened to avoid the `TypeError: Converting circular structure to JSON`.
> fixed observability tests running forever

- cypress/integration/plugins/observability-dashboards/7_datasources_dashboard.spec.js
Fix datasources test cases' url assertion when security is enabled
**Please merge after https://github.com/opensearch-project/opensearch-dashboards-functional-test/pull/1023 so that we can verify the fix in CI.**
* Forwardport https://github.com/opensearch-project/opensearch-dashboards-functional-test/pull/1024
> [Forwardport main] Fix datasources test cases' url assertion

- cypress/integration/plugins/dashboards-assistant/conversation_save_to_notebook_spec.js
- cypress/utils/plugins/dashboards-assistant/helpers.js
Add functional tests for save to notebook
https://github.com/opensearch-project/opensearch-dashboards-functional-test/assets/4034161/803d7031-0577-4bea-a398-de400dadac54
Due to the [ml-commons issue](https://github.com/opensearch-project/ml-commons/issues/1971), this tests can be passed with previous version of ml-commons plugin.
> feat: add functional tests for conversation save to notebook

- cypress/integration/plugins/dashboards-assistant/chatbot_agent_framework_spec.js
> feat: add regenerate cases

- .github/workflows/remote-cypress-workflow.yml
- integtest.sh
- poll_remote_workflow.sh
- remoteCypress.sh
- remote_cypress_manifest.json
Adding remote cypress workflow orchestrator script integration with existing logic of integtest.sh script. This will keep the current behavior of integtest script as it is when triggered along with silently triggering the remote cypress workflows present in the plugin/components as defined in manifest json file and continue to poll them till its completion. 
Changes summary:
* Orchestrator integration with integtest script.
* Adding manifest json file to define plugin/components that gets onboarded to use orchestrator workflow. This manifest is used to capture plugin repo name, workflow name, branch that needs to be tested and any additional security related configuration that needs to be passed to the cypress tests running remote github workflows.
* In this iteration I'm adding …
> Add remote cypress orchestrator integration with integtest script

- cypress/integration/plugins/observability-dashboards/4_panels.spec.js
- cypress/utils/plugins/observability-dashboards/constants.js
Improving flaky panels tests by removing most unnecessary waits, adding a longer timeout for page to load. Also added a check for the second test
#897 
> Improve Observability Panels Tests

- test_finder.sh
Improve bash checking in test_finder.sh for all OSes
https://github.com/opensearch-project/opensearch-build/issues/4370#issuecomment-1928454267
> Improve bash checking in test_finder.sh for all OSes

- cypress/integration/plugins/observability-dashboards/4_panels.spec.js
- cypress/integration/plugins/reports-dashboards/04-download.spec.js
Fix dashboards observability and reporting test failures.
[272](https://github.com/opensearch-project/dashboards-reporting/issues/272)
[1321](https://github.com/opensearch-project/dashboards-observability/issues/1321)
> Fix dashboards observability and reporting test CI issue

- cypress/integration/plugins/custom-import-map-dashboards/1_import_vector_map_tab.spec.js
- cypress/integration/plugins/custom-import-map-dashboards/2_opensearchMapLayer.spec.js
- cypress/integration/plugins/custom-import-map-dashboards/3_add_saved_object.spec.js
- cypress/integration/plugins/custom-import-map-dashboards/4_documentsLayer.spec.js
Increase the timeout and wait period for maps-dashboards tests to prevent intermittent failures, especially in Jenkins CI with security enabled.
Tested in docker image `opensearchstaging/ci-runner:ci-runner-rockylinux8-opensearch-dashboards-integtest-v4` which is same used in [Jenkins Integ Test Pipeline](https://build.ci.opensearch.org/job/integ-test-opensearch-dashboards/).
```
Spec                                              Tests  Passing  Failing  Pending  Skipped  
│ ✔  plugins/custom-import-map-dashboard      00:24        1        1        -        -        - │
│    s/1_import_vector_map_tab.spec.js                                                           │ …
```
> Increase timeout and wait to maps-dashboards tests

- cypress/integration/plugins/observability-dashboards/6_notebooks.spec.js
- cypress/utils/plugins/observability-dashboards/constants.js
Notebooks add index refresh, remove SQL check in paragraph
https://github.com/opensearch-project/opensearch-dashboards-functional-test/issues/897
> Notebooks add index refresh, remove SQL check in paragraph

- integtest.sh
Disable video recording in Windows due to ffmpeg crash
Also remove a rm issue causing failure due to file not exist raised in #988.
https://github.com/opensearch-project/opensearch-dashboards-functional-test/issues/1068
> Disable video recording in Windows due to ffmpeg crash

- integtest.sh
[2.x] Adding placeholder to keep main/2.x/1.x consistent before #988 backports and disable windows video recording
#1068
#1069
> [2.x] Adding placeholder to keep main/2.x/1.x consistent before #988 backports and disable windows video recording

- cypress/integration/plugins/custom-import-map-dashboards/1_import_vector_map_tab.spec.js
- cypress/integration/plugins/custom-import-map-dashboards/2_opensearchMapLayer.spec.js
- cypress/integration/plugins/custom-import-map-dashboards/3_add_saved_object.spec.js
- cypress/integration/plugins/custom-import-map-dashboards/4_documentsLayer.spec.js
Update tenant to global to maps-dashboards
```
arm64-tar-with-security:
Spec                                              Tests  Passing  Failing  Pending  Skipped  
│ ✔  plugins/custom-import-map-dashboard      00:30        1        1        -        -        - │
│    s/1_import_vector_map_tab.spec.js                                                           │
├────────────────────────────────────────────────────────────────────────────────────────────────┤
│ ✔  plugins/custom-import-map-dashboard      01:49        1        1        -        -        - │
│    s/2_opensearchMapLayer.spec.js                                                              │ …
```
> Update tenant to global to maps-dashboards

- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/data_explorer/date_nanos.spec.js
- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/data_explorer/date_nanos_mixed.spec.js
- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/data_explorer/discover.spec.js
- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/data_explorer/doc_navigation.spec.js
- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/data_explorer/doc_table.spec.js
- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/data_explorer/field_data.spec.js
- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/data_explorer/index_pattern_with_encoded_id.spec.js
- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/data_explorer/index_pattern_without_field.spec.js
- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/data_explorer/large_string.spec.js
- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/data_explorer/saved_queries.spec.js
- cypress/utils/dashboards/data_explorer/commands.js
- cypress/utils/dashboards/data_explorer/index.d.ts
- package.json
This PR enables cypress tests to run datagrid table. By navigating via `cy.switchDiscoverTable('new');`, discover will load datagrid table. This will accomadate the changes due to the change of restore legacy table in this PR https://github.com/opensearch-project/OpenSearch-Dashboards/pull/5789
We will temporarily skip `apps/data_explorer/saved_queries.spec.js` due to a bug. Once we fixed the issue, we will restore the test.
> Enable cypress tests to run datagrid table in Discover

- cypress/integration/plugins/observability-dashboards/6_notebooks.spec.js
When checking for a reporting download being triggered, the tests are waiting for a loading screen. This causes test failures if the download happens faster than React renders. In one test run, the test failed when the API returned in 18 ms (whereas a passing test in the same run had a return time of 224 ms). This PR updates the tests to instead check for the success toast.
N/A
> Fix in-context reporting tests

- cypress/integration/plugins/gantt-chart-dashboards/gantt_ui.spec.js
Increase delay times in gantt charts. This solves the tests not working as expected in environments where UI takes more time to load especially when security plugin is enabled.
https://github.com/opensearch-project/opensearch-dashboards-functional-test/issues/914
> Increase delay times in gantt charts

- cypress/integration/plugins/query-workbench-dashboards/ui.spec.js
- cypress/utils/plugins/query-workbench-dashboards/constants.js
When running integration tests on windows, the CSV data inconsistently was encoded with `\r\n` or `\n`, which caused a failing test assertion. This PR adds a method to normalize the test data.
N/A
> Normalize query workbench constant newlines

- cypress/integration/plugins/alerting-dashboards-plugin/acknowledge_alerts_modal_spec.js
- cypress/integration/plugins/alerting-dashboards-plugin/alert_spec.js
- cypress/integration/plugins/alerting-dashboards-plugin/alerts_dashboard_flyout_spec.js
- cypress/integration/plugins/alerting-dashboards-plugin/bucket_level_monitor_spec.js
- cypress/integration/plugins/alerting-dashboards-plugin/cluster_metrics_monitor_spec.js
- cypress/integration/plugins/alerting-dashboards-plugin/composite_level_monitor_spec.js
- cypress/integration/plugins/alerting-dashboards-plugin/document_level_monitor_spec.js
- cypress/integration/plugins/alerting-dashboards-plugin/monitors_dashboard_spec.js
- cypress/integration/plugins/alerting-dashboards-plugin/query_level_monitor_spec.js
- cypress/utils/plugins/alerting-dashboards-plugin/constants.js
Increased timeout thresholds for alerting cypress tests to reduce flakiness when running on slow domains.
https://github.com/opensearch-project/alerting-dashboards-plugin/issues/867
> Increased timeout thresholds for alerting cypress tests to reduce flakiness when running on slow domains.

- cypress/integration/plugins/alerting-dashboards-plugin/acknowledge_alerts_modal_spec.js
- cypress/integration/plugins/alerting-dashboards-plugin/alert_spec.js
- cypress/integration/plugins/alerting-dashboards-plugin/alerts_dashboard_flyout_spec.js
- cypress/integration/plugins/alerting-dashboards-plugin/bucket_level_monitor_spec.js
- cypress/integration/plugins/alerting-dashboards-plugin/cluster_metrics_monitor_spec.js
- cypress/integration/plugins/alerting-dashboards-plugin/composite_level_monitor_spec.js
- cypress/integration/plugins/alerting-dashboards-plugin/document_level_monitor_spec.js
- cypress/integration/plugins/alerting-dashboards-plugin/monitors_dashboard_spec.js
- cypress/integration/plugins/alerting-dashboards-plugin/query_level_monitor_spec.js
- cypress/utils/plugins/alerting-dashboards-plugin/constants.js
Manually cherry-picked PR #1093 
> [Backport 2.x] Increased timeout thresholds for alerting cypress tests to reduce flakiness when running on slow domains. #1093

- cypress/integration/plugins/alerting-dashboards-plugin/acknowledge_alerts_modal_spec.js
- cypress/integration/plugins/alerting-dashboards-plugin/alert_spec.js
- cypress/integration/plugins/alerting-dashboards-plugin/alerts_dashboard_flyout_spec.js
- cypress/integration/plugins/alerting-dashboards-plugin/bucket_level_monitor_spec.js
- cypress/integration/plugins/alerting-dashboards-plugin/cluster_metrics_monitor_spec.js
- cypress/integration/plugins/alerting-dashboards-plugin/composite_level_monitor_spec.js
- cypress/integration/plugins/alerting-dashboards-plugin/document_level_monitor_spec.js
- cypress/integration/plugins/alerting-dashboards-plugin/monitors_dashboard_spec.js
- cypress/integration/plugins/alerting-dashboards-plugin/query_level_monitor_spec.js
- cypress/utils/plugins/alerting-dashboards-plugin/constants.js
Manually cherry-picked PR #1093 
> [Backport 2.12] Increased timeout thresholds for alerting cypress tests to reduce flakiness when running on slow domains. #1093

- .github/workflows/alerting-release-e2e-workflow.yml
- .github/workflows/anomaly-detection-release-e2e-workflow.yml
- .github/workflows/cypress-workflow-bundle-snapshot-based.yml
- .github/workflows/index-management-release-e2e-workflow.yml
- .github/workflows/security-analytics-release-e2e-workflow.yml
- .github/workflows/security-release-e2e-workflow.yml
The workflows of alerting, anomaly detection, OSD Core, index management, security analytics, security plugin are timeout due to #1055. This PR is for bypass these timeouts.
The workflow can be finished after adding NO_COMMAND_LOG env variable. Here is the details:
**alerting:** https://github.com/opensearch-project/opensearch-dashboards-functional-test/actions/runs/8014175412/job/21892373162?pr=1066
**anomaly detection:** https://github.com/opensearch-project/opensearch-dashboards-functional-test/actions/runs/8014175413/job/21892371861?pr=1066
**OSD Core:** 
https://github.com/opensearch-project/opensearch-dashboards-functional-test/actions/runs/8014175416/job/21892374262?pr=1066
https://github.com/opensearch-project/opensearch-dashboards-functional-test/actions/runs/8014175416/job/218923 …
> ci: add NO_COMMAND_LOG to unhang

- browser_downloader.sh
- integtest.sh
Add download_chromium to integtest.sh for standalone chromium installation
Closes: https://github.com/opensearch-project/opensearch-build/issues/4459
> Add download_chromium to integtest.sh for standalone chromium installation

- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/data_explorer/shared_links.spec.js
1. refactor so that each test case is independent from each other
2. use decodeURI to make url consistent so that the url matches
this PR fixed the 3 failed tests of `cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/data_explorer/shared_links.spec.js`
```
shared links
shared links with state in query
1) should allow for copying the snapshot URL
✓ should allow for copying the snapshot URL as a short URL
2) should allow for copying the saved object URL
shared links with state in sessionStorage
✓ should allow for copying the snapshot URL (12854ms)
✓ should allow for copying the snapshot URL as a short URL
3) should allow for copying the saved object URL
3 passing (4m)
3 failing
1) shared links
shared links with state in query
should allow for copying the snapshot …
```
> fixed failed discover app shared links tests

- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/data_explorer/date_nanos.spec.js
- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/data_explorer/date_nanos_mixed.spec.js
- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/data_explorer/discover.spec.js
- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/data_explorer/field_data.spec.js
- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/data_explorer/index_pattern_with_encoded_id.spec.js
- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/data_explorer/index_pattern_without_field.spec.js
- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/data_explorer/saved_queries.spec.js
- cypress/utils/dashboards/data_explorer/commands.js
Address changes from:  https://github.com/opensearch-project/OpenSearch-Dashboards/pull/6170
n/a
> [Discover] toggle for legacy mode

- cypress/integration/plugins/custom-import-map-dashboards/1_import_vector_map_tab.spec.js
- cypress/integration/plugins/custom-import-map-dashboards/2_opensearchMapLayer.spec.js
- cypress/integration/plugins/custom-import-map-dashboards/3_add_saved_object.spec.js
- cypress/integration/plugins/custom-import-map-dashboards/4_documentsLayer.spec.js
This PR does:
1. Update "data source" name from https://github.com/opensearch-project/dashboards-maps/pull/588
2. Rebase code change from 2.x to main.
Local test:
```
Spec                                              Tests  Passing  Failing  Pending  Skipped  
│ ✔  plugins/custom-import-map-dashboard      00:51        1        1        -        -        - │
│    s/1_import_vector_map_tab.spec.js                                                           │
├────────────────────────────────────────────────────────────────────────────────────────────────┤
│ ✔  plugins/custom-import-map-dashboard      01:54        1        1        -        -        - │
│    s/2_opensearchMapLayer.spec.js …
```
> [maps-dashboards] Update data source name and rebase code in maps

- cypress/integration/plugins/index-management-dashboards-plugin/indices_spec.js
During one of the tests for indices, we create an index with name `reindex_opensearch_dashboards_sample_data_ecommerce` that is superstring for the sample index `opensearch_dashboards_sample_data_ecommerce`. This new index is supposed to get deleted but sometimes it might not get deleted due to failure in backend and after that if some other test looks for the sample index and tries to select that index from a combo box, it faces collision and might end up not selecting any index. This PR renames the new index to avoid this situation.
Fixes flaky test in Index Management Dashboards - https://github.com/opensearch-project/index-management-dashboards-plugin/issues/880
For more …
> [Index-mgmt] Renamed index to avoid collision for other tests

- cypress/integration/plugins/dashboards-assistant/chatbot_interaction_trace_spec.js
- cypress/integration/plugins/dashboards-assistant/chatbot_sidecar_spec.js
- cypress/integration/plugins/dashboards-assistant/conversation_history_spec.js
Add functional test for sidecar.
This functional test should run on the feat-sidecar branch of OSD and dashboard-assistant repo, so checks may fail in CI env.
Following is the recording and result of tests.
https://github.com/opensearch-project/opensearch-dashboards-functional-test/assets/42465692/dc2f0cce-420c-4caf-a75e-213f3bf456b4
Depend on OSD PR: https://github.com/opensearch-project/OpenSearch-Dashboards/pull/5920
> add functional test for sidecar

- .github/workflows/security-release-e2e-workflow.yml
> include security-dashboards-plugin into security CI

- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/data_explorer/large_string.spec.js
Other test utilize the helper function and not seeing the particular need for this test to ensure it switches. But by doing this avoid whatever is taking focus of the popover that lets the test first click the button but before cypress test runner clicks the switch.
n/a
> [Discover] set local storage directly for large string spec

- cypress/integration/plugins/alerting-dashboards-plugin/acknowledge_alerts_modal_spec.js
Adding intercept to ensure monitor search call finishes after page load before we check for the monitor value and fail.
https://github.com/opensearch-project/alerting-dashboards-plugin/issues/910
> [Alerting][2.13] Improve acknowledge alerts tests

- cypress/integration/plugins/observability-dashboards/6_notebooks.spec.js
- cypress/utils/plugins/observability-dashboards/constants.js
Coming from the autocut issue https://github.com/opensearch-project/dashboards-observability/issues/1579: the tests for notebooks are failing in 2.13. This test suite has been flaky for a while, and it looked like the reason this one was failing was because some other delete action was interfering with the test (it was looking for a notebook but there was an empty notebook state).
This PR completely refactors these tests to be mutually independent: every test gets its own notebook with a randomized name, and each notebook has its own teardown. This should help avoid all the weird interdependent flakiness from before with this suite.
Needs backporting to 2.x and 2.13.
https://github.com/opensearch-project/dashboards-observability/issues/1579
By submitting this pull request, I confirm that …
> Refactor 6_notebooks.spec.js

- .github/workflows/cypress-workflow-bundle-snapshot-based-windows.yml
- .github/workflows/cypress-workflow-bundle-snapshot-based.yml
Resolved 
https://github.com/opensearch-project/opensearch-dashboards-functional-test/issues/993
https://github.com/opensearch-project/opensearch-dashboards-functional-test/issues/1108
Removed `dorny/paths-filter` action and use GitHub workflow builtin path filter
> fix(workflow): paths-filter error on push event

- cypress/integration/plugins/index-management-dashboards-plugin/rollups_spec.js
- cypress/integration/plugins/index-management-dashboards-plugin/transforms_spec.js
Adding intercepts and wait time to mitigate flaky tests.
Resolves https://github.com/opensearch-project/index-management-dashboards-plugin/issues/1011
> [Backport 2.13] rollups/transform: wait for page to render

- cypress/integration/plugins/index-management-dashboards-plugin/rollups_spec.js
- cypress/integration/plugins/index-management-dashboards-plugin/transforms_spec.js
Adding intercepts and wait time to mitigate flaky tests.
Resolves https://github.com/opensearch-project/index-management-dashboards-plugin/issues/1011
> [Backport 2.x] rollups/transform: wait for page to render

- cypress/integration/plugins/index-management-dashboards-plugin/rollups_spec.js
- cypress/integration/plugins/index-management-dashboards-plugin/transforms_spec.js
Adding intercepts and wait time to mitigate flaky tests.
https://github.com/opensearch-project/index-management-dashboards-plugin/issues/968
> rollups/transform: wait for page to render

- cypress/integration/plugins/alerting-dashboards-plugin/acknowledge_alerts_modal_spec.js
Delete alerts before and after running tests for the acknowledge alerts spec
https://github.com/opensearch-project/alerting-dashboards-plugin/issues/910
> [Alerting][2.13] Delete alerts before and after running tests

- cypress/integration/plugins/gantt-chart-dashboards/gantt_ui.spec.js
Refactor `dashboards-visualization` flaky tests
[#354](https://github.com/opensearch-project/dashboards-visualizations/issues/354)
> Fix Flaky Dashboards Visualization Tests

- cypress/integration/plugins/gantt-chart-dashboards/gantt_ui.spec.js
Duplicate of #1194 to attempt on `2.13` since OS is more stable.
Since #1187 was merged in while the failures were unresolved, opening this one to fix failures. Setting to draft initially so it doesn't get merged before finished again. Following #1033 example of setting tenants
**Needs `backport 2.x` and `backport main` labels. Must go in _after_ #1190 and #1191**
[#354](https://github.com/opensearch-project/dashboards-visualizations/issues/354)
> [2.13] Switch to Private Tenant for Gantt Charts Tests

- DEVELOPER_GUIDE.md
Add developer doc for Orchestrator remote test workflow
> [Docs] Add developer doc for Orchestrator remote test workflow

- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/datasource-management-plugin/1_create_datasource.spec.js
- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/datasource-management-plugin/3_update_datasource.spec.js
- cypress/utils/dashboards/datasource-management-dashboards-plugin/constants.js
- In https://github.com/opensearch-project/OpenSearch-Dashboards/pull/5315, we switched from `EuiSelect` to `EuiSuperSelect`, causing some test cases to fail. This PR addressed these failures, and make sure all related tests can pass
- clean the code by using existing util functions, and constants
#1198 
> [Multiple Datasource]Fix failed test cases caused by switching from EuiSelect to EuiSuperSelect

- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/vis_builder/basic.spec.js
- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/vis_builder/dashboard.spec.js
- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/vis_builder/experimental.spec.js
- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/vis_builder/vis_types/area.spec.js
- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/vis_builder/vis_types/bar.spec.js
- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/vis_builder/vis_types/line.spec.js
- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/vis_builder/vis_types/metric.spec.js
- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/vis_builder/vis_types/table.spec.js
Flaky tests due to loading time due to switch tenant. Currently set default tenant to global.
Partial https://github.com/opensearch-project/opensearch-build/issues/4433
> Use global tenant in vis-builder tests

- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/data_explorer/shared_links.spec.js
A copied snapshot URL included `security_tenant` when security plugin was enabled and multitenancy was configured. This change sanitizes the copied URL before asserting to make the tests work correctly with and without security and multitenancy.
Fixes https://github.com/opensearch-project/OpenSearch-Dashboards/issues/6373
> [OSD] Sanitize copied share-link before validating

- cypress/integration/plugins/security-analytics-dashboards-plugin/1_detectors.spec.js
- cypress/integration/plugins/security-analytics-dashboards-plugin/2_rules.spec.js
- cypress/integration/plugins/security-analytics-dashboards-plugin/3_alerts.spec.js
- cypress/integration/plugins/security-analytics-dashboards-plugin/4_findings.spec.js
- cypress/utils/plugins/security-analytics-dashboards-plugin/commands.js
- cypress/utils/plugins/security-analytics-dashboards-plugin/constants.js
- cypress/utils/plugins/security-analytics-dashboards-plugin/helpers.js
Updated cypress tests for security analytics 2.11
> [Security Analytics] Updated tests 2.11

- cypress/integration/plugins/gantt-chart-dashboards/gantt_ui.spec.js
Adds global tenant to gantt-charts 
https://github.com/opensearch-project/dashboards-visualizations/issues/357
https://github.com/opensearch-project/dashboards-visualizations/issues/362
> Update gantt chart tenant

- .github/workflows/workspace-release-e2e-workflow.yml
- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/workspace-plugin/workspace_create.spec.js
Fix errors in the workspace workflow.
1. When `workspace` and `opensearch_security.multitenancy` are  enabled at the same time, OSD will report an error ([plugins][securityDashboards] StatusCodeError: Authorization Exception).
Related Issue: https://github.com/opensearch-project/OpenSearch-Dashboards/issues/6314
2. Create a workspace in the test and do not delete it after completing the test, resulting in the inconsistent return result with the expected result.
Turn off `opensearch_security.multitenancy` when `security` is enabled.
Add an operation to delete the workspace in `after()`.
For more information on following Developer Certificate of Origin and signing off your …
> [Workspace] Clean up workspace after tests and disable multi-tenancy when running workspace test

- cypress/integration/plugins/reports-dashboards/01-create.spec.js
- cypress/integration/plugins/reports-dashboards/04-download.spec.js
Add get tenant to flaky tests
https://github.com/opensearch-project/dashboards-reporting/issues/342
> Update tenant in reporting tests

- .github/CODEOWNERS
current code owner list doesn't match with reviewer list
current list 
https://raw.githubusercontent.com/opensearch-project/opensearch-dashboards-functional-test/main/.github/CODEOWNERS
```
*   @tianleh @kavilla @ohltyler @CCongWang @ashwin-pc @peterzhuamazon @ananzh @prudhvigodithi
*   @xluo-aws @Hailong-am @SuZhou-Joe @ruanyl @wanglam @raintygao
```
Current review list
looks like default reviewer list load last line of the file.
merge two lines to fix the issue
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-o …
> fix issue code reviewer list doesn't reflect the right code owner list

- cypress/integration/plugins/observability-dashboards/6_notebooks.spec.js
While debugging the failing tests https://github.com/opensearch-project/dashboards-observability/issues/1702, it looks like the reason is that the notebook loading is flaky immediately after creation. This is due to not using the refresh logic in the `moveToTestNotebook` method in the second test suite, it was only present in the first. After looking over the usage of this method, I decided to move the refresh logic straight to `makeTestNotebook` and deleted `moveToTestNotebook` since its only use seemed to be to force this refresh.
Needs backport to 2.x / 2.14.
N/A …
> Use moveToTestNotebook during notebooks-reporting integration suite

- cypress/utils/plugins/ml-commons-dashboards/commands.js
This PR is for fixing integration test failed in https://github.com/opensearch-project/ml-commons-dashboards/issues/322 .
The root cause of tests failed was `Memory Circuit Breaker is open`, increase to 100 to avoid this error.
> Increase jvm_heap_memory_threshold to 100 for ml-commons dashboards

- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/workspace-plugin/workspace_create.spec.js
- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/workspace-plugin/workspace_dropdown_menu.spec.js
- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/workspace-plugin/workspace_overview.spec.js
- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/workspace-plugin/workspace_update.spec.js
- cypress/utils/dashboards/workspace-plugin/commands.js
Add functional test for workspace overview page
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/6583
> [Workspace] Add functional test for workspace overview page

- cypress/fixtures/dashboard/opensearch_dashboards/data_explorer/index_with_nested_field/data.json.txt
- cypress/fixtures/dashboard/opensearch_dashboards/data_explorer/index_with_nested_field/mappings.json.txt
- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/data_explorer/discover.spec.js
- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/data_explorer/discover_advanced_settings.spec.js
- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/data_explorer/discover_table.spec.js
- cypress/utils/dashboards/data_explorer/commands.js
This adds functional tests for the issues described in https://github.com/opensearch-project/OpenSearch-Dashboards/issues/6280.
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5713
Issues Still Pending (Sub Issues within the Test Suite are mentioned within brackets)
1. **Function Test Suite 2: Copy data without extra data:** No easy way to test copying data to clipboard in cypress
2. **Function Test Suite 5: Left Navigation Display (Should display Unknown type field properly in left navigation):** Niche scenario
3. **Function Test Suite 6: Saved Search Embeddable in Dashboard (When load a saved search in dashboard, sort should be loaded properly Issue: https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5933)** : Issue still open hence couldn't be tested …
> Add Discover Table Tests

- cypress/utils/plugins/anomaly-detection-dashboards-plugin/constants.js
This PR addresses a test failure caused by the recent update of the listing detectors URL from '/detectors' to '/detectors/_list' as implemented in server/routes/ad.ts. The change was introduced in https://github.com/opensearch-project/anomaly-detection-dashboards-plugin/pull/739. Previously, the tests in `dashboard_spec.js` and `detector_list_spec.js` were failing because they were waiting for requests to `BASE_AD_NODE_API_PATH + '/detectors*'`, which no longer exists due to the URL update.
Testing:
- Successfully ran all tests in `dashboard_spec.js` and `detector_list_spec.js` to ensure that they now correctly interact with the updated URL.
For more information on following …
> Update getDetectors URL to match recent API changes

- cypress/utils/plugins/security/commands.js
After introducing MDS feature in 2.14, security dashboards API changed to include a query param - dataSourceId= to indicate which datasource the call is being made for. This was not being appropriately handled in the intercept, leading to timeout. This PR adds that param to the intercept calls so that tests work appropriately. 
> Fix paths for MDS api changes

- .github/workflows/cypress-workflow-bundle-snapshot-based.yml
- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/datasource-management-plugin/1_create_datasource.spec.js
- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/datasource-management-plugin/2_datasource_table.spec.js
- cypress/utils/dashboards/datasource-management-dashboards-plugin/commands.js
- cypress/utils/dashboards/datasource-management-dashboards-plugin/constants.js
- Replace fake data source endpoint with real endpoint (auth, and no auth)
- skip sigv4 related tests since infra workflow doesn't support create , and those tests will fail
There are 4 CI related to the function tests is OSD core, and they all failed, not caused by MDS tests and test infra.
1. [e2e windows, with security:](https://github.com/opensearch-project/opensearch-dashboards-functional-test/actions/runs/8934752160/job/24542128919?pr=1260) failed to spin up opensearch, not even reach cypress test step
2. [e2e windows, without security](https://github.com/opensearch-project/opensearch-dashboards-functional-test/actions/runs/8934752160/job/24542128808?pr=1260): failed because workflow template doesn't allow passing osd arguments `data_source.enabled=true` …
> [MD] Replace fake data source endpoint with configurable real endpoint

- cypress/integration/plugins/observability-dashboards/6_notebooks.spec.js
Since notebooks are still flaky on notebook creation, even with refresh logic added (see #1250), I think the reason the tests are still failing is because notebook creation is flaky in some index refresh race condition scenarios. This PR refactors the notebook creation to drop the refresh attempt and only check for a successful creation message, on the assumption that notebooks should have a functional requirement to always show a valid notebook after stating a successful creation.
I'm not sure this fixes the flaky tests in CI (still struggling to understand the root cause and get exact repro steps), but in local testing this passed 10 consecutive runs (the old version failed after 6 runs and a version with both parts fails almost every run). This should also pass the ball out of the …
> Add further creation waits to notebooks tests

- cypress/integration/plugins/observability-dashboards/4_panels.spec.js
Move `createDashboard` intercept to before `Create` button is clicked, in the event that the `Create` request completes prior to the wait.
Needs `backport 2.x`
N/A
> Move Intercept in Observability Panels Test

- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/data_explorer/aaa_before.spec.js
- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/data_explorer/discover.spec.js
- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/data_explorer/discover_advanced_settings.spec.js
- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/data_explorer/index_pattern_without_field.spec.js
- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/data_explorer/shared_links.spec.js
- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/vis-augmenter/dashboard_spec.js
- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/vis_builder/basic.spec.js
- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/vis_builder/dashboard.spec.js
- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/vis_builder/vis_types/area.spec.js
- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/vis_builder/vis_types/bar.spec.js
- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/vis_builder/vis_types/line.spec.js
- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/vis_builder/vis_types/metric.spec.js
- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/vis_builder/vis_types/table.spec.js
- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/vis_type_table/basic.spec.js
- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/vis_type_table/data.spec.js
- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/vis_type_table/embed.spec.js
- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/vis_type_table/options.spec.js
- cypress/utils/commands.js
The security plugin underwent a logic change, rendering the current tenant setting code invalid. To rectify this, cy.fleshTenantSettings is being added to ensure that the tenant is properly configured, allowing all test cases to pass as they did previously.
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/6472
> Fix: flaky test on 2.14

- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/data_explorer/discover_advanced_settings.spec.js
- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/data_explorer/discover_table.spec.js
- cypress/utils/commands.js
> Fix Test Failures

- cypress/integration/plugins/observability-dashboards/7_datasources_dashboard.spec.js
- Skip datasources tests for managed service run
- backport `2.x`, `2.13`
Due to the design difference between opensource and managed service, the tests for observability datasources should only be run for opensource version.
> [Enhancement] Skip datasources tests for managed service run

- cypress/utils/commands.js
- cypress/utils/dashboards/commands.js
Tests ran failed on jenkins, where a smaller EC2 is used to run the integration test. This PR is changing to use a lightweight solution to flesh tenant settings to fix the bug and accelerate the test.
failed https://ci.opensearch.org/ci/dbc/integ-test-opensearch-dashboards/2.14.0/7633/linux/arm64/tar/test-results/5916/integ-test/OpenSearch-Dashboards/with-security/stdout.txt
**snapshot:**
pass https://ci.opensearch.org/ci/dbc/integ-test-opensearch-dashboards/2.14.0/7633/linux/arm64/tar/test-results/5916/integ-test/OpenSearch-Dashboards/without-security/stdout.txt
**snapshot:**
For more information on following Developer Certificate of Origin and signing off your commits, …
> fix: use lightweight way to flesh tenant settings

- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/dashboard_share_copy_link_test.js
Tries to reduce some flakiness from this test by navigating directly to discover instead of starting at stack management and trying to navigate there via UI
> Navigate directly to discover to reduce flakiness

- cypress/utils/commands.js
- cypress/utils/dashboards/commands.js
The default tenant does not take effect if adding commands inside `/dashboards/utils`, seems to have something to do with loop dependency. 
This PR fix that by moving the `fleshTenantSettings` to `/commands` directory.
> fix: defaultTenant does not take effect

- .github/CODEOWNERS
- MAINTAINERS.md
We have followed internal maintainer nomination process, and add maintainer: https://github.com/zhongnansu
N/A
> Add maintainer zhongnan

- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/vis_builder/basic.spec.js
Adding test case to validate vis Builder bugs that are addressed by https://github.com/opensearch-project/OpenSearch-Dashboards/pull/6811.  
https://github.com/opensearch-project/OpenSearch-Dashboards/pull/6811
Adding the test suite results after the above changes
https://github.com/opensearch-project/opensearch-dashboards-functional-test/assets/38322563/37e6f6df-cfe4-4327-ae6f-12c075c47fa5
> Add Test for Vis Builder Bugs

- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/datasource-management-plugin/4_set_default_datasource.spec.js
- cypress/utils/dashboards/datasource-management-dashboards-plugin/commands.js
Add FT for default data source 
1. Create data source
1. when create the first data source, it will be the default data source
2. Edit data source
1. Go to edit data source page, when the current data source is default data source, the set_default button is disabled
2. when the current data source is not default, the set_default button is enabled
3. After back to data source table, the default bage will be attached to the new data source
3. Data source table
1. Delete the default data source, the next one will be the default data source
✓ The first data source is the default data source (71217ms)
✓ Delete the default data source, the next one will become default data source (8905ms)
✓ Go the edit data source page of default data source, the set_default button should be disabled
✓ Go the …
> [MDS]Add FT test for default data source

- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/data_explorer/discover.spec.js
- cypress/utils/dashboards/data_explorer/commands.js
- cypress/utils/dashboards/data_explorer/index.d.ts
Due to https://github.com/opensearch-project/OpenSearch-Dashboards/pull/6167, we don't have the double render issue when global state is updated.
Therefore we don't need to call makeDatePickerMenuOpen function, which is just to reclick the DatePickerToggle to make the menu re-open. This function is a tmp solution to allow test passing.
In this PR, we will remove the function and all the usages.
https://github.com/opensearch-project/opensearch-dashboards-functional-test/assets/79961084/940a369b-bfb6-41f4-b7bf-0fefa9ce9c91
NA …
> Don't need to force DatePickerMenu open

- .github/workflows/cypress-workflow-bundle-snapshot-based.yml
- cypress.json
- cypress/fixtures/dashboard/opensearch_dashboards/telemetry/uiReport.json
- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/telemetry/server.spec.js
- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/telemetry/ui_metric.spec.js
- package.json
Add functional tests to validate the UI Metric Collector introduced in OpenSearch dashboards core. This PR is the same as 
https://github.com/opensearch-project/opensearch-dashboards-functional-test/pull/1223 wit the updated changes based on comments which got closed by mistake.   
Added test cases to validate server side batching of UI Metric reports introduced in https://github.com/opensearch-project/OpenSearch-Dashboards/pull/6721
**Tests**
https://github.com/opensearch-project/opensearch-dashboards-functional-test/assets/38322563/23f24815-0084-4448-bffa-dd92eb2753e1
https://github.com/opensearch-project/opensearch-dashboards-functional-test/assets/38322563/bbd3c5f8-ceaa-46d6-ba65-62bb28988668
https://github.com/opensearch-project/opensearch-dashboards-functional-test/assets/38322563/fa …
> Add functional test for UI Metric

- .github/workflows/workspace-release-e2e-workflow.yml
Fix dashboards admin missing for workspace security enabled tests
> Set dashboards admin for security enabled tests

- cypress/integration/plugins/observability-dashboards/1_trace_analytics_dashboard.spec.js
- cypress/integration/plugins/observability-dashboards/2_trace_analytics_services.spec.js
* Moves trace groups to trace page
* Add service flyout test
https://github.com/opensearch-project/opensearch-dashboards-functional-test/issues/1269
> Trace analytics cypress update for 2.15

- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/data_explorer/discover_table.spec.js
Fix Flaky tests in Discover Table.
Without Security
https://github.com/opensearch-project/opensearch-dashboards-functional-test/assets/38322563/e800b3fd-989e-444e-b5e4-eec8b1e62c1f
With Security
https://github.com/opensearch-project/opensearch-dashboards-functional-test/assets/38322563/bc377c53-ce91-4e42-903c-4bbb2e34bdcf
> Fix Flaky Discover Table Tests

- .github/actions/start-opensearch/action.yml
- .github/workflows/cypress-workflow-bundle-snapshot-based-ci-groups.yml
- .github/workflows/release-e2e-workflow-template-windows.yml
- .github/workflows/release-e2e-workflow-template.yml
There is a jar hell issue in opensearch 3.0.0. Bump JDK to 21 to mitigate.
> Bump JDK to 21

- cypress/integration/plugins/security/roles_spec.js
After an upstream change in security dashboards plugin, we are now showing a loading screen until the data is returned. This means that a previously faulty assertion became untrue. This PR fixes that. Now it asserts that when clicking on a cluster filter dropdown, a cluster permission link exists (previously it did not exist since the data was not returned yet). 
Fix: https://github.com/opensearch-project/security-dashboards-plugin/issues/1999
> Update assertion after loading fix

- cypress/integration/plugins/security-analytics-dashboards-plugin/3_alerts.spec.js
Updates alerts spec test for PRs 
- https://github.com/opensearch-project/security-analytics-dashboards-plugin/pull/1031
- https://github.com/opensearch-project/security-analytics-dashboards-plugin/pull/1033
> [Security Analytics][2.15] Fix alerts tests security analytics

- cypress/integration/plugins/security-analytics-dashboards-plugin/3_alerts.spec.js
Wait for alerts to load completely before checking their count
https://github.com/opensearch-project/security-analytics-dashboards-plugin/issues/1043
> [Security analytics][2.15] Wait for alerts to load completely before checking

- cypress/integration/plugins/index-management-dashboards-plugin/aliases.js
- cypress/integration/plugins/index-management-dashboards-plugin/data_streams.js
- cypress/integration/plugins/index-management-dashboards-plugin/indices_spec.js
- cypress/integration/plugins/index-management-dashboards-plugin/rollups_spec.js
- cypress/integration/plugins/index-management-dashboards-plugin/transforms_spec.js
This change reduces the possibility of failures of few flaky tests in IM dashboard
Flaky tests:
1. rollup_spec cypress test
2. transform_spec cypress test
N/A
> Cypress Fix for few flaky tests in index-management dashboard plugin during Jenkins executions

- cypress/integration/plugins/observability-dashboards/1_trace_analytics_dashboard.spec.js
Waits for trace group table to load, before proceeding to next cypress checks
https://github.com/opensearch-project/opensearch-dashboards-functional-test/issues/1269
> Check trace group table loading state 

- .github/workflows/cypress-workflow-bundle-snapshot-based-ci-groups.yml
- test_finder.sh
Extract the ci_groups_finder logic to test_finder.sh so that Jenkins workflow can reuse the CI groups to organize OSD test cases.
> feat: reuse specs finder

- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/workspace-plugin/mds_workspace_create.spec.js
- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/workspace-plugin/mds_workspace_import_sample_data_to.spec.js
- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/workspace-plugin/mds_workspace_overview.spec.js
- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/workspace-plugin/mds_workspace_update.spec.js
- cypress/utils/dashboards/workspace-plugin/commands.js
Due to [workspace form refactor PR](https://github.com/opensearch-project/OpenSearch-Dashboards/pull/7133) in OSD, some workspace integration test cases were failed across below files:
- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/workspace-plugin/mds_workspace_create.spec.js
- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/workspace-plugin/mds_workspace_import_sample_data_to.spec.js
- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/workspace-plugin/mds_workspace_overview.spec.js
- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/workspace-plugin/mds_workspace_update.spec.js
This PR aim to fix these failed test cases.
By submitting this pull request, I confirm …
> Fix workspace failed integration tests

- cypress.json
- cypress/integration/plugins/security-dashboards-plugin/inaccessible_tenancy_features.js
- cypress/integration/plugins/security-dashboards-plugin/readonly.js
- cypress/integration/plugins/security-dashboards-plugin/switch_tenant.js
- cypress/integration/plugins/security/permissions_spec.js
_**note**: this change already exists on main and was added via: https://github.com/opensearch-project/opensearch-dashboards-functional-test/pull/1444_
2.16 integ test build failed for securityDashboards:
https://ci.opensearch.org/ci/dbc/integ-test-opensearch-dashboards/2.16.0/7841/linux/arm64/tar/test-results/6098/integ-test/securityDashboards/with-security/cypress-screenshots/plugins/security/permissions_spec.js/Permissions+page+--+should+create+new+action+group+successfully+by+selecting+%60Create+from+selection%60+%28failed%29.png
cypress test-run video: https://ci.opensearch.org/ci/dbc/integ-test-opensearch-dashboards/2.16.0/7841/linux/arm64/tar/test-results/6098/integ-test/securityDashboards/with-security/cypress-videos/plugins/security/permissions_spec.js.mp4
The root-cause is …
> [2.x] Fixes flaky-ness in permissions spec test

- cypress/integration/plugins/alerting-dashboards-plugin/cluster_metrics_monitor_spec.js
- cypress/integration/plugins/alerting-dashboards-plugin/composite_level_monitor_spec.js
Cherry-picked fixes from PR https://github.com/opensearch-project/opensearch-dashboards-functional-test/pull/1305
Please backport this fix to 2.x, and 2.14 through 2.16.
> Fixed v2.15 alerting tests.

- .github/workflows/security-release-e2e-workflow.yml
- cypress/fixtures/plugins/security/permissions/actiongroups_post_new_creation_from_selection_response.json
- cypress/fixtures/plugins/security/permissions/actiongroups_post_new_creation_response.json
- cypress/integration/plugins/security-dashboards-plugin/sanity_tests.spec.js
- cypress/integration/plugins/security/permissions_spec.js
- Re-arranges the fixture load in a test to reflect the correct updates.
- Updates action-group names in fixture files.
- Related to https://github.com/opensearch-project/security-dashboards-plugin/issues/2055
> Fixes the permissions spec and related to fixtures to reflect correct action-group names

- cypress/integration/plugins/notifications-dashboards/1_email_senders_and_groups.spec.js
* This PR fixes the delete recepient group tests when security is enabled.
Tests passing locally
```
Couldn't determine Mocha version
Test create email senders
✓ creates ssl sender (23454ms)
✓ creates tls sender (9529ms)
✓ creates SES sender (7720ms)
Test edit senders
✓ edits sender email address (7649ms)
✓ edits ses sender region (6772ms)
Test delete senders
✓ deletes smtp senders (8828ms)
✓ deletes ses senders (9164ms)
Test create, edit and delete recipient group
✓ creates recipient group (13723ms)
✓ edits recipient group description (7658ms)
✓ opens email addresses popup (5351ms)
✓ deletes recipient groups (10181ms)
```
For more …
> fix tests to work with security enabled

- cypress/integration/plugins/security-analytics-dashboards-plugin/3_alerts.spec.js
Fixes alert related test by ensuring the filter dropdown is opened if not open already.
Passing tests:
> open dropdown if not open already

- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/data_explorer/index_pattern_without_field.spec.js
- cypress/utils/dashboards/vis_type_table/table.js
The test cleans up the index pattern after it has been used for the test. 
> Cleanup Index patterns after the test

- cypress/fixtures/plugins/security/permissions/actiongroups_post_new_creation_from_selection_response.json
- cypress/fixtures/plugins/security/permissions/actiongroups_post_new_creation_response.json
- cypress/integration/plugins/security/permissions_spec.js
Signed-off-by: Darshit Chanpura [dchanp@amazon.com](mailto:dchanp@amazon.com)
(cherry picked from commit https://github.com/opensearch-project/opensearch-dashboards-functional-test/commit/a8ba15a0175cc1684a020cac5712de12c99c68d9)
Description
Backports https://github.com/opensearch-project/opensearch-dashboards-functional-test/pull/1449 via https://github.com/opensearch-project/opensearch-dashboards-functional-test/commit/a8ba15a0175cc1684a020cac5712de12c99c68d9
Required manual backport because sanitty_test_spec.js file is not present in 2.16 but is changed in main.
- Related to https://github.com/opensearch-project/security-dashboards-plugin/issues/2055
For more information …
> [Backport 2.16] Fixes the permissions spec and related to fixtures to reflect correct action-group names (#1449)

- cypress/fixtures/plugins/security/permissions/actiongroups_post_new_creation_from_selection_response.json
- cypress/fixtures/plugins/security/permissions/actiongroups_post_new_creation_response.json
- cypress/integration/plugins/security/permissions_spec.js
Signed-off-by: Darshit Chanpura <dchanp@amazon.com>
(cherry picked from commit a8ba15a0175cc1684a020cac5712de12c99c68d9)
Backports #1449 via a8ba15a0175cc1684a020cac5712de12c99c68d9
Required manual backport because `sanitty_test_spec.js` file is not present in 2.x but is changed in main.
> [Backport 2.x] Fixes the permissions spec and related to fixtures to reflect correct action-group names (#1449)

- cypress/integration/plugins/custom-import-map-dashboards/4_documentsLayer.spec.js
Add wait before selecting layer
https://github.com/opensearch-project/dashboards-maps/issues/642
> [Maps] Add wait before select layer

- cypress/integration/plugins/alerting-dashboards-plugin/bucket_level_monitor_spec.js
- cypress/integration/plugins/alerting-dashboards-plugin/query_level_monitor_spec.js
Fixed alerting cypress tests.
Please backport this PR to 2.x, and 2.16.
The 2 tests updated by this PR are passing on a docker image cluster with security enabled.
https://github.com/opensearch-project/alerting-dashboards-plugin/issues/1011
> Fixed alerting cypress tests.

- cypress/integration/plugins/index-management-dashboards-plugin/aliases.js
There is flaky test where checkbox is not getting selected in windows run.
> select checkbox via id instead of class name

- cypress/fixtures/plugins/notifications-dashboards/test_chime_channel.json
- cypress/fixtures/plugins/notifications-dashboards/test_slack_channel.json
- cypress/integration/plugins/notifications-dashboards/2_channels.spec.js
Manual backport of https://github.com/opensearch-project/opensearch-dashboards-functional-test/pull/1507
* add ; to tests
Signed-off-by: Riya Saxena <riysaxen@amazon.com>
* fix channel tests in notifications
Signed-off-by: Riya Saxena <riysaxen@amazon.com>
* fix channel tests in notifications
Signed-off-by: Riya Saxena <riysaxen@amazon.com>
---------
Signed-off-by: Riya Saxena <riysaxen@amazon.com>
(cherry picked from commit 09bf9ce4d661b3f287a3d6454da89be2fafeaf6e) …
> [Backport 2.16] Fix channel tests (#1507)

- cypress/fixtures/plugins/notifications-dashboards/test_chime_channel.json
- cypress/fixtures/plugins/notifications-dashboards/test_slack_channel.json
- cypress/integration/plugins/notifications-dashboards/2_channels.spec.js
Manual backport for 2.x for https://github.com/opensearch-project/opensearch-dashboards-functional-test/pull/1507
* add ; to tests
Signed-off-by: Riya Saxena <riysaxen@amazon.com>
* fix channel tests in notifications
Signed-off-by: Riya Saxena <riysaxen@amazon.com>
* fix channel tests in notifications
Signed-off-by: Riya Saxena <riysaxen@amazon.com>
---------
Signed-off-by: Riya Saxena <riysaxen@amazon.com>
(cherry picked from commit 09bf9ce4d661b3f287a3d6454da89be2fafeaf6e) …
> [Backport 2.x] Fix channel tests (#1507)

- cypress/integration/plugins/index-management-dashboards-plugin/rollups_spec.js
- cypress/integration/plugins/index-management-dashboards-plugin/transforms_spec.js
Reordering tests in rollups and transform as checking enable/disbale feature after deleting transform/rollup creates flakiness.
https://github.com/opensearch-project/index-management-dashboards-plugin/issues/1095
> Rollup and Transform flaky test fix

- cypress/integration/plugins/observability-dashboards/4_panels.spec.js
The test fails if a base path is set, which doesn't show up as a problem in GH CI but does in other CI pipelines. Will need backport to 2.x for 2.17.
N/A
> Fix panel test not respecting base path setting

- cypress/fixtures/plugins/security-analytics-dashboards-plugin/integration_tests/index/create_dns_settings.json
- cypress/fixtures/plugins/security-analytics-dashboards-plugin/integration_tests/index/create_windows_settings.json
- cypress/fixtures/plugins/security-analytics-dashboards-plugin/sample_dns_index_settings.json
- cypress/fixtures/plugins/security-analytics-dashboards-plugin/sample_network_index_settings.json
- cypress/fixtures/plugins/security-analytics-dashboards-plugin/sample_windows_index_settings.json
Removed some unnecessary index settings from test indexes.
Please backport this PR to 2.15, 2.16, and 2.x.
All tests pass locally.
> Security analytics tests - removed test index settings.

- cypress/integration/plugins/anomaly-detection-dashboards-plugin/create_detector_spec.js
- cypress/integration/plugins/anomaly-detection-dashboards-plugin/detector_configuration_spec.js
- cypress/integration/plugins/anomaly-detection-dashboards-plugin/historical_analysis_spec.js
- cypress/integration/plugins/anomaly-detection-dashboards-plugin/overview_spec.js
- cypress/integration/plugins/anomaly-detection-dashboards-plugin/sample_detector_spec.js
- cypress/integration/plugins/anomaly-detection-dashboards-plugin/vis_augmenter/associate_detector_spec.js
- cypress/integration/plugins/anomaly-detection-dashboards-plugin/vis_augmenter/augment_vis_saved_object_spec.js
- cypress/integration/plugins/anomaly-detection-dashboards-plugin/vis_augmenter/view_anomaly_events_spec.js
This PR addresses intermittent failures in the AD Cypress tests related to a known issue in Cypress (https://github.com/cypress-io/cypress/issues/25397). The specific failure observed was:
```
Sample detector
"before all" hook for "Empty message with modal":
AssertionError: Timed out retrying after 60000ms: Expected to find element: `[data-test-subj="viewSampleDetectorLink"]`, but never found it.
```
To mitigate this issue, we applied a workaround suggested in the GitHub issue, ensuring that cy.visit is executed before cy.request. This change helps stabilize the tests by properly loading AD overview page  before making any API requests.
Testing:
* Ran all Cypress tests with the modified code to verify the fix.
By submitting this pull request, I confirm that my contribution is made under …
> Fix Cypress Test Flakiness by Executing cy.visit Before cy.request

- cypress/integration/plugins/custom-import-map-dashboards/5_add_map_to_dashboard.spec.js
- cypress/integration/plugins/custom-import-map-dashboards/7_enable_new_home_ui.spec.js
This PR:
1. Add new home ui test for maps dashboards
2. Fix failure in add_map_to_dashboard case
https://github.com/opensearch-project/dashboards-maps/issues/649
https://github.com/opensearch-project/dashboards-maps/issues/663
> Add new home ui test for maps

- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/data_explorer/discover_advanced_settings.spec.js
> Fix Flaky Discover Tests

- cypress/integration/plugins/security-analytics-dashboards-plugin/2_rules.spec.js
Fixes issue with Rules spec in Security Analytics
https://github.com/opensearch-project/security-analytics-dashboards-plugin/issues/1122
> [2.17][Security analytics] Bypass element overlap when typing

- cypress/integration/plugins/observability-dashboards/2_trace_analytics_services.spec.js
- cypress/integration/plugins/observability-dashboards/3_trace_analytics_traces.spec.js
- cypress/integration/plugins/observability-dashboards/6_notebooks.spec.js
- cypress/utils/plugins/observability-dashboards/constants.js
Fixes tests using the timepicker previously using the string 'Refresh' to now use the updated data-test-subj attribute since that string is not guaranteed to be there.
Fixes notebooks tests using the old header value to grab the specified notebook
> fixes observability dashboards tests

- cypress/integration/plugins/reports-dashboards/02-edit.spec.js
Fixes reporting dashboards test where an input element is covered by another element, the test was modified to force click on that element.
> Fix reports dashboards test

- cypress/integration/plugins/custom-import-map-dashboards/7_enable_new_home_ui.spec.js
Skip new home UI test if disabled in OSD
> [Maps plugin] Skip new home UI test if disabled in OSD

- cypress/fixtures/plugins/security-analytics-dashboards-plugin/integration_tests/rule/create_dns_rule_with_type_selection.json
- cypress/utils/plugins/security-analytics-dashboards-plugin/commands.js
1. Added short wait to help reduce flakiness.
2. Gave rule unique ID.
Please backport this PR back to v2.17.
The affected test class passes locally on a 2.17.1 security-enabled domain.
> Security analytics cypress test fixes.

- cypress/integration/plugins/dashboards-flow-framework/create_workflow_spec.js
- Updated flow framework dashboards test spec to match changes in https://github.com/opensearch-project/dashboards-flow-framework/pull/432
- Fixed flaky test spec 
> Update flow framework dashboards test spec

- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/data_explorer/discover.spec.js
- cypress/utils/dashboards/commands.js
Observe the following issue sometimes in OSD CI.
The bug is due to the query from a previous test response:200 is not cleaned out
```
it('should persist across refresh', function () {
// Set up query and filter
cy.setTopNavQuery('response:200');
cy.submitFilterFromDropDown('extension.raw', 'is one of', 'jpg');
cy.reload();
cy.getElementByTestId(`queryInput`).should('have.text', 'response:200');
cy.get('[data-test-subj~="filter-key-extension.raw"]').should(
'be.visible'
);
});
```
Therefore we add a function to manual clean out the query to make the test more robust.
NA …
> Clean query to make the test more robust

- cypress/integration/plugins/observability-dashboards/2_trace_analytics_services.spec.js
- cypress/integration/plugins/observability-dashboards/3_trace_analytics_traces.spec.js
- cypress/utils/plugins/observability-dashboards/constants.js
[Bug] updated traces and services tests with new refresh button
https://github.com/opensearch-project/opensearch-dashboards-functional-test/issues/1549
> [Bug] updated traces and services tests with new refresh button

- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/data_explorer/discover_advanced_settings.spec.js
seeing this error in CI
```
core-opensearch-dashboards/opensearch-dashboards/apps/data_explorer/discover_advanced_settings.spec.js
modifyColumnsOnSwitch advanced setting
- check columns still available after switching data sources in legacy table
âœ“ check columns still available after switching data sources in new table (39154ms)
16 passing (8m)
1 pending
1 failing
1) discover_advanced_setting
searchOnPageLoad advanced setting
check refresh data button is displayed when searchOnPageLoad is set as false:
AssertionError: Timed out retrying after 60000ms: Expected to find content: 'Refresh data' within the element: <span.euiButton__text.euiSuperUpdateButton__text> but never did.
at Context.eval (http://localhost:5601/__cypress/tests?p=cypress/integration/core-opensearch-dashboards/opensearch …
```
> make modifyColumnsOnSwitc test more robust

- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/data_explorer/discover_advanced_settings.spec.js
ciGroup6 is still flaky on the same test after previous commit. We will have to add a data-test-subj for refresh data button in OSD. Here is the PR https://github.com/opensearch-project/OpenSearch-Dashboards/pull/8782 and here is the ftr update https://github.com/opensearch-project/opensearch-dashboards-functional-test/pull/1618. 
For now, to unblock progress, we will skip this test for 2.18
na
> skip searchOnPageLoad test in 2.18

- cypress/integration/plugins/dashboards-flow-framework/create_workflow_spec.js
Updates a few button IDs in the modal for editing different form values. Buttons were added & updated as part of this meta issue: https://github.com/opensearch-project/dashboards-flow-framework/issues/446
> Update modal buttons for FF tests

- .github/workflows/cypress-workflow-bundle-snapshot-based-ci-groups.yml
- .github/workflows/release-e2e-workflow-template.yml
This PR is for fixing upload artifact error due to duplicate artifact names. Here is a failed example:
https://github.com/opensearch-project/opensearch-dashboards-functional-test/actions/runs/11659889509/job/32461200995?pr=999
The root cause was a breaking change in [upload-artifact v4](https://github.com/actions/upload-artifact?tab=readme-ov-file#breaking-changes) from [this PR](https://github.com/opensearch-project/opensearch-dashboards-functional-test/pull/1545). This action no longer support same upload artifact name. …
> Fix duplicate test cypress result name

- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/workspace-plugin/mds_workspace_analytics_overviews.spec.js
- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/workspace-plugin/mds_workspace_essential_overviews.spec.js
- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/workspace-plugin/mds_workspace_search_overviews.spec.js
- cypress/utils/commands.js
Add cypress test for essential/search/analytics overview page
> Add cypress test for workspace overview page

- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/workspace-plugin/mds_workspace_collaborators.spec.js
- cypress/utils/dashboards/workspace-plugin/commands.js
add tests for workspace collaborators page
> [Workspace] add tests for workspace collaborators page

- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/workspace-plugin/mds_workspace_assets.spec.js
Add integration test cases for workspace assets.
> [workspace] Add integration test cases for workspace assets.

- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/workspace-plugin/mds_workspace_acl.spec.js
This PR introduces ACL related test cases for workspace.
> [Workspace] Add ACL related test cases

- .github/CODEOWNERS
- MAINTAINERS.md
Backport 110d2704128f4cb8abe058b5aa102f837cb696e1 from #1649
> [Backport 2.x]feat: add yubonluo as maintain (#1649)

- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/workspace-plugin/mds_workspace_association.spec.js
add tests for data source association and dissociation
> [Workspace] add tests for data source association and dissociation

- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/workspace-plugin/mds_workspace_create.spec.js
1. Create a workspace from home page
2. Jump to collaborators page after creating a workspace.
3. The card on the right summarizes the information.
> Add test cases for workspace creation

- cypress/integration/plugins/dashboards-flow-framework/create_workflow_spec.js
Some low-level checks on the responses from ingest/search caused some tests to fail after https://github.com/opensearch-project/dashboards-flow-framework/pull/509
This PR simplifies the logic checking. How responses are rendered may soon change, which would require further changes later. Removing the lower-level checks to prevent flakiness and minimize test rewriting.
> Simplify api response info for FF tests

- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/workspace-plugin/mds_workspace_copy.spec.js
- cypress/utils/dashboards/workspace-plugin/test-cases/mds_workspace_copy.cases.js
> [Workspace] add copy functional tests

- cypress/integration/plugins/observability-dashboards/2_trace_analytics_services.spec.js
- cypress/integration/plugins/observability-dashboards/3_trace_analytics_traces.spec.js
- cypress/integration/plugins/observability-dashboards/6_notebooks.spec.js
- cypress/utils/plugins/observability-dashboards/constants.js
Update traces and services tests to use data-test-subj instead of searching for string "Refresh" to click refresh button
Update notebooks to use just data-test-subj for checking header and updated delete button
Services:
Traces:
Notebooks:
> Update observability dashboards tests

- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/data_explorer/shared_links.spec.js
Revert https://github.com/opensearch-project/opensearch-dashboards-functional-test/pull/932 as 2.x can correctly decode. Currently this test causes ciGroup9 fail and block CI.
NA
```
ananzh@88665a1f0502 opensearch-dashboards-functional-test % yarn cypress run --spec "cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/data_explorer/shared_links.spec.js"
yarn run v1.22.21
warning ../../package.json: No license field
$ /Users/ananzh/Work/opensearch-dashboards-functional-test/node_modules/.bin/cypress run --spec cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/data_explorer/shared_links.spec.js
====================================================================================================
(Run Starting) …
```
> Fix shared link test in 2.x for 2.19

- cypress/integration/plugins/dashboards-flow-framework/create_workflow_spec.js
Updates the Flow Framework tests to work properly with the latest UX overhauls.
> Update Flow Framework tests

- cypress/integration/plugins/observability-dashboards/2_trace_analytics_services.spec.js
- cypress/integration/plugins/observability-dashboards/6_notebooks.spec.js
Update notebooks and traces tests with dynamic wait. This helps to verify existence of DOM and only then clicking them
We saw in the latest 2.19 RCs the notebooks test and trace services test fail for the below cases:
- https://ci.opensearch.org/ci/dbc/integ-test-opensearch-dashboards/2.19.0/8251/linux/x64/tar/test-results/6948/integ-test/observabilityDashboards/with-security/cypress-screenshots/plugins/observability-dashboards/2_trace_analytics_services.spec.js/Testing+services+table+--+Opens+service+flyout+%28failed%29.png
- https://ci.opensearch.org/ci/dbc/integ-test-opensearch-dashboards/2.19.0/8251/linux/x64/tar/test-results/6948/integ-test/observabilityDashboards/with-security/cypress-screenshots/plugins/observability-dashboards/6_notebooks.spec.js/Testing+notebook+actions+--+Creates …
> Update notebooks and traces tests with dynamic wait

- cypress/integration/plugins/observability-dashboards/6_notebooks.spec.js
Update notebooks tests with wait for delete. This helps to ensure page renders before running delete flow.
https://ci.opensearch.org/ci/dbc/integ-test-opensearch-dashboards/2.19.0/8256/linux/arm64/tar/test-results/6964/integ-test/observabilityDashboards/with-security/cypress-screenshots/plugins/observability-dashboards/6_notebooks.spec.js/Test+reporting+integration+if+plugin+installed+--+View+reports+homepage+from+context+menu+--+after+all+hook+%28failed%29.png
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTR …
> Update notebooks test with delay for delete

- cypress/integration/plugins/dashboards-flow-framework/create_workflow_spec.js
https://github.com/opensearch-project/dashboards-flow-framework/pull/604 changed the logic such that a model _must_ be selected before creating presets, when the preset require them. This updates the tests to select the deployed model before trying to create.
> Add model selection in Flow Framework tests

- cypress/integration/plugins/custom-import-map-dashboards/7_enable_new_home_ui.spec.js
Fix overly strict disable check in flaky integ test added in #1587
When an element is disabled, the disabled property is not always set to `disabled='disabled'`. Sometimes it is set with `disabled=''` or as a property without a value, `disabled`. In those cases, the test would not be skipped and the integ test fails since the switch is still disabled.
> [Maps Plugin] Fix disable check in Maps new home integ tests

- cypress/integration/plugins/dashboards-flow-framework/create_workflow_spec.js
Add containsModels param to handle custom/empty template. We don't want to search for models for this template, which does not require one.
> [Flow Framework] Add containsModels param to handle custom/empty template

- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/left-navigation/left_navigation.spec.js
Add additional assertion to avoid flakiness.
This is caused by loading icon can appear/hide twice on the screen, once for loading the page (first loading) and once for loading the visualisation list (second loading). Between two loading period, the recent history button could appear on the screen for milliseconds and then being replaced by loading icon again by the second loading. 
In a rare slow network case, Cypress can potentially got the recent history button successfully during the interval between two loading period. However, when Cypress attempt to click on the button it already selected, the button itself could already disappear and being replaced by loading icon during the second loading, result in test failure.
This PR adds an additional assertion to ensure the page is fully …
> Improve the assertion in left navigation recent history test to avoid flakiness

- .github/workflows/left-navigation-release-e2e-workflow.yml
- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/left-navigation/left_navigation.spec.js
- cypress/integration/plugins/observability-dashboards/3_trace_analytics_traces.spec.js
- cypress/integration/plugins/observability-dashboards/6_notebooks.spec.js
Manually backport https://github.com/opensearch-project/opensearch-dashboards-functional-test/commit/947aaa0ba49539b249c4a8f39a45e35c37b780bc from https://github.com/opensearch-project/opensearch-dashboards-functional-test/pull/1707
N/A
> [Backport main] Add new test suite and workflow for left navigation menu

- cypress/integration/plugins/search-relevance-dashboards/2_search_card.spec.js
- cypress/utils/dashboards/workspace-plugin/test-cases/mds_workspace_search_overviews.cases.js
Move search relevance card to search plugin
```
yarn cypress run --spec cypress/integration/core-opensearch-dashboards/opensearch-dashboards/workspace-plugin/mds_workspace_search_overviews.spec.js
Search workspace overview
✓ Set up search cards display correctly (19982ms)
✓ Different search techniques section display correctly (5940ms)
2 passing (29s)
```
```
yarn cypress run --spec cypress/integration/plugins/search-relevance-dashboards/2_search_card.spec.js  
Search card
✓ Configure and evaluate search cards should display correctly (20396ms)
1 passing (23s)
```
N/A …
> Move search relevance card tests to search plugin

- .github/workflows/release-e2e-workflow-template.yml
- cypress/integration/plugins/reports-dashboards/04-download.spec.js
Fixed flakey download of CSV test
> [BUG]added fix for csv downloads in reports-2.11

- .github/workflows/release-e2e-workflow-template.yml
- cypress/integration/plugins/reports-dashboards/04-download.spec.js
Updated flakey test in reporting Homepage
> [BUG]Reports flakey test fix for 2.5

- cypress/integration/plugins/observability-dashboards/3_trace_analytics_traces.spec.js
- cypress/integration/plugins/observability-dashboards/4_panels.spec.js
- cypress/utils/plugins/observability-dashboards/constants.js
To fix `2_trace_analytics_services`, SERVICE_SPAN_ID (which only only used for this one instance) was changed to be the first sample trace instead of the last, hidden one.
To fix `3_trace_analytics_traces`, the network call outgoing from the refresh button was intercepted and waited on for completion.
To fix `4_panels_space`, an intercept for the saved object visualization wait waited on, and for a later failing point, a clone panel network call was intercepted and waited on. …
> fix dashboards-observability 2.3 tests

- cypress/integration/plugins/observability-dashboards/3_trace_analytics_traces.spec.js
- cypress/integration/plugins/observability-dashboards/4_panels.spec.js
- cypress/integration/plugins/observability-dashboards/6_notebooks.spec.js
Added a typing delay to traces test as to not miss letters.
Added a ppl search call intercept for panels, for the entire page to load.
Added a saved object search intercept for it to finish in notebooks test clean up.
> dashboards-observability flakey test mitigation

- cypress/integration/plugins/query-workbench-dashboards/ui.spec.js
Fixes the query workbench test to intercept the ppl query network call for the results to disseminate and the needed element to appear.
> query workbench intercept ppl query network call

- package-lock.json
- package.json
Bump nano id to 3.3.8 to fix CVE 2024-55565
> Fix CVE-2024-55565

- cypress/integration/plugins/reports-dashboards/02-edit.spec.js
- cypress/integration/plugins/reports-dashboards/04-download.spec.js
Updated edit spec and download test in 2.7(match gitfarm)
Cypress ✓ Download from reporting homepage (22386ms) 2025-02-21 20:29:25.546 Cypress[60505:67188855] +[IMKClient subclass]: chose IMKClient_Modern 2025-02-21 20:29:25.546 Cypress[60505:67188855] +[IMKInputSession subclass]: chose IMKInputSession_Modern ✓ Download pdf from in-context menu (6225ms) ✓ Download png from in-context menu (6357ms) ✓ Download csv from saved search in-context menu (18554ms) ✓ Download from Report definition details page (63990ms)
5 passing (2m)
(Results)
┌────────────────────────────────────────────────────────────────────────────────────────────────┐ │ Tests: 5 │ │ Passing: 5 │ │ Failing: 0 │ │ Pending: 0 │ │ Skipped: 0 │ │ Screenshots: 0 │ │ Video: true │ │ Duration: 1 minute, 58 seconds │ │ Spec Ran: …
> [Bug]Fix flakey reports test in 2.7

- cypress/integration/plugins/reports-dashboards/02-edit.spec.js
- cypress/integration/plugins/reports-dashboards/04-download.spec.js
Updated edit spec and download test in 2.5(match gitfarm)
Cypress ✓ Download from reporting homepage (22386ms) 2025-02-21 20:29:25.546 Cypress[60505:67188855] +[IMKClient subclass]: chose IMKClient_Modern 2025-02-21 20:29:25.546 Cypress[60505:67188855] +[IMKInputSession subclass]: chose IMKInputSession_Modern ✓ Download pdf from in-context menu (6225ms) ✓ Download png from in-context menu (6357ms) ✓ Download csv from saved search in-context menu (18554ms) ✓ Download from Report definition details page (63990ms)
5 passing (2m)
(Results)
┌────────────────────────────────────────────────────────────────────────────────────────────────┐ │ Tests: 5 │ │ Passing: 5 │ │ Failing: 0 │ │ Pending: 0 │ │ Skipped: 0 │ │ Screenshots: 0 │ │ Video: true │ │ Duration: 1 minute, 58 seconds │ │ Spec Ran: …
> [Bug]Fix flakey reports test in 2.5

- cypress/integration/plugins/custom-import-map-dashboards/0_add_saved_object.js
- cypress/integration/plugins/custom-import-map-dashboards/1_import_vector_map_tab.spec.js
- cypress/integration/plugins/custom-import-map-dashboards/2_opensearchMapLayer.spec.js
- cypress/integration/plugins/custom-import-map-dashboards/3_add_saved_object.spec.js
- cypress/integration/plugins/custom-import-map-dashboards/4_documentsLayer.spec.js
- cypress/integration/plugins/custom-import-map-dashboards/5_add_map_to_dashboard.spec.js
- cypress/integration/plugins/custom-import-map-dashboards/6_geojson_file_upload.spec.js
- cypress/integration/plugins/custom-import-map-dashboards/7_enable_new_home_ui.spec.js
dashboards-maps integration tests failed to load home page when using cypress while the home page is loading normally without cypress.
- adding cy.visit to base url in before function to fix the issue
- all integ tests passed
https://github.com/opensearch-project/dashboards-maps/issues/710
> fix dashboards-maps integ tests by adding a visit to base url

- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/data_explorer/field_data.spec.js
Wait for search table visible to ensure render is complete.
Attempting to fix a failed test discovered by introducing a code change in OSD
https://github.com/opensearch-project/OpenSearch-Dashboards/pull/9541  
> Add wait for field data test

- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/data_explorer/discover.spec.js
Fix `should reload the saved search with persisted query to show the initial hit count` tests which was failing due to previous test suite not cleaning up the query bar upon completion.
> Fix Discover Saved Search Test

- .github/workflows/assistant-release-e2e-workflow.yml
- .github/workflows/release-e2e-workflow-template.yml
- cypress/fixtures/plugins/dashboards-assistant/agent-framework-thought-response.json
- cypress/fixtures/plugins/dashboards-assistant/flow-template.json
- cypress/integration/plugins/dashboards-assistant/conversation_save_to_notebook_spec.js
- cypress/integration/plugins/dashboards-assistant/mds_chatbot_agent_framework_spec.js
- cypress/integration/plugins/dashboards-assistant/mds_chatbot_default_data_source_change.js
- cypress/integration/plugins/dashboards-assistant/mds_chatbot_interaction_trace_spec.js
- cypress/integration/plugins/dashboards-assistant/mds_chatbot_sidecar_spec.js
- cypress/integration/plugins/dashboards-assistant/mds_conversation_history_spec.js
- cypress/integration/plugins/dashboards-assistant/mds_feedback_spec.js
- cypress/support/assistant-dummy-llm.js
Fix dashboard-assistant test
Deprecate CatIndexTool and use ListIndexTool
> Fix Integration test

- .github/actions/start-opensearch/action.yml
- .github/workflows/release-e2e-workflow-template.yml
- cypress.json
- cypress/fixtures/plugins/anomaly-detection-dashboards-plugin/sample_remote_test_data.txt
- cypress/integration/plugins/anomaly-detection-dashboards-plugin/create_remote_detector_spec.js
- cypress/plugins/index.js
- cypress/utils/commands.js
Adding remote detector integration tests for anomaly detection plugin
> adding ad remote index tests

- cypress/integration/plugins/reports-dashboards/04-download.spec.js
Fix reporting dashboard test,
Download pdf from in-context menu
was failing because cypress was looking for nested structure.
Now passing:
> ReportingDashboard - Test fix

- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/vis_type_table/data.spec.js
- cypress/utils/commands.js
The test fixes the inconsistency due to concurrent searches by force merging the segments into a single one and performing searches. 
https://github.com/opensearch-project/OpenSearch/issues/18149
> Fix OSD CI group2 tests

- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/vis_type_table/data.spec.js
- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/vis_type_table/embed.spec.js
- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/vis_type_table/options.spec.js
- cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/vis_type_table/split.spec.js
This aims to fix flaky Discover tests. 
```
yarn cypress run --headless --spec "cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/vis_type_table/*"
yarn run v1.22.22
$ /Users/suchsah/Documents/Dashboards-tests/node_modules/.bin/cypress run --headless --spec 'cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/vis_type_table/*'
====================================================================================================
(Run Starting)
│ Cypress:        9.5.4                                                                          │
│ Browser:        Electron 94 (headless)                                                         │
│ Node …
```
> Fix Discover Flaky Tests

- .github/workflows/assistant-release-e2e-workflow.yml
- cypress/fixtures/plugins/alerting-dashboards-plugin/sample_query_level_monitor_for_alert_summary.json
- cypress/fixtures/plugins/dashboards-assistant/data2summary-response.json
- cypress/fixtures/plugins/dashboards-assistant/flow-templates/data2summary.json
- cypress/fixtures/plugins/dashboards-assistant/flow-templates/suggest-ad.json
- cypress/fixtures/plugins/dashboards-assistant/flow-templates/summary.json
- cypress/fixtures/plugins/dashboards-assistant/flow-templates/summary_with_log_pattern.json
- cypress/fixtures/plugins/dashboards-assistant/suggest-ad-response.json
- cypress/fixtures/plugins/dashboards-assistant/summary-response.json
- cypress/fixtures/plugins/dashboards-assistant/summary-with-log-pattern-response.json
- cypress/integration/plugins/dashboards-assistant/mds_query_enhancements_alert_summary_spec.js
- cypress/integration/plugins/dashboards-assistant/mds_query_enhancements_data2summary_spec.js
- cypress/integration/plugins/dashboards-assistant/mds_query_enhancements_suggest_anomaly_detector_spec.js
- cypress/support/assistant-dummy-llm.js
- cypress/utils/plugins/alerting-dashboards-plugin/commands.js
- cypress/utils/plugins/dashboards-assistant/commands.js
- cypress/utils/plugins/dashboards-assistant/constants.js
This PR add integration tests for Assistant, mainly includes changes below:
- Add integration tests for alert summary in alert page.
- Add integration tests for discovery summary in discovery page.
- Add integration tests for anonymous detect in discovery page.
Related PR: https://github.com/opensearch-project/opensearch-dashboards-functional-test/pull/1783
> [Manual backport] Feat: add tests for alert summary, discovery summary and anonymous detect

- cypress/integration/plugins/search-relevance-dashboards/1_query_compare.spec.js
- Fix integ tests failure due to a change on dashboards-search-relevance router
https://github.com/user-attachments/assets/e4287098-b5e9-4be8-ac29-253a70e43a8b
- https://github.com/opensearch-project/dashboards-search-relevance/issues/512
> update dashboards-search-relevance router

- package-lock.json
- package.json
Bump serialize-javascript version to greater than 6.0.2 to avoid XSS.
The dependency comes from mocha 10.2.0, and mocha is the dependency of `cypress-multi-reporters` and `mocha-junit-reporter`
```
├─┬ cypress-multi-reporters@1.5.0
│ └── mocha@10.2.0
└─┬ mocha-junit-reporter@2.0.0
└── mocha@10.2.0 deduped
```
So we choose overrides to upgrade the deep dependency.
> [CVE] serialize-javascript

- cypress/integration/plugins/search-relevance-dashboards/3_query_set_creation.spec.js
- cypress/integration/plugins/search-relevance-dashboards/4_search_configuration_creation.spec.js
- cypress/integration/plugins/search-relevance-dashboards/5_judgment_creation.spec.js
After resource creation, add validation for list and view to make sure all resources created successfully
```
Spec                                              Tests  Passing  Failing  Pending  Skipped  
│ ✔  plugins/search-relevance-dashboards      00:52        1        1        -        -        - │
│    /1_query_compare.spec.js                                                                    │
├────────────────────────────────────────────────────────────────────────────────────────────────┤
│ ✔  plugins/search-relevance-dashboards        2ms        -        -        -        -        - │
│    /2_search_card.spec.js                                                                      │ …
```
> add search-relevance workbench list/view

- cypress/fixtures/plugins/dashboards-flow-framework/search_models_response.json
- cypress/integration/plugins/dashboards-flow-framework/create_workflow_spec.js
- cypress/utils/plugins/dashboards-flow-framework/commands.js
- cypress/utils/plugins/dashboards-flow-framework/constants.js
Improves the Flow Framework OSD plugin tests by decoupling the connector creation step for improved flexibility & less flakiness when running the tests against different endpoints with different security standards. For example, an Amazon OpenSearch Service (AOS) domain prohibits remote connector creation, so these tests cannot run out-of-the-box against such endpoints. This fixes that, by mocking the connector creation entirely if the step fails.
Includes several other minor improvements to minimize flakiness, such as the model deployment call and scoped-down mocking checks during ingest and search. 
Tested against local domain with no security, and against an AOS domain with basic auth. Both scenarios succeed without any changes to the test file:
```
Spec …
```
> Decouple connector creation for FF tests

- integtest.sh
Ensure windows install cypress based on ci bucket source
https://build.ci.opensearch.org/blue/organizations/jenkins/integ-test-opensearch-dashboards/detail/integ-test-opensearch-dashboards/7659/pipeline/
```
npm ERR! Platform: win32-x64 (10.0.17763)
npm ERR! Cypress Version: 9.5.4
npm ERR! [FAILED] The Cypress App could not be downloaded.
```
Test by force cypress in package.json to be 9.7.0 but 9.5.4 still installed.
```
npm info run cypress@9.7.0 postinstall node_modules/cypress node index.js --exec install
npm info run cypress@9.7.0 postinstall { code: 0, signal: null }
$ cypress --version
Cypress package version: 9.7.0
Cypress binary version: 9.5.4
Electron version: 15.3.5
Bundled Node version:
16.5.0
```
By submitting this pull request, I confirm that my contribution is made under …
> Ensure windows install cypress based on ci bucket source

- cypress/integration/plugins/anomaly-detection-dashboards-plugin/forecaster_list_spec.js
- cypress/utils/plugins/anomaly-detection-dashboards-plugin/commands.js
This PR:
* Create `cy.handleTenantDialog` custom command to handle the optional  **"Select your tenant"** pop-up.
* Refactor `forecaster_list_spec.js` and `createForecaster` helper to leverage the new command, reducing duplicate code.
* Introduce explicit waits (`cy.contains('Loading OpenSearch Dashboards').should('not.exist')`, `cy.wait(500)`) and additional `cy.log` statements to handle cases where the home page loads slowly, improving stability and aiding debugging.
* Replace thrown error during action-menu retries with a `cy.log` to enable fallback logic in future enhancements.
* Implement fallback logic to use **"Stop forecasting"** when the **"Cancel forecast"** modal  
does not appear, covering both *Initializing* and *Running* forecast states. …
> extract tenant-dialog helper & improve forecaster list test robustness

- cypress/integration/plugins/anomaly-detection-dashboards-plugin/daily_forecaster_spec.js
- cypress/integration/plugins/anomaly-detection-dashboards-plugin/forecaster_list_spec.js
- cypress/integration/plugins/anomaly-detection-dashboards-plugin/forecaster_list_spec_mock.js
- cypress/utils/plugins/anomaly-detection-dashboards-plugin/commands.js
backport the following to 3.1
https://github.com/opensearch-project/opensearch-dashboards-functional-test/pull/1823
https://github.com/opensearch-project/opensearch-dashboards-functional-test/pull/1835
https://github.com/opensearch-project/anomaly-detection-dashboards-plugin/issues/1072
> [backport to 3.1] test: improve resilience in forecast tests

- cypress/integration/plugins/anomaly-detection-dashboards-plugin/daily_forecaster_spec.js
- cypress/integration/plugins/anomaly-detection-dashboards-plugin/forecaster_list_spec.js
- cypress/integration/plugins/anomaly-detection-dashboards-plugin/forecaster_list_spec_mock.js
- cypress/utils/plugins/anomaly-detection-dashboards-plugin/commands.js
- In `daily_forecaster_spec.js`, after clicking the “Start test” button, wait for the “Initializing test” message before verifying “Test complete” to ensure previous messages have cleared and avoid race conditions.
- In `forecaster_list_spec.js`: • Preemptively set the tenant to “global” via localStorage within `onBeforeLoad` when visiting `/`—this avoids the non-deterministic “Select your tenant” popup. • Removed multiple scattered calls to `cy.handleTenantDialog()`, relying on tenant pre-setting instead. • Increased UI rendering wait from 500 ms to 2000 ms for menu visibility.
- In `forecaster_list_spec_mock.js`: • Applied the same “global” tenant override on page load to avoid the popup.
- In `commands.js`: • Added `typeInEuiCombo(testSubj, value)` Cypress command to reliably enter …
> test: improve resilience in forecast tests

- cypress/integration/plugins/anomaly-detection-dashboards-plugin/create_detector_spec.js
- cypress/integration/plugins/anomaly-detection-dashboards-plugin/create_remote_detector_spec.js
- cypress/integration/plugins/anomaly-detection-dashboards-plugin/forecaster_configuration_spec.js
- add Suggest Parameters flow in create_detector_spec.js and create_remote_detector_spec.js (open dialog, generate, apply, verify close)
- use stable EUI selectors for remote index picking (button[title="cluster:index"] instead of .euiComboBoxOption__content) to reduce flakiness
- inline resilient selectTopItemFromFilter + clickFirstFilterItem with retry logic in forecaster_configuration_spec.js; remove helper import and ensure combo box pill reflects selection
- add short waits where needed (e.g., before generating suggestions) to avoid transient errors when fields are not populated yet
For more information on following Developer Certificate of Origin and signing off your …
> test(ad): add Suggest parameters E2E and stabilize selections
